In [ ]:
!pip install nba_api
import requests
import pandas as pd
from datetime import datetime
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, commonteamroster
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display, HTML
import time

# Fetch today's games from NBA Stats API (JSON format)
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses
        data = response.json()

        today = datetime.now().strftime('%Y-%m-%d')
        games_today = []

        # Iterate through each month's schedule to find games for today
        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],  # Home team abbreviation
                        'away_team': game['v']['ta'],  # Away team abbreviation
                        'home_team_id': game['h']['tid'],  # Home team ID
                        'away_team_id': game['v']['tid']   # Away team ID
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch player game logs for the current season
def fetch_player_game_logs(player_id, season='2024-25'):
    retries = 3
    for attempt in range(retries):
        try:
            print(f"Fetching game logs for player ID: {player_id}")
            game_logs = playergamelog.PlayerGameLog(player_id=player_id, season=season, season_type_all_star='Regular Season').get_data_frames()[0]
            return game_logs
        except Exception as e:
            if attempt < retries - 1:
                print(f"Retrying game logs fetch for player {player_id} (Attempt {attempt + 1})...")
                time.sleep(5)
            else:
                print(f"Failed to fetch game logs for player {player_id}: {e}")
                return pd.DataFrame()

# Calculate per-player stats (Points, Rebounds, Assists)
def calculate_stats(stat_values):
    if len(stat_values) == 0:
        return None, None, None

    stat_values = pd.Series(stat_values).fillna(0)  # Fill NaN values with zero
    mean = round(stat_values.mean(), 2)
    std_dev = round(stat_values.std(), 2)
    cv = round(std_dev / mean, 2) if mean != 0 else None

    return mean, std_dev, cv

# Analyze today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team_id = game['home_team_id']
        away_team_id = game['away_team_id']
        home_team = game['home_team']
        away_team = game['away_team']

        print(f"Processing teams: {home_team} vs {away_team}")

        # Fetch player stats for both teams
        for team_id, team_name in [(home_team_id, home_team), (away_team_id, away_team)]:
            print(f"Processing team: {team_name}")
            try:
                team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                if not team_roster.empty:
                    for _, player in team_roster.iterrows():
                        try:
                            player_id = player['PLAYER_ID']
                            player_name = player['PLAYER']
                            print(f"Processing player: {player_name} (ID: {player_id})")

                            game_logs = fetch_player_game_logs(player_id)

                            if game_logs.empty:
                                continue

                            ppg_values = game_logs['PTS']
                            rpg_values = game_logs['REB']
                            apg_values = game_logs['AST']

                            mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(ppg_values)
                            mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(rpg_values)
                            mean_apg, std_dev_apg, cv_apg = calculate_stats(apg_values)

                            all_players_data.append({
                                'Player': player_name,
                                'Team': team_name,
                                'PPG': mean_ppg,
                                'PPG SD': std_dev_ppg,
                                'PPG CV': cv_ppg,
                                'RPG': mean_rpg,
                                'RPG SD': std_dev_rpg,
                                'RPG CV': cv_rpg,
                                'APG': mean_apg,
                                'APG SD': std_dev_apg,
                                'APG CV': cv_apg
                            })
                            time.sleep(1)
                        except Exception as e:
                            print(f"Error processing player {player_name}: {e}")
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    return pd.DataFrame(all_players_data)

# Display results as an HTML table in Jupyter Notebook
def display_results(df, stat_type):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)

    if stat_type == 'Points':
        sorted_df = df.sort_values('PPG CV', ascending=True)
        print("\nTop Players by Points CV:")
        display(HTML(sorted_df[['Player', 'Team', 'PPG', 'PPG SD', 'PPG CV']].to_html(index=False, justify='center')))
    elif stat_type == 'Rebounds':
        sorted_df = df.sort_values('RPG CV', ascending=True)
        print("\nTop Players by Rebounds CV:")
        display(HTML(sorted_df[['Player', 'Team', 'RPG', 'RPG SD', 'RPG CV']].to_html(index=False, justify='center')))
    elif stat_type == 'Assists':
        sorted_df = df.sort_values('APG CV', ascending=True)
        print("\nTop Players by Assists CV:")
        display(HTML(sorted_df[['Player', 'Team', 'APG', 'APG SD', 'APG CV']].to_html(index=False, justify='center')))

# Run the analysis and display the output
if __name__ == "__main__":
    print("Fetching data for today's games...")
    stats_data = analyze_teams_for_today()

    if not stats_data.empty:
        display_results(stats_data, 'Points')
        display_results(stats_data, 'Rebounds')
        display_results(stats_data, 'Assists')
    else:
        print("No games or data available for today.")

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Fetching data for today's games...
Processing teams: CHA vs NYK
Processing team: CHA
Processing player: Miles Bridges (ID: 1628970)
Fetching game logs for player ID: 1628970
Processing player: LaMelo Ball (ID: 1630163)
Fetching game logs for player ID: 1630163
Processing player: Grant Williams (ID: 1629684)
Fetching game logs for player ID: 1629684
Processing player: DaQuan Jeffries (ID: 1629610)
Fetching game logs for player ID: 1629610
Processing player: Nick Richards (ID: 1630208)
Fetching game logs for player ID: 1630208
Processing player: Mark Williams (ID: 1631109)
Fetching game logs for player ID: 1631109
Processing player: Nick Smith Jr. (ID: 1641733)
Fetching game logs for player ID: 1641733
Processing player: Josh Green (ID: 1630182)
Fetching game logs for player ID: 1630182
Processing player: Cody Martin (ID: 1628998)
Fetching game logs for player ID: 1628998
Processing player: Moussa Diabate (ID: 1631217)
Fetching game logs for player ID: 1631217
Processing player: Vasilije Micić (ID: 203995)
Fetching game logs for player ID: 203995
Processing player: Tre Mann (ID: 1630544)
Fetching game logs for player ID: 1630544
Processing player: Brandon Miller (ID: 1641706)
Fetching game logs for player ID: 1641706
Processing player: KJ Simpson (ID: 1642354)
Fetching game logs for player ID: 1642354
Processing player: Jared Rhoden (ID: 1631197)
Fetching game logs for player ID: 1631197
Processing player: Seth Curry (ID: 203552)
Fetching game logs for player ID: 203552
Processing player: Tidjane Salaün (ID: 1642275)
Fetching game logs for player ID: 1642275
Processing player: Taj Gibson (ID: 201959)
Fetching game logs for player ID: 201959

KeyboardInterrupt:

In [ ]:
# Required Libraries
!pip install nba_api
import requests
import pandas as pd
from datetime import datetime
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, commonteamroster
from IPython.display import display, HTML
import time

# Fetch today's games from NBA Stats API (JSON format)
def fetch_schedule():
    url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
    response = requests.get(url)
    data = response.json()

    # Get today's date in the format used in the JSON
    today = datetime.now().strftime('%Y-%m-%d')

    # Extract games for today
    games_today = []
    for month_data in data['lscd']:  # Loop through each month's schedule
        for game in month_data['mscd']['g']:  # Extract each game
            if game['gdte'] == today:  # Match today's date
                games_today.append(game)

    return games_today

# Fetch player game logs for the current season
def fetch_player_game_logs(player_id, season='2024-25'):
    retries = 3
    for attempt in range(retries):
        try:
            game_logs = playergamelog.PlayerGameLog(player_id=player_id, season=season, season_type_all_star='Regular Season').get_data_frames()[0]
            return game_logs
        except Exception as e:
            if attempt < retries - 1:
                time.sleep(5)
            else:
                return pd.DataFrame()

# Calculate statistics for a list of values
def calculate_stats(stat_values):
    if len(stat_values) == 0:
        return None, None, None

    mean = sum(stat_values) / len(stat_values)
    std_dev = pd.Series(stat_values).std()
    cv = std_dev / mean if mean != 0 else None

    # Ensure that None values are handled before rounding
    mean = round(mean, 2) if mean is not None else None
    std_dev = round(std_dev, 2) if std_dev is not None else None
    cv = round(cv, 2) if cv is not None else None

    return mean, std_dev, cv

# Analyze today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team_id = game['h']['tid']  # Home team ID
        away_team_id = game['v']['tid']  # Away team ID
        home_team = game['h']['ta']  # Home team abbreviation
        away_team = game['v']['ta']  # Away team abbreviation

        for team_id, team_name in [(home_team_id, home_team), (away_team_id, away_team)]:
            team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

            if not team_roster.empty:
                for _, player in team_roster.iterrows():
                    player_id = player['PLAYER_ID']
                    player_name = player['PLAYER']
                    position = player['POSITION']

                    game_logs = fetch_player_game_logs(player_id)

                    if game_logs.empty:
                        continue

                    ppg_values = game_logs['PTS'].tolist()
                    rpg_values = game_logs['REB'].tolist()
                    apg_values = game_logs['AST'].tolist()

                    mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(ppg_values)
                    mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(rpg_values)
                    mean_apg, std_dev_apg, cv_apg = calculate_stats(apg_values)

                    all_players_data.append({
                        'Player': f"{player_name} ({position})",
                        'Team': team_name,
                        'PPG': mean_ppg, 'PPG SD': std_dev_ppg, 'PPG CV': cv_ppg,
                        'RPG': mean_rpg, 'RPG SD': std_dev_rpg, 'RPG CV': cv_rpg,
                        'APG': mean_apg, 'APG SD': std_dev_apg, 'APG CV': cv_apg
                    })

    return pd.DataFrame(all_players_data)

# Display results sorted by consistency (lowest CV first)
def display_sorted_stats(df, category):
    if category == 'Points':
        stats = df[['Player', 'Team', 'PPG', 'PPG SD', 'PPG CV']].sort_values(by='PPG CV').dropna()
    elif category == 'Rebounds':
        stats = df[['Player', 'Team', 'RPG', 'RPG SD', 'RPG CV']].sort_values(by='RPG CV').dropna()
    elif category == 'Assists':
        stats = df[['Player', 'Team', 'APG', 'APG SD', 'APG CV']].sort_values(by='APG CV').dropna()
    else:
        print(f"Unknown category: {category}")
        return

    print(f"\nTop Players by {category} Consistency (Lowest CV):")
    display(HTML(stats.to_html(index=False)))

# Run the analysis
if __name__ == "__main__":
    print("Fetching data for today's games...")
    stats_data = analyze_teams_for_today()

    if not stats_data.empty:
        display_sorted_stats(stats_data, 'Points')
        display_sorted_stats(stats_data, 'Rebounds')
        display_sorted_stats(stats_data, 'Assists')
    else:
        print("No games or data available for today.")

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Fetching data for today's games...
No games scheduled for today.
No games or data available for today.

In [ ]:
!pip install nba_api openpyxl
import requests
import pandas as pd
from datetime import datetime
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, commonteamroster
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display, HTML
import os
import time

# Fetch today's games from NBA Stats API (JSON format)
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses
        data = response.json()

        today = datetime.now().strftime('%Y-%m-%d')
        games_today = []

        # Iterate through each month's schedule to find games for today
        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],  # Home team abbreviation
                        'away_team': game['v']['ta'],  # Away team abbreviation
                        'home_team_id': game['h']['tid'],  # Home team ID
                        'away_team_id': game['v']['tid']   # Away team ID
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch player game logs for the current season
def fetch_player_game_logs(player_id, season='2024-25'):
    retries = 3
    for attempt in range(retries):
        try:
            print(f"Fetching game logs for player ID: {player_id}")
            game_logs = playergamelog.PlayerGameLog(player_id=player_id, season=season, season_type_all_star='Regular Season').get_data_frames()[0]
            return game_logs
        except Exception as e:
            if attempt < retries - 1:
                print(f"Retrying game logs fetch for player {player_id} (Attempt {attempt + 1})...")
                time.sleep(5)
            else:
                print(f"Failed to fetch game logs for player {player_id}: {e}")
                return pd.DataFrame()

# Calculate per-player stats (Points, Rebounds, Assists)
def calculate_stats(stat_values):
    if len(stat_values) == 0:
        return None, None, None

    stat_values = pd.Series(stat_values).fillna(0)  # Fill NaN values with zero
    mean = round(stat_values.mean(), 2)
    std_dev = round(stat_values.std(), 2)
    cv = round(std_dev / mean, 2) if mean != 0 else None

    return mean, std_dev, cv

# Analyze today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team_id = game['home_team_id']
        away_team_id = game['away_team_id']
        home_team = game['home_team']
        away_team = game['away_team']

        print(f"Processing teams: {home_team} vs {away_team}")

        # Fetch player stats for both teams
        for team_id, team_name in [(home_team_id, home_team), (away_team_id, away_team)]:
            print(f"Processing team: {team_name}")
            try:
                team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                if not team_roster.empty:
                    for _, player in team_roster.iterrows():
                        try:
                            player_id = player['PLAYER_ID']
                            player_name = player['PLAYER']
                            player_position = player['POSITION']  # Fetch player's position
                            print(f"Processing player: {player_name} (ID: {player_id})")

                            game_logs = fetch_player_game_logs(player_id)

                            if game_logs.empty:
                                continue

                            ppg_values = game_logs['PTS']
                            rpg_values = game_logs['REB']
                            apg_values = game_logs['AST']

                            mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(ppg_values)
                            mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(rpg_values)
                            mean_apg, std_dev_apg, cv_apg = calculate_stats(apg_values)

                            all_players_data.append({
                                'Player': player_name,
                                'Position': player_position,
                                'Team': team_name,
                                'PPG': mean_ppg,
                                'PPG SD': std_dev_ppg,
                                'PPG CV': cv_ppg,
                                'RPG': mean_rpg,
                                'RPG SD': std_dev_rpg,
                                'RPG CV': cv_rpg,
                                'APG': mean_apg,
                                'APG SD': std_dev_apg,
                                'APG CV': cv_apg
                            })
                            time.sleep(1)
                        except Exception as e:
                            print(f"Error processing player {player_name}: {e}")
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    return pd.DataFrame(all_players_data)

# Display results as an HTML table in Jupyter Notebook
def display_results(df, stat_type):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)

    if stat_type == 'Points':
        sorted_df = df.sort_values('PPG CV', ascending=True)
        print("\nTop Players by Points CV:")
        display(HTML(sorted_df[['Player', 'Position', 'Team', 'PPG', 'PPG SD', 'PPG CV']].to_html(index=False, justify='center')))
    elif stat_type == 'Rebounds':
        sorted_df = df.sort_values('RPG CV', ascending=True)
        print("\nTop Players by Rebounds CV:")
        display(HTML(sorted_df[['Player', 'Position', 'Team', 'RPG', 'RPG SD', 'RPG CV']].to_html(index=False, justify='center')))
    elif stat_type == 'Assists':
        sorted_df = df.sort_values('APG CV', ascending=True)
        print("\nTop Players by Assists CV:")
        display(HTML(sorted_df[['Player', 'Position', 'Team', 'APG', 'APG SD', 'APG CV']].to_html(index=False, justify='center')))

# Run the analysis and save the output to a spreadsheet
if __name__ == "__main__":
    print("Fetching data for today's games...")
    stats_data = analyze_teams_for_today()

    if not stats_data.empty:
        display_results(stats_data, 'Points')
        display_results(stats_data, 'Rebounds')
        display_results(stats_data, 'Assists')

        # Save the output to an Excel file
        try:
            desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")  # Get desktop path
            file_path = os.path.join(desktop_path, "NBA_Stats_Today.xlsx")

            # Write to Excel
            stats_data.to_excel(file_path, index=False, sheet_name='NBA Stats')

            print(f"Results saved to {file_path}")
        except Exception as e:
            print(f"Error saving to Excel: {e}")
    else:
        print("No games or data available for today.")

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Fetching data for today's games...
No games scheduled for 2024-11-28.
No games scheduled for today.
No games or data available for today.

In [ ]:
!pip install nba_api openpyxl
import requests
import pandas as pd
from datetime import datetime
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, commonteamroster
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display, HTML
import os
import time

# Fetch today's games from NBA Stats API (JSON format)
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        today = datetime.now().strftime('%Y-%m-%d')
        games_today = []

        # Iterate through each month's schedule to find games for today
        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch player game logs for the current season
def fetch_player_game_logs(player_id, season='2024-25'):
    retries = 3
    for attempt in range(retries):
        try:
            print(f"Fetching game logs for player ID: {player_id}")
            game_logs = playergamelog.PlayerGameLog(player_id=player_id, season=season, season_type_all_star='Regular Season').get_data_frames()[0]
            return game_logs
        except Exception as e:
            if attempt < retries - 1:
                print(f"Retrying game logs fetch for player {player_id} (Attempt {attempt + 1})...")
                time.sleep(5)
            else:
                print(f"Failed to fetch game logs for player {player_id}: {e}")
                return pd.DataFrame()

# Calculate per-player stats (Points, Rebounds, Assists)
def calculate_stats(stat_values):
    if len(stat_values) == 0:
        return None, None, None

    stat_values = pd.Series(stat_values).fillna(0)
    mean = round(stat_values.mean(), 2)
    std_dev = round(stat_values.std(), 2)
    cv = round(std_dev / mean, 2) if mean != 0 else None

    return mean, std_dev, cv

# Analyze today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team_id = game['home_team_id']
        away_team_id = game['away_team_id']
        home_team = game['home_team']
        away_team = game['away_team']

        print(f"Processing teams: {home_team} vs {away_team}")

        for team_id, team_name in [(home_team_id, home_team), (away_team_id, away_team)]:
            print(f"Processing team: {team_name}")
            try:
                team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                if not team_roster.empty:
                    for _, player in team_roster.iterrows():
                        try:
                            player_id = player['PLAYER_ID']
                            player_name = player['PLAYER']
                            player_position = player['POSITION']
                            print(f"Processing player: {player_name} (ID: {player_id})")

                            game_logs = fetch_player_game_logs(player_id)

                            if game_logs.empty:
                                continue

                            ppg_values = game_logs['PTS']
                            rpg_values = game_logs['REB']
                            apg_values = game_logs['AST']

                            mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(ppg_values)
                            mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(rpg_values)
                            mean_apg, std_dev_apg, cv_apg = calculate_stats(apg_values)

                            all_players_data.append({
                                'Player': player_name,
                                'Position': player_position,
                                'Team': team_name,
                                'PPG': mean_ppg,
                                'PPG SD': std_dev_ppg,
                                'PPG CV': cv_ppg,
                                'RPG': mean_rpg,
                                'RPG SD': std_dev_rpg,
                                'RPG CV': cv_rpg,
                                'APG': mean_apg,
                                'APG SD': std_dev_apg,
                                'APG CV': cv_apg
                            })
                            time.sleep(1)
                        except Exception as e:
                            print(f"Error processing player {player_name}: {e}")
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    return pd.DataFrame(all_players_data)

# Save results to Excel
def save_to_excel(df):
    try:
        desktop_path = r'C:\Users\MaterialsLab\Desktop\nba_predictions.xlsx'  # Specify the path to your desktop
        file_path = os.path.join(desktop_path, "nba_predictions.xlsx")

        # Create separate DataFrames for each stat type
        points_df = df[['Player', 'Position', 'Team', 'PPG', 'PPG SD', 'PPG CV']].sort_values('PPG CV')
        rebounds_df = df[['Player', 'Position', 'Team', 'RPG', 'RPG SD', 'RPG CV']].sort_values('RPG CV')
        assists_df = df[['Player', 'Position', 'Team', 'APG', 'APG SD', 'APG CV']].sort_values('APG CV')

        # Write to Excel
        with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
            points_df.to_excel(writer, index=False, sheet_name='Points Consistency')
            rebounds_df.to_excel(writer, index=False, sheet_name='Rebounds Consistency')
            assists_df.to_excel(writer, index=False, sheet_name='Assists Consistency')

        print(f"Results saved to C:\\Users\\MaterialsLab\\Desktop\\nba_predictions.xlsx")
    except Exception as e:
        print(f"Error saving to Excel: {e}")

# Run the analysis and save the output
if __name__ == "__main__":
    print("Fetching data for today's games...")
    stats_data = analyze_teams_for_today()

    if not stats_data.empty:
        save_to_excel(stats_data)
    else:
        print("No games or data available for today.")

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Fetching data for today's games...
Processing teams: CHA vs NYK
Processing team: CHA
Processing player: Miles Bridges (ID: 1628970)
Fetching game logs for player ID: 1628970
Processing player: LaMelo Ball (ID: 1630163)
Fetching game logs for player ID: 1630163
Processing player: Grant Williams (ID: 1629684)
Fetching game logs for player ID: 1629684
Processing player: DaQuan Jeffries (ID: 1629610)
Fetching game logs for player ID: 1629610
Processing player: Nick Richards (ID: 1630208)
Fetching game logs for player ID: 1630208
Processing player: Mark Williams (ID: 1631109)
Fetching game logs for player ID: 1631109
Processing player: Nick Smith Jr. (ID: 1641733)
Fetching game logs for player ID: 1641733
Processing player: Josh Green (ID: 1630182)
Fetching game logs for player ID: 1630182
Processing player: Cody Martin (ID: 1628998)
Fetching game logs for player ID: 1628998
Processing player: Moussa Diabate (ID: 1631217)
Fetching game logs for player ID: 1631217
Processing player: Vasilije Micić (ID: 203995)
Fetching game logs for player ID: 203995
Processing player: Tre Mann (ID: 1630544)
Fetching game logs for player ID: 1630544
Processing player: Brandon Miller (ID: 1641706)
Fetching game logs for player ID: 1641706
Processing player: KJ Simpson (ID: 1642354)
Fetching game logs for player ID: 1642354
Processing player: Jared Rhoden (ID: 1631197)
Fetching game logs for player ID: 1631197
Processing player: Seth Curry (ID: 203552)
Fetching game logs for player ID: 203552
Processing player: Tidjane Salaün (ID: 1642275)
Fetching game logs for player ID: 1642275
Processing player: Taj Gibson (ID: 201959)
Fetching game logs for player ID: 201959
Processing team: NYK
Processing player: Boo Buie III (ID: 1642486)
Fetching game logs for player ID: 1642486
Processing player: Jacob Toppin (ID: 1631210)
Fetching game logs for player ID: 1631210
Processing player: Cameron Payne (ID: 1626166)
Fetching game logs for player ID: 1626166
Processing player: Miles McBride (ID: 1630540)
Fetching game logs for player ID: 1630540
Processing player: Josh Hart (ID: 1628404)
Fetching game logs for player ID: 1628404
Processing player: Pacôme Dadiet (ID: 1642359)
Fetching game logs for player ID: 1642359
Processing player: Precious Achiuwa (ID: 1630173)
Fetching game logs for player ID: 1630173
Processing player: OG Anunoby (ID: 1628384)
Fetching game logs for player ID: 1628384
Processing player: Kevin McCullar Jr. (ID: 1641755)
Fetching game logs for player ID: 1641755
Processing player: Jalen Brunson (ID: 1628973)
Fetching game logs for player ID: 1628973
Processing player: Tyler Kolek (ID: 1642278)
Fetching game logs for player ID: 1642278
Processing player: Jericho Sims (ID: 1630579)
Fetching game logs for player ID: 1630579
Processing player: Mitchell Robinson (ID: 1629011)
Fetching game logs for player ID: 1629011
Processing player: Mikal Bridges (ID: 1628969)
Fetching game logs for player ID: 1628969
Processing player: Karl-Anthony Towns (ID: 1626157)
Fetching game logs for player ID: 1626157
Processing player: Matt Ryan (ID: 1630346)
Fetching game logs for player ID: 1630346
Processing player: Ariel Hukporti (ID: 1630574)
Fetching game logs for player ID: 1630574
Processing teams: ATL vs CLE
Processing team: ATL
Processing player: Jalen Johnson (ID: 1630552)
Fetching game logs for player ID: 1630552
Processing player: Keaton Wallace (ID: 1630811)
Fetching game logs for player ID: 1630811
Processing player: Seth Lundy (ID: 1641754)
Fetching game logs for player ID: 1641754
Processing player: Kobe Bufkin (ID: 1641723)
Fetching game logs for player ID: 1641723
Processing player: Dyson Daniels (ID: 1630700)
Fetching game logs for player ID: 1630700
Processing player: David Roddy (ID: 1631223)
Fetching game logs for player ID: 1631223
Processing player: Zaccharie Risacher (ID: 1642258)
Fetching game logs for player ID: 1642258
Processing player: Trae Young (ID: 1629027)
Fetching game logs for player ID: 1629027
Processing player: De'Andre Hunter (ID: 1629631)
Fetching game logs for player ID: 1629631
Processing player: Bogdan Bogdanović (ID: 203992)
Fetching game logs for player ID: 203992
Processing player: Clint Capela (ID: 203991)
Fetching game logs for player ID: 203991
Processing player: Onyeka Okongwu (ID: 1630168)
Fetching game logs for player ID: 1630168
Processing player: Mouhamed Gueye (ID: 1631243)
Fetching game logs for player ID: 1631243
Processing player: Larry Nance Jr. (ID: 1626204)
Fetching game logs for player ID: 1626204
Processing player: Garrison Mathews (ID: 1629726)
Fetching game logs for player ID: 1629726
Processing player: Dominick Barlow (ID: 1631230)
Fetching game logs for player ID: 1631230
Processing player: Vít Krejčí (ID: 1630249)
Fetching game logs for player ID: 1630249
Processing player: Cody Zeller (ID: 203469)
Fetching game logs for player ID: 203469
Processing team: CLE
Processing player: Max Strus (ID: 1629622)
Fetching game logs for player ID: 1629622
Processing player: Ty Jerome (ID: 1629660)
Fetching game logs for player ID: 1629660
Processing player: Caris LeVert (ID: 1627747)
Fetching game logs for player ID: 1627747
Processing player: Evan Mobley (ID: 1630596)
Fetching game logs for player ID: 1630596
Processing player: Sam Merrill (ID: 1630241)
Fetching game logs for player ID: 1630241
Processing player: Craig Porter Jr. (ID: 1641854)
Fetching game logs for player ID: 1641854
Processing player: Darius Garland (ID: 1629636)
Fetching game logs for player ID: 1629636
Processing player: Tristan Thompson (ID: 202684)
Fetching game logs for player ID: 202684
Processing player: JT Thor (ID: 1630550)
Fetching game logs for player ID: 1630550
Processing player: Georges Niang (ID: 1627777)
Fetching game logs for player ID: 1627777
Processing player: Emoni Bates (ID: 1641734)
Fetching game logs for player ID: 1641734
Processing player: Jaylon Tyson (ID: 1642281)
Fetching game logs for player ID: 1642281
Processing player: Jarrett Allen (ID: 1628386)
Fetching game logs for player ID: 1628386
Processing player: Dean Wade (ID: 1629731)
Fetching game logs for player ID: 1629731
Processing player: Luke Travers (ID: 1631247)
Fetching game logs for player ID: 1631247
Processing player: Isaac Okoro (ID: 1630171)
Fetching game logs for player ID: 1630171
Processing player: Donovan Mitchell (ID: 1628378)
Fetching game logs for player ID: 1628378
Processing teams: MEM vs NOP
Processing team: MEM
Processing player: Jaylen Wells (ID: 1642377)
Fetching game logs for player ID: 1642377
Processing player: Scotty Pippen Jr. (ID: 1630590)
Fetching game logs for player ID: 1630590
Processing player: Jake LaRavia (ID: 1631222)
Fetching game logs for player ID: 1631222
Processing player: Vince Williams Jr. (ID: 1631246)
Fetching game logs for player ID: 1631246
Processing player: Santi Aldama (ID: 1630583)
Fetching game logs for player ID: 1630583
Processing player: Colin Castleton (ID: 1630658)
Fetching game logs for player ID: 1630658
Processing player: Luke Kennard (ID: 1628379)
Fetching game logs for player ID: 1628379
Processing player: Ja Morant (ID: 1629630)
Fetching game logs for player ID: 1629630
Processing player: Jaren Jackson Jr. (ID: 1628991)
Fetching game logs for player ID: 1628991
Processing player: Zach Edey (ID: 1641744)
Fetching game logs for player ID: 1641744
Processing player: Brandon Clarke (ID: 1629634)
Fetching game logs for player ID: 1629634
Processing player: Yuki Kawamura (ID: 1642530)
Fetching game logs for player ID: 1642530
Processing player: Desmond Bane (ID: 1630217)
Fetching game logs for player ID: 1630217
Processing player: Cam Spencer (ID: 1642285)
Fetching game logs for player ID: 1642285
Processing player: Jay Huff (ID: 1630643)
Fetching game logs for player ID: 1630643
Processing player: Marcus Smart (ID: 203935)
Fetching game logs for player ID: 203935
Processing player: GG Jackson (ID: 1641713)
Fetching game logs for player ID: 1641713
Processing player: John Konchar (ID: 1629723)
Fetching game logs for player ID: 1629723
Processing team: NOP
Processing player: Zion Williamson (ID: 1629627)
Fetching game logs for player ID: 1629627
Processing player: Herbert Jones (ID: 1630529)
Fetching game logs for player ID: 1630529
Processing player: Elfrid Payton (ID: 203901)
Fetching game logs for player ID: 203901
Processing player: CJ McCollum (ID: 203468)
Fetching game logs for player ID: 203468
Processing player: Javonte Green (ID: 1629750)
Fetching game logs for player ID: 1629750
Processing player: Dejounte Murray (ID: 1627749)
Fetching game logs for player ID: 1627749
Processing player: Jamal Cain (ID: 1631288)
Fetching game logs for player ID: 1631288
Processing player: Daniel Theis (ID: 1628464)
Fetching game logs for player ID: 1628464
Processing player: Brandon Boston Jr. (ID: 1630527)
Fetching game logs for player ID: 1630527
Processing player: Antonio Reeves (ID: 1641810)
Fetching game logs for player ID: 1641810
Processing player: Brandon Ingram (ID: 1627742)
Fetching game logs for player ID: 1627742
Processing player: Jose Alvarado (ID: 1630631)
Fetching game logs for player ID: 1630631
Processing player: Karlo Matkovic (ID: 1631255)
Fetching game logs for player ID: 1631255
Processing player: Yves Missi (ID: 1642274)
Fetching game logs for player ID: 1642274
Processing player: Jordan Hawkins (ID: 1641722)
Fetching game logs for player ID: 1641722
Processing player: Trey Murphy III (ID: 1630530)
Fetching game logs for player ID: 1630530
Processing player: Jeremiah Robinson-Earl (ID: 1630526)
Fetching game logs for player ID: 1630526
Processing player: Trey Jemison III (ID: 1641998)
Fetching game logs for player ID: 1641998
Processing teams: BKN vs ORL
Processing team: BKN
Processing player: Dariq Whitehead (ID: 1641727)
Fetching game logs for player ID: 1641727
Processing player: Ziaire Williams (ID: 1630533)
Fetching game logs for player ID: 1630533
Processing player: Cameron Johnson (ID: 1629661)
Fetching game logs for player ID: 1629661
Processing player: Shake Milton (ID: 1629003)
Fetching game logs for player ID: 1629003
Processing player: Cui Yongxi (ID: 1642385)
Fetching game logs for player ID: 1642385
Processing player: Trendon Watford (ID: 1630570)
Fetching game logs for player ID: 1630570
Processing player: Ben Simmons (ID: 1627732)
Fetching game logs for player ID: 1627732
Processing player: Tyrese Martin (ID: 1631213)
Fetching game logs for player ID: 1631213
Processing player: Jaylen Martin (ID: 1641798)
Fetching game logs for player ID: 1641798
Processing player: Dennis Schröder (ID: 203471)
Fetching game logs for player ID: 203471
Processing player: Day'Ron Sharpe (ID: 1630549)
Fetching game logs for player ID: 1630549
Processing player: Noah Clowney (ID: 1641730)
Fetching game logs for player ID: 1641730
Processing player: Jalen Wilson (ID: 1630592)
Fetching game logs for player ID: 1630592
Processing player: Cam Thomas (ID: 1630560)
Fetching game logs for player ID: 1630560
Processing player: Dorian Finney-Smith (ID: 1627827)
Fetching game logs for player ID: 1627827
Processing player: Nic Claxton (ID: 1629651)
Fetching game logs for player ID: 1629651
Processing player: Bojan Bogdanović (ID: 202711)
Fetching game logs for player ID: 202711
Processing player: Keon Johnson (ID: 1630553)
Fetching game logs for player ID: 1630553
Processing team: ORL
Processing player: Anthony Black (ID: 1641710)
Fetching game logs for player ID: 1641710
Processing player: Jonathan Isaac (ID: 1628371)
Fetching game logs for player ID: 1628371
Processing player: Caleb Houstan (ID: 1631216)
Fetching game logs for player ID: 1631216
Processing player: Kentavious Caldwell-Pope (ID: 203484)
Fetching game logs for player ID: 203484
Processing player: Jalen Suggs (ID: 1630591)
Fetching game logs for player ID: 1630591
Processing player: Paolo Banchero (ID: 1631094)
Fetching game logs for player ID: 1631094
Processing player: Mac McClung (ID: 1630644)
Fetching game logs for player ID: 1630644
Processing player: Cory Joseph (ID: 202709)
Fetching game logs for player ID: 202709
Processing player: Trevelin Queen (ID: 1630243)
Fetching game logs for player ID: 1630243
Processing player: Jett Howard (ID: 1641724)
Fetching game logs for player ID: 1641724
Processing player: Gary Harris (ID: 203914)
Fetching game logs for player ID: 203914
Processing player: Moritz Wagner (ID: 1629021)
Fetching game logs for player ID: 1629021
Processing player: Franz Wagner (ID: 1630532)
Fetching game logs for player ID: 1630532
Processing player: Tristan da Silva (ID: 1641783)
Fetching game logs for player ID: 1641783
Processing player: Wendell Carter Jr. (ID: 1628976)
Fetching game logs for player ID: 1628976
Processing player: Goga Bitadze (ID: 1629048)
Fetching game logs for player ID: 1629048
Processing player: Cole Anthony (ID: 1630175)
Fetching game logs for player ID: 1630175
Processing teams: MIN vs LAC
Processing team: MIN
Processing player: Terrence Shannon Jr. (ID: 1630545)
Fetching game logs for player ID: 1630545
Processing player: Donte DiVincenzo (ID: 1628978)
Fetching game logs for player ID: 1628978
Processing player: Daishen Nix (ID: 1630227)
Fetching game logs for player ID: 1630227
Processing player: Jaden McDaniels (ID: 1630183)
Fetching game logs for player ID: 1630183
Processing player: Rob Dillingham (ID: 1642265)
Fetching game logs for player ID: 1642265
Processing player: Anthony Edwards (ID: 1630162)
Fetching game logs for player ID: 1630162
Processing player: Joe Ingles (ID: 204060)
Fetching game logs for player ID: 204060
Processing player: Josh Minott (ID: 1631169)
Fetching game logs for player ID: 1631169
Processing player: Nickeil Alexander-Walker (ID: 1629638)
Fetching game logs for player ID: 1629638
Processing player: Mike Conley (ID: 201144)
Fetching game logs for player ID: 201144
Processing player: Naz Reid (ID: 1629675)
Fetching game logs for player ID: 1629675
Processing player: Jesse Edwards (ID: 1642399)
Fetching game logs for player ID: 1642399
Processing player: Jaylen Clark (ID: 1641740)
Fetching game logs for player ID: 1641740
Processing player: Rudy Gobert (ID: 203497)
Fetching game logs for player ID: 203497
Processing player: Julius Randle (ID: 203944)
Fetching game logs for player ID: 203944
Processing player: Leonard Miller (ID: 1631159)
Fetching game logs for player ID: 1631159
Processing player: PJ Dozier (ID: 1628408)
Fetching game logs for player ID: 1628408
Processing player: Luka Garza (ID: 1630568)
Fetching game logs for player ID: 1630568
Processing team: LAC
Processing player: James Harden (ID: 201935)
Fetching game logs for player ID: 201935
Processing player: Kawhi Leonard (ID: 202695)
Fetching game logs for player ID: 202695
Processing player: Mo Bamba (ID: 1628964)
Fetching game logs for player ID: 1628964
Processing player: Bones Hyland (ID: 1630538)
Fetching game logs for player ID: 1630538
Processing player: Amir Coffey (ID: 1629599)
Fetching game logs for player ID: 1629599
Processing player: Kris Dunn (ID: 1627739)
Fetching game logs for player ID: 1627739
Processing player: Trentyn Flowers (ID: 1642280)
Fetching game logs for player ID: 1642280
Processing player: Jordan Miller (ID: 1641757)
Fetching game logs for player ID: 1641757
Processing player: Cam Christie (ID: 1642353)
Fetching game logs for player ID: 1642353
Processing player: Terance Mann (ID: 1629611)
Fetching game logs for player ID: 1629611
Processing player: P.J. Tucker (ID: 200782)
Fetching game logs for player ID: 200782
Processing player: Kobe Brown (ID: 1641738)
Fetching game logs for player ID: 1641738
Processing player: Kai Jones (ID: 1630539)
Fetching game logs for player ID: 1630539
Processing player: Norman Powell (ID: 1626181)
Fetching game logs for player ID: 1626181
Processing player: Nicolas Batum (ID: 201587)
Fetching game logs for player ID: 201587
Processing player: Ivica Zubac (ID: 1627826)
Fetching game logs for player ID: 1627826
Processing player: Derrick Jones Jr. (ID: 1627884)
Fetching game logs for player ID: 1627884
Processing player: Kevin Porter Jr. (ID: 1629645)
Fetching game logs for player ID: 1629645
Processing teams: IND vs DET
Processing team: IND
Processing player: Tyrese Haliburton (ID: 1630169)
Fetching game logs for player ID: 1630169
Processing player: Bennedict Mathurin (ID: 1631097)
Fetching game logs for player ID: 1631097
Processing player: Obi Toppin (ID: 1630167)
Fetching game logs for player ID: 1630167
Processing player: Andrew Nembhard (ID: 1629614)
Fetching game logs for player ID: 1629614
Processing player: Moses Brown (ID: 1629650)
Fetching game logs for player ID: 1629650
Processing player: Tristen Newton (ID: 1641803)
Fetching game logs for player ID: 1641803
Processing player: Jarace Walker (ID: 1641716)
Fetching game logs for player ID: 1641716
Processing player: Enrique Freeman (ID: 1642402)
Fetching game logs for player ID: 1642402
Processing player: T.J. McConnell (ID: 204456)
Fetching game logs for player ID: 204456
Processing player: Johnny Furphy (ID: 1642277)
Fetching game logs for player ID: 1642277
Processing player: James Wiseman (ID: 1630164)
Fetching game logs for player ID: 1630164
Processing player: James Johnson (ID: 201949)
Fetching game logs for player ID: 201949
Processing player: Isaiah Jackson (ID: 1630543)
Fetching game logs for player ID: 1630543
Processing player: Aaron Nesmith (ID: 1630174)
Fetching game logs for player ID: 1630174
Processing player: Ben Sheppard (ID: 1641767)
Fetching game logs for player ID: 1641767
Processing player: Quenton Jackson (ID: 1631245)
Fetching game logs for player ID: 1631245
Processing player: Myles Turner (ID: 1626167)
Fetching game logs for player ID: 1626167
Processing player: Pascal Siakam (ID: 1627783)
Fetching game logs for player ID: 1627783
Processing team: DET
Processing player: Jalen Duren (ID: 1631105)
Fetching game logs for player ID: 1631105
Processing player: Ronald Holland II (ID: 1641842)
Fetching game logs for player ID: 1641842
Processing player: Cade Cunningham (ID: 1630595)
Fetching game logs for player ID: 1630595
Processing player: Malik Beasley (ID: 1627736)
Fetching game logs for player ID: 1627736
Processing player: Paul Reed (ID: 1630194)
Fetching game logs for player ID: 1630194
Processing player: Tim Hardaway Jr. (ID: 203501)
Fetching game logs for player ID: 203501
Processing player: Ausar Thompson (ID: 1641709)
Fetching game logs for player ID: 1641709
Processing player: Tobias Harris (ID: 202699)
Fetching game logs for player ID: 202699
Processing player: Cole Swider (ID: 1631306)
Fetching game logs for player ID: 1631306
Processing player: Wendell Moore Jr. (ID: 1631111)
Fetching game logs for player ID: 1631111
Processing player: Simone Fontecchio (ID: 1631323)
Fetching game logs for player ID: 1631323
Processing player: Jaden Ivey (ID: 1631093)
Fetching game logs for player ID: 1631093
Processing player: Daniss Jenkins (ID: 1642450)

In [ ]:
import requests
from datetime import datetime

# Fetch today's games from NBA Stats API (JSON format)
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses
        data = response.json()

        today = datetime.now().strftime('%Y-%m-%d')
        games_today = []

        # Iterate through each month's schedule to find games for today
        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],  # Home team abbreviation
                        'away_team': game['v']['ta'],  # Away team abbreviation
                        'home_team_id': game['h']['tid'],  # Home team ID
                        'away_team_id': game['v']['tid'],  # Away team ID
                        'game_id': game['gid']  # Game ID
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Test the schedule fetching function
games = fetch_schedule()
if games:
    print(f"Games scheduled for today ({datetime.now().strftime('%Y-%m-%d')}):")
    for game in games:
        print(f"{game['away_team']} vs {game['home_team']} (Game ID: {game['game_id']})")
else:
    print("No games found or an error occurred.")

Games scheduled for today (2024-11-29):
NYK vs CHA (Game ID: 0022400040)
CLE vs ATL (Game ID: 0022400041)
NOP vs MEM (Game ID: 0022400042)
ORL vs BKN (Game ID: 0022400043)
LAC vs MIN (Game ID: 0022400044)
DET vs IND (Game ID: 0022400045)
TOR vs MIA (Game ID: 0022400046)
BOS vs CHI (Game ID: 0022400047)
OKC vs LAL (Game ID: 0022400048)
SAC vs POR (Game ID: 0022400049)

In [ ]:
# Install the necessary package for NBA data
!pip install nba_api

import json
from nba_api.stats.endpoints import teamestimatedmetrics
import pandas as pd

# Fetch the data
team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(season="2024-25", season_type="Regular Season", league_id="00")

# Parse the response to a pandas DataFrame
data = team_metrics.get_data_frames()[0]  # Extract the first DataFrame (this is where our data resides)

# Filter the required columns
columns_of_interest = ["TEAM_NAME", "E_OFF_RATING", "E_DEF_RATING", "E_PACE"]

# Create a new DataFrame with only the columns we care about
filtered_data = data[columns_of_interest]

# Display the filtered data
print(filtered_data)

In [ ]:
!pip install nba_api pytz

import json
import pandas as pd
from nba_api.stats.endpoints import teamestimatedmetrics
from nba_api.stats.endpoints import playergamelog, commonteamroster
from datetime import datetime
import requests
import time
import pytz

# Define EST timezone
EST = pytz.timezone('US/Eastern')

# Team abbreviation to full team name mapping
team_abbr_to_full = {
    'CHA': 'Charlotte Hornets', 'MIA': 'Miami Heat', 'CLE': 'Cleveland Cavaliers', 'ATL': 'Atlanta Hawks',
    'IND': 'Indiana Pacers', 'POR': 'Portland Trail Blazers', 'ORL': 'Orlando Magic', 'CHI': 'Chicago Bulls',
    'PHI': 'Philadelphia 76ers', 'HOU': 'Houston Rockets', 'WAS': 'Washington Wizards', 'LAC': 'Los Angeles Clippers',
    'DAL': 'Dallas Mavericks', 'NYK': 'New York Knicks', 'MEM': 'Memphis Grizzlies', 'DET': 'Detroit Pistons',
    'MIN': 'Minnesota Timberwolves', 'SAC': 'Sacramento Kings', 'NOP': 'New Orleans Pelicans', 'TOR': 'Toronto Raptors',
    'SAS': 'San Antonio Spurs', 'LAL': 'Los Angeles Lakers', 'PHX': 'Phoenix Suns', 'BKN': 'Brooklyn Nets',
    'UTA': 'Utah Jazz', 'DEN': 'Denver Nuggets', 'GSW': 'Golden State Warriors', 'OKC': 'Oklahoma City Thunder'
}

# Fetch the data for team metrics
def fetch_team_metrics():
    try:
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(season="2024-25", season_type="Regular Season", league_id="00")
        data = team_metrics.get_data_frames()[0]  # Extract the first DataFrame (this is where our data resides)
        columns_of_interest = ["TEAM_NAME", "E_OFF_RATING", "E_DEF_RATING", "E_PACE"]
        filtered_data = data[columns_of_interest]
        return filtered_data
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return pd.DataFrame()

# Fetch today's NBA games from NBA Stats API
def fetch_schedule():
    try:
        # Get the current date in EST
        now = datetime.now(EST)
        today = now.strftime('%Y-%m-%d')  # Format the date as YYYY-MM-DD
        print(f"Fetching schedule for {today} (EST)")

        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses
        data = response.json()

        games_today = []

        # Iterate through each month's schedule to find games for today
        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],  # Home team abbreviation
                        'away_team': game['v']['ta'],  # Away team abbreviation
                        'home_team_id': game['h']['tid'],  # Home team ID
                        'away_team_id': game['v']['tid']   # Away team ID
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch player game logs for the current season
def fetch_player_game_logs(player_id, season='2024-25'):
    retries = 3
    for attempt in range(retries):
        try:
            print(f"Fetching game logs for player ID: {player_id}")
            game_logs = playergamelog.PlayerGameLog(player_id=player_id, season=season, season_type_all_star='Regular Season').get_data_frames()[0]
            return game_logs
        except Exception as e:
            if attempt < retries - 1:
                print(f"Retrying game logs fetch for player {player_id} (Attempt {attempt + 1})...")
                time.sleep(5)
            else:
                print(f"Failed to fetch game logs for player {player_id}: {e}")
                return pd.DataFrame()

# Calculate per-player stats (Points, Rebounds, Assists)
def calculate_stats(stat_values):
    if len(stat_values) == 0:
        return None, None, None

    stat_values = pd.Series(stat_values).fillna(0)  # Fill NaN values with zero
    mean = round(stat_values.mean(), 2)
    std_dev = round(stat_values.std(), 2)
    cv = round(std_dev / mean, 2) if mean != 0 else None

    return mean, std_dev, cv

# Analyze today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    team_metrics_data = fetch_team_metrics()
    if team_metrics_data.empty:
        print("No team metrics available.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team_id = game['home_team_id']
        away_team_id = game['away_team_id']
        home_team_abbr = game['home_team']
        away_team_abbr = game['away_team']

        # Map the abbreviations to full team names
        home_team = team_abbr_to_full.get(home_team_abbr, home_team_abbr)
        away_team = team_abbr_to_full.get(away_team_abbr, away_team_abbr)

        # Fetch team metrics for both home and away teams
        home_team_metrics = team_metrics_data[team_metrics_data['TEAM_NAME'] == home_team]
        away_team_metrics = team_metrics_data[team_metrics_data['TEAM_NAME'] == away_team]

        # Ensure there is data for the home and away teams
        if home_team_metrics.empty or away_team_metrics.empty:
            print(f"Missing team data for {home_team} or {away_team}")
            continue

        home_team_metrics = home_team_metrics.iloc[0]
        away_team_metrics = away_team_metrics.iloc[0]

        home_team_offrtg = home_team_metrics['E_OFF_RATING']
        away_team_offrtg = away_team_metrics['E_OFF_RATING']
        home_team_defrtg = home_team_metrics['E_DEF_RATING']
        away_team_defrtg = away_team_metrics['E_DEF_RATING']
        home_team_pace = home_team_metrics['E_PACE']
        away_team_pace = away_team_metrics['E_PACE']

        print(f"Processing teams: {home_team} vs {away_team}")

        # Fetch player stats for both teams
        for team_id, team_name, team_offrtg, team_defrtg, team_pace in [(home_team_id, home_team, home_team_offrtg, home_team_defrtg, home_team_pace), (away_team_id, away_team, away_team_offrtg, away_team_defrtg, away_team_pace)]:
            print(f"Processing team: {team_name}")
            try:
                team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                if team_roster.empty:
                    print(f"No players found for team {team_name}")
                    continue

                for _, player in team_roster.iterrows():
                    try:
                        player_id = player['PLAYER_ID']
                        player_name = player['PLAYER']
                        player_pos = player['POSITION']
                        print(f"Processing player: {player_name} (ID: {player_id})")

                        game_logs = fetch_player_game_logs(player_id)

                        if game_logs.empty:
                            print(f"No game logs available for {player_name}")
                            continue

                        ppg_values = game_logs['PTS']
                        rpg_values = game_logs['REB']
                        apg_values = game_logs['AST']

                        mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(ppg_values)
                        mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(rpg_values)
                        mean_apg, std_dev_apg, cv_apg = calculate_stats(apg_values)

                        all_players_data.append({
                            'player_name': player_name,
                            'position': player_pos,
                            'team': team_name,
                            'offensive_rating': team_offrtg,
                            'defensive_rating': team_defrtg,
                            'pace': team_pace,
                            'avg_points': mean_ppg,
                            'std_dev_points': std_dev_ppg,
                            'cv_points': cv_ppg,
                            'avg_rebounds': mean_rpg,
                            'std_dev_rebounds': std_dev_rpg,
                            'cv_rebounds': cv_rpg,
                            'avg_assists': mean_apg,
                            'std_dev_assists': std_dev_apg,
                            'cv_assists': cv_apg
                        })
                    except Exception as e:
                        print(f"Error processing player {player_name}: {e}")
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    return pd.DataFrame(all_players_data)

# Display the results
def display_results(players_df, stat_type):
    if players_df.empty:
        print(f"No data available for {stat_type}.")
        return

    print(f"\n{stat_type} stats:")
    stat_columns = [col for col in players_df.columns if stat_type.lower() in col.lower()]
    display(players_df[['player_name', 'team'] + stat_columns].sort_values(by=f'avg_{stat_type.lower()}'))

# Main execution flow
if __name__ == "__main__":
    players_df = analyze_teams_for_today()
    if not players_df.empty:
        display_results(players_df, stat_type='Points')
        display_results(players_df, stat_type='Rebounds')
        display_results(players_df, stat_type='Assists')

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (2024.2)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Fetching schedule for 2024-12-02 (EST)
Processing teams: Atlanta Hawks vs New Orleans Pelicans
Processing team: Atlanta Hawks
Processing player: Jalen Johnson (ID: 1630552)
Fetching game logs for player ID: 1630552
Processing player: Keaton Wallace (ID: 1630811)
Fetching game logs for player ID: 1630811
Processing player: Seth Lundy (ID: 1641754)
Fetching game logs for player ID: 1641754
No game logs available for Seth Lundy
Processing player: Kobe Bufkin (ID: 1641723)
Fetching game logs for player ID: 1641723
Processing player: Dyson Daniels (ID: 1630700)
Fetching game logs for player ID: 1630700
Processing player: David Roddy (ID: 1631223)
Fetching game logs for player ID: 1631223
Processing player: Zaccharie Risacher (ID: 1642258)
Fetching game logs for player ID: 1642258
Processing player: Trae Young (ID: 1629027)
Fetching game logs for player ID: 1629027
Processing player: De'Andre Hunter (ID: 1629631)
Fetching game logs for player ID: 1629631
Processing player: Bogdan Bogdanović (ID: 203992)
Fetching game logs for player ID: 203992
Processing player: Clint Capela (ID: 203991)
Fetching game logs for player ID: 203991
Processing player: Onyeka Okongwu (ID: 1630168)
Fetching game logs for player ID: 1630168
Processing player: Mouhamed Gueye (ID: 1631243)
Fetching game logs for player ID: 1631243
Processing player: Larry Nance Jr. (ID: 1626204)
Fetching game logs for player ID: 1626204
Processing player: Garrison Mathews (ID: 1629726)
Fetching game logs for player ID: 1629726
Processing player: Dominick Barlow (ID: 1631230)
Fetching game logs for player ID: 1631230
Processing player: Vít Krejčí (ID: 1630249)
Fetching game logs for player ID: 1630249
Processing player: Cody Zeller (ID: 203469)
Fetching game logs for player ID: 203469
No game logs available for Cody Zeller
Processing team: New Orleans Pelicans
Processing player: Zion Williamson (ID: 1629627)
Fetching game logs for player ID: 1629627
Processing player: Herbert Jones (ID: 1630529)
Fetching game logs for player ID: 1630529
Processing player: Elfrid Payton (ID: 203901)
Fetching game logs for player ID: 203901
Processing player: CJ McCollum (ID: 203468)
Fetching game logs for player ID: 203468
Processing player: Javonte Green (ID: 1629750)
Fetching game logs for player ID: 1629750
Processing player: Dejounte Murray (ID: 1627749)
Fetching game logs for player ID: 1627749
Processing player: Jamal Cain (ID: 1631288)
Fetching game logs for player ID: 1631288
Processing player: Daniel Theis (ID: 1628464)
Fetching game logs for player ID: 1628464
Processing player: Brandon Boston Jr. (ID: 1630527)
Fetching game logs for player ID: 1630527
Processing player: Antonio Reeves (ID: 1641810)
Fetching game logs for player ID: 1641810
Retrying game logs fetch for player 1641810 (Attempt 1)...
Fetching game logs for player ID: 1641810
Processing player: Brandon Ingram (ID: 1627742)
Fetching game logs for player ID: 1627742
Processing player: Jose Alvarado (ID: 1630631)
Fetching game logs for player ID: 1630631
Processing player: Karlo Matković (ID: 1631255)
Fetching game logs for player ID: 1631255
Processing player: Yves Missi (ID: 1642274)
Fetching game logs for player ID: 1642274
Processing player: Jordan Hawkins (ID: 1641722)
Fetching game logs for player ID: 1641722
Processing player: Trey Murphy III (ID: 1630530)
Fetching game logs for player ID: 1630530
Processing player: Jeremiah Robinson-Earl (ID: 1630526)
Fetching game logs for player ID: 1630526
Processing player: Trey Jemison III (ID: 1641998)
Fetching game logs for player ID: 1641998
Missing team data for BOS or Miami Heat
Processing teams: Chicago Bulls vs Brooklyn Nets
Processing team: Chicago Bulls
Processing player: Coby White (ID: 1629632)
Fetching game logs for player ID: 1629632
Processing player: DJ Steward (ID: 1630569)
Fetching game logs for player ID: 1630569
No game logs available for DJ Steward
Processing player: Lonzo Ball (ID: 1628366)
Fetching game logs for player ID: 1628366
Processing player: Josh Giddey (ID: 1630581)
Fetching game logs for player ID: 1630581
Processing player: Jevon Carter (ID: 1628975)
Fetching game logs for player ID: 1628975
Processing player: Jalen Smith (ID: 1630188)
Fetching game logs for player ID: 1630188
Processing player: Zach LaVine (ID: 203897)
Fetching game logs for player ID: 203897
Processing player: Nikola Vučević (ID: 202696)
Fetching game logs for player ID: 202696
Processing player: Ayo Dosunmu (ID: 1630245)
Fetching game logs for player ID: 1630245
Processing player: Torrey Craig (ID: 1628470)
Fetching game logs for player ID: 1628470
Processing player: Matas Buzelis (ID: 1641824)
Fetching game logs for player ID: 1641824
Processing player: Julian Phillips (ID: 1641763)
Fetching game logs for player ID: 1641763
Processing player: Adama Sanogo (ID: 1641766)
Fetching game logs for player ID: 1641766
Processing player: Talen Horton-Tucker (ID: 1629659)
Fetching game logs for player ID: 1629659
Processing player: Dalen Terry (ID: 1631207)
Fetching game logs for player ID: 1631207
Processing player: Chris Duarte (ID: 1630537)
Fetching game logs for player ID: 1630537
Retrying game logs fetch for player 1630537 (Attempt 1)...
Fetching game logs for player ID: 1630537
Processing player: E.J. Liddell (ID: 1630604)
Fetching game logs for player ID: 1630604
Retrying game logs fetch for player 1630604 (Attempt 1)...
Fetching game logs for player ID: 1630604
Retrying game logs fetch for player 1630604 (Attempt 2)...
Fetching game logs for player ID: 1630604
Processing player: Patrick Williams (ID: 1630172)
Fetching game logs for player ID: 1630172
Retrying game logs fetch for player 1630172 (Attempt 1)...
Fetching game logs for player ID: 1630172
Retrying game logs fetch for player 1630172 (Attempt 2)...
Fetching game logs for player ID: 1630172
Processing team: Brooklyn Nets
Processing player: Dariq Whitehead (ID: 1641727)
Fetching game logs for player ID: 1641727
Processing player: Ziaire Williams (ID: 1630533)
Fetching game logs for player ID: 1630533
Retrying game logs fetch for player 1630533 (Attempt 1)...
Fetching game logs for player ID: 1630533
Retrying game logs fetch for player 1630533 (Attempt 2)...
Fetching game logs for player ID: 1630533
Processing player: Cameron Johnson (ID: 1629661)
Fetching game logs for player ID: 1629661
Retrying game logs fetch for player 1629661 (Attempt 1)...
Fetching game logs for player ID: 1629661
Processing player: Shake Milton (ID: 1629003)
Fetching game logs for player ID: 1629003
Retrying game logs fetch for player 1629003 (Attempt 1)...
Fetching game logs for player ID: 1629003
Processing player: Cui Yongxi (ID: 1642385)
Fetching game logs for player ID: 1642385
Processing player: Trendon Watford (ID: 1630570)
Fetching game logs for player ID: 1630570
Processing player: Ben Simmons (ID: 1627732)
Fetching game logs for player ID: 1627732
Processing player: Tyrese Martin (ID: 1631213)
Fetching game logs for player ID: 1631213
Retrying game logs fetch for player 1631213 (Attempt 1)...
Fetching game logs for player ID: 1631213
Processing player: Jaylen Martin (ID: 1641798)
Fetching game logs for player ID: 1641798
Retrying game logs fetch for player 1641798 (Attempt 1)...
Fetching game logs for player ID: 1641798
Processing player: Dennis Schröder (ID: 203471)
Fetching game logs for player ID: 203471
Processing player: Day'Ron Sharpe (ID: 1630549)
Fetching game logs for player ID: 1630549
Retrying game logs fetch for player 1630549 (Attempt 1)...
Fetching game logs for player ID: 1630549
No game logs available for Day'Ron Sharpe
Processing player: Noah Clowney (ID: 1641730)
Fetching game logs for player ID: 1641730
Retrying game logs fetch for player 1641730 (Attempt 1)...
Fetching game logs for player ID: 1641730
Processing player: Jalen Wilson (ID: 1630592)
Fetching game logs for player ID: 1630592
Processing player: Cam Thomas (ID: 1630560)
Fetching game logs for player ID: 1630560
Processing player: Dorian Finney-Smith (ID: 1627827)
Fetching game logs for player ID: 1627827
Processing player: Nic Claxton (ID: 1629651)
Fetching game logs for player ID: 1629651
Processing player: Bojan Bogdanović (ID: 202711)
Fetching game logs for player ID: 202711
No game logs available for Bojan Bogdanović
Processing player: Keon Johnson (ID: 1630553)
Fetching game logs for player ID: 1630553
Processing teams: Minnesota Timberwolves vs Los Angeles Lakers
Processing team: Minnesota Timberwolves
Processing player: Terrence Shannon Jr. (ID: 1630545)
Fetching game logs for player ID: 1630545
Processing player: Donte DiVincenzo (ID: 1628978)
Fetching game logs for player ID: 1628978
Processing player: Daishen Nix (ID: 1630227)
Fetching game logs for player ID: 1630227
No game logs available for Daishen Nix
Processing player: Jaden McDaniels (ID: 1630183)
Fetching game logs for player ID: 1630183
Processing player: Rob Dillingham (ID: 1642265)
Fetching game logs for player ID: 1642265
Processing player: Anthony Edwards (ID: 1630162)
Fetching game logs for player ID: 1630162
Processing player: Joe Ingles (ID: 204060)
Fetching game logs for player ID: 204060
Processing player: Josh Minott (ID: 1631169)
Fetching game logs for player ID: 1631169
Processing player: Nickeil Alexander-Walker (ID: 1629638)
Fetching game logs for player ID: 1629638
Processing player: Mike Conley (ID: 201144)
Fetching game logs for player ID: 201144
Processing player: Naz Reid (ID: 1629675)
Fetching game logs for player ID: 1629675
Processing player: Jesse Edwards (ID: 1642399)
Fetching game logs for player ID: 1642399
No game logs available for Jesse Edwards
Processing player: Jaylen Clark (ID: 1641740)
Fetching game logs for player ID: 1641740
No game logs available for Jaylen Clark
Processing player: Rudy Gobert (ID: 203497)
Fetching game logs for player ID: 203497
Processing player: Julius Randle (ID: 203944)
Fetching game logs for player ID: 203944
Processing player: Leonard Miller (ID: 1631159)
Fetching game logs for player ID: 1631159
No game logs available for Leonard Miller
Processing player: PJ Dozier (ID: 1628408)
Fetching game logs for player ID: 1628408
Processing player: Luka Garza (ID: 1630568)
Fetching game logs for player ID: 1630568
Processing team: Los Angeles Lakers
Processing player: Jalen Hood-Schifino (ID: 1641720)
Fetching game logs for player ID: 1641720
Processing player: D'Angelo Russell (ID: 1626156)
Fetching game logs for player ID: 1626156
Processing player: Jarred Vanderbilt (ID: 1629020)
Fetching game logs for player ID: 1629020
No game logs available for Jarred Vanderbilt
Processing player: Anthony Davis (ID: 203076)
Fetching game logs for player ID: 203076
Processing player: Dalton Knecht (ID: 1642261)
Fetching game logs for player ID: 1642261
Processing player: Cam Reddish (ID: 1629629)
Fetching game logs for player ID: 1629629
Processing player: Gabe Vincent (ID: 1629216)
Fetching game logs for player ID: 1629216
Processing player: Bronny James (ID: 1642355)
Fetching game logs for player ID: 1642355
Processing player: Christian Koloko (ID: 1631132)
Fetching game logs for player ID: 1631132
Processing player: Jaxson Hayes (ID: 1629637)
Fetching game logs for player ID: 1629637
Processing player: Max Christie (ID: 1631108)
Fetching game logs for player ID: 1631108
Processing player: Austin Reaves (ID: 1630559)
Fetching game logs for player ID: 1630559
Processing player: Maxwell Lewis (ID: 1641721)
Fetching game logs for player ID: 1641721
Processing player: LeBron James (ID: 2544)
Fetching game logs for player ID: 2544
Processing player: Rui Hachimura (ID: 1629060)
Fetching game logs for player ID: 1629060
Processing player: Christian Wood (ID: 1626174)
Fetching game logs for player ID: 1626174
No game logs available for Christian Wood
Processing player: Quincy Olivari (ID: 1642439)
Fetching game logs for player ID: 1642439
No game logs available for Quincy Olivari
Processing player: Armel Traoré (ID: 1642422)
Fetching game logs for player ID: 1642422

Points stats:

,player_name,team,avg_points,std_dev_points,cv_points
92,Maxwell Lewis,Los Angeles Lakers,0.00,0.00,NaN
51,Dariq Whitehead,Brooklyn Nets,0.00,0.00,NaN
72,Joe Ingles,Minnesota Timberwolves,0.00,0.00,NaN
55,Cui Yongxi,Brooklyn Nets,0.25,0.50,2.00
95,Armel Traoré,Los Angeles Lakers,0.50,1.00,2.00
...,...,...,...,...,...
16,Zion Williamson,New Orleans Pelicans,22.67,9.71,0.43
26,Brandon Ingram,New Orleans Pelicans,22.88,7.20,0.31
63,Cam Thomas,Brooklyn Nets,24.71,8.57,0.35
71,Anthony Edwards,Minnesota Timberwolves,27.68,5.31,0.19
83,Anthony Davis,Los Angeles Lakers,28.63,8.11,0.28

Rebounds stats:

,player_name,team,avg_rebounds,std_dev_rebounds,cv_rebounds
55,Cui Yongxi,Brooklyn Nets,0.00,0.00,NaN
14,Dominick Barlow,Atlanta Hawks,0.00,0.00,NaN
59,Jaylen Martin,Brooklyn Nets,0.00,0.00,NaN
67,Terrence Shannon Jr.,Minnesota Timberwolves,0.00,0.00,NaN
87,Bronny James,Los Angeles Lakers,0.17,0.41,2.41
...,...,...,...,...,...
9,Clint Capela,Atlanta Hawks,8.81,3.27,0.37
0,Jalen Johnson,Atlanta Hawks,9.90,3.68,0.37
40,Nikola Vučević,Chicago Bulls,9.95,2.54,0.26
77,Rudy Gobert,Minnesota Timberwolves,11.16,3.79,0.34
83,Anthony Davis,Los Angeles Lakers,11.53,3.06,0.27

Assists stats:

,player_name,team,avg_assists,std_dev_assists,cv_assists
95,Armel Traoré,Los Angeles Lakers,0.00,0.00,NaN
51,Dariq Whitehead,Brooklyn Nets,0.00,0.00,NaN
55,Cui Yongxi,Brooklyn Nets,0.00,0.00,NaN
59,Jaylen Martin,Brooklyn Nets,0.00,0.00,NaN
28,Karlo Matković,New Orleans Pelicans,0.00,0.00,NaN
...,...,...,...,...,...
57,Ben Simmons,Brooklyn Nets,6.56,2.61,0.40
36,Josh Giddey,Chicago Bulls,6.67,2.71,0.41
18,Elfrid Payton,New Orleans Pelicans,7.83,6.74,0.86
93,LeBron James,Los Angeles Lakers,9.35,3.60,0.39
6,Trae Young,Atlanta Hawks,12.05,4.16,0.35

In [ ]:
# Install necessary packages
!pip install nba_api requests

import pandas as pd
import numpy as np
from nba_api.stats.endpoints import (
    playergamelog, commonteamroster, teamestimatedmetrics
)
from nba_api.stats.library.parameters import Season, SeasonType
from datetime import datetime
import pytz
import requests
import time

# Map team abbreviations to full names
team_abbr_to_full = {
    "CHA": "Charlotte Hornets",
    "NYK": "New York Knicks",
    "ATL": "Atlanta Hawks",
    "CLE": "Cleveland Cavaliers",
    "MEM": "Memphis Grizzlies",
    "NOP": "New Orleans Pelicans",
    "BKN": "Brooklyn Nets",
    "ORL": "Orlando Magic",
    # Add all team mappings here...
}

# Fetch today's NBA games from NBA Stats API
def fetch_schedule():
    try:
        # Get the current date in EST
        EST = pytz.timezone('US/Eastern')
        now = datetime.now(EST)
        today = now.strftime('%Y-%m-%d')  # Format the date as YYYY-MM-DD
        print(f"Fetching schedule for {today} (EST)")

        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses
        data = response.json()

        games_today = []

        # Iterate through each month's schedule to find games for today
        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],  # Home team abbreviation
                        'away_team': game['v']['ta'],  # Away team abbreviation
                        'home_team_id': game['h']['tid'],  # Home team ID
                        'away_team_id': game['v']['tid']   # Away team ID
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics (Offensive/Defensive stats)
def fetch_team_metrics():
    try:
        print("Fetching team metrics...")
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25",
            season_type="Regular Season",
            league_id="00"
        ).get_data_frames()[0]
        return team_metrics
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return pd.DataFrame()

# Fetch player game logs for the current season
def fetch_player_game_logs(player_id, season="2024-25"):
    retries = 3
    for attempt in range(retries):
        try:
            print(f"Fetching game logs for player ID: {player_id}")
            game_logs = playergamelog.PlayerGameLog(
                player_id=player_id,
                season=season,
                season_type_all_star="Regular Season"
            ).get_data_frames()[0]
            return game_logs
        except Exception as e:
            if attempt < retries - 1:
                print(f"Retrying game logs fetch for player {player_id} (Attempt {attempt + 1})...")
                time.sleep(5)
            else:
                print(f"Failed to fetch game logs for player {player_id}: {e}")
                return pd.DataFrame()

# Calculate per-player stats (Points, Rebounds, Assists)
def calculate_stats(stat_values):
    if len(stat_values) == 0:
        return None, None, None

    stat_values = pd.Series(stat_values).fillna(0)  # Fill NaN values with zero
    mean = round(stat_values.mean(), 2)
    std_dev = round(stat_values.std(), 2)
    cv = round(std_dev / mean, 2) if mean != 0 else None

    return mean, std_dev, cv

# Analyze today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    team_metrics_data = fetch_team_metrics()
    if team_metrics_data.empty:
        print("No team metrics available.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team_id = game['home_team_id']
        away_team_id = game['away_team_id']
        home_team_abbr = game['home_team']
        away_team_abbr = game['away_team']

        # Map the abbreviations to full team names
        home_team = team_abbr_to_full.get(home_team_abbr, home_team_abbr)
        away_team = team_abbr_to_full.get(away_team_abbr, away_team_abbr)

        # Fetch team metrics for both home and away teams
        home_team_metrics = team_metrics_data[team_metrics_data['TEAM_NAME'] == home_team]
        away_team_metrics = team_metrics_data[team_metrics_data['TEAM_NAME'] == away_team]

        # Ensure there is data for the home and away teams
        if home_team_metrics.empty or away_team_metrics.empty:
            print(f"Missing team data for {home_team} or {away_team}")
            continue

        home_team_metrics = home_team_metrics.iloc[0]
        away_team_metrics = away_team_metrics.iloc[0]

        home_team_offrtg = home_team_metrics['E_OFF_RATING']
        away_team_offrtg = away_team_metrics['E_OFF_RATING']
        home_team_defrtg = home_team_metrics['E_DEF_RATING']
        away_team_defrtg = away_team_metrics['E_DEF_RATING']
        home_team_pace = home_team_metrics['E_PACE']
        away_team_pace = away_team_metrics['E_PACE']

        print(f"Processing teams: {home_team} vs {away_team}")

        # Fetch player stats for both teams
        for team_id, team_name, team_offrtg, team_defrtg, team_pace in [(home_team_id, home_team, home_team_offrtg, home_team_defrtg, home_team_pace), (away_team_id, away_team, away_team_offrtg, away_team_defrtg, away_team_pace)]:
            print(f"Processing team: {team_name}")
            try:
                team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                if team_roster.empty:
                    print(f"No players found for team {team_name}")
                    continue

                for _, player in team_roster.iterrows():
                    try:
                        player_id = player['PLAYER_ID']
                        player_name = player['PLAYER']
                        player_pos = player['POSITION']
                        print(f"Processing player: {player_name} (ID: {player_id})")

                        game_logs = fetch_player_game_logs(player_id)

                        if game_logs.empty:
                            print(f"No game logs available for {player_name}")
                            continue

                        ppg_values = game_logs['PTS']
                        rpg_values = game_logs['REB']
                        apg_values = game_logs['AST']

                        mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(ppg_values)
                        mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(rpg_values)
                        mean_apg, std_dev_apg, cv_apg = calculate_stats(apg_values)

                        all_players_data.append({
                            'player_name': player_name,
                            'position': player_pos,
                            'team': team_name,
                            'offensive_rating': team_offrtg,
                            'defensive_rating': team_defrtg,
                            'pace': team_pace,
                            'avg_points': mean_ppg,
                            'std_dev_points': std_dev_ppg,
                            'cv_points': cv_ppg,
                            'avg_rebounds': mean_rpg,
                            'std_dev_rebounds': std_dev_rpg,
                            'cv_rebounds': cv_rpg,
                            'avg_assists': mean_apg,
                            'std_dev_assists': std_dev_apg,
                            'cv_assists': cv_apg
                        })
                    except Exception as e:
                        print(f"Error processing player {player_name}: {e}")
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    return pd.DataFrame(all_players_data)

# Display the results
def display_results(players_df, stat_type):
    if players_df.empty:
        print(f"No data available for {stat_type}.")
        return

    print(f"\n{stat_type} stats:")
    stat_columns = [col for col in players_df.columns if stat_type.lower() in col.lower()]
    display(players_df[['player_name', 'team'] + stat_columns].sort_values(by=f'avg_{stat_type.lower()}'))

# Main execution flow
if __name__ == "__main__":
    players_df = analyze_teams_for_today()
    if not players_df.empty:
        display_results(players_df, stat_type='Points')
        display_results(players_df, stat_type='Rebounds')
        display_results(players_df, stat_type='Assists')

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.32.3)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.8.30)
Fetching schedule for 2024-12-02 (EST)
Fetching team metrics...
Processing teams: Atlanta Hawks vs New Orleans Pelicans
Processing team: Atlanta Hawks
Processing player: Jalen Johnson (ID: 1630552)
Fetching game logs for player ID: 1630552
Processing player: Keaton Wallace (ID: 1630811)
Fetching game logs for player ID: 1630811
Processing player: Seth Lundy (ID: 1641754)
Fetching game logs for player ID: 1641754
No game logs available for Seth Lundy
Processing player: Kobe Bufkin (ID: 1641723)
Fetching game logs for player ID: 1641723
Processing player: Dyson Daniels (ID: 1630700)
Fetching game logs for player ID: 1630700
Processing player: David Roddy (ID: 1631223)
Fetching game logs for player ID: 1631223
Processing player: Zaccharie Risacher (ID: 1642258)
Fetching game logs for player ID: 1642258
Processing player: Trae Young (ID: 1629027)
Fetching game logs for player ID: 1629027
Processing player: De'Andre Hunter (ID: 1629631)
Fetching game logs for player ID: 1629631
Processing player: Bogdan Bogdanović (ID: 203992)
Fetching game logs for player ID: 203992
Processing player: Clint Capela (ID: 203991)
Fetching game logs for player ID: 203991
Processing player: Onyeka Okongwu (ID: 1630168)
Fetching game logs for player ID: 1630168
Processing player: Mouhamed Gueye (ID: 1631243)
Fetching game logs for player ID: 1631243
Processing player: Larry Nance Jr. (ID: 1626204)
Fetching game logs for player ID: 1626204
Processing player: Garrison Mathews (ID: 1629726)
Fetching game logs for player ID: 1629726
Processing player: Dominick Barlow (ID: 1631230)
Fetching game logs for player ID: 1631230
Processing player: Vít Krejčí (ID: 1630249)
Fetching game logs for player ID: 1630249
Processing player: Cody Zeller (ID: 203469)
Fetching game logs for player ID: 203469
No game logs available for Cody Zeller
Processing team: New Orleans Pelicans
Processing player: Zion Williamson (ID: 1629627)
Fetching game logs for player ID: 1629627
Processing player: Herbert Jones (ID: 1630529)
Fetching game logs for player ID: 1630529
Processing player: Elfrid Payton (ID: 203901)
Fetching game logs for player ID: 203901
Processing player: CJ McCollum (ID: 203468)
Fetching game logs for player ID: 203468
Processing player: Javonte Green (ID: 1629750)
Fetching game logs for player ID: 1629750
Processing player: Dejounte Murray (ID: 1627749)
Fetching game logs for player ID: 1627749
Processing player: Jamal Cain (ID: 1631288)
Fetching game logs for player ID: 1631288
Processing player: Daniel Theis (ID: 1628464)
Fetching game logs for player ID: 1628464
Processing player: Brandon Boston Jr. (ID: 1630527)
Fetching game logs for player ID: 1630527
Processing player: Antonio Reeves (ID: 1641810)
Fetching game logs for player ID: 1641810
Processing player: Brandon Ingram (ID: 1627742)
Fetching game logs for player ID: 1627742
Processing player: Jose Alvarado (ID: 1630631)
Fetching game logs for player ID: 1630631
Processing player: Karlo Matković (ID: 1631255)
Fetching game logs for player ID: 1631255
Processing player: Yves Missi (ID: 1642274)
Fetching game logs for player ID: 1642274
Processing player: Jordan Hawkins (ID: 1641722)
Fetching game logs for player ID: 1641722
Processing player: Trey Murphy III (ID: 1630530)
Fetching game logs for player ID: 1630530
Processing player: Jeremiah Robinson-Earl (ID: 1630526)
Fetching game logs for player ID: 1630526
Processing player: Trey Jemison III (ID: 1641998)
Fetching game logs for player ID: 1641998
Missing team data for BOS or MIA
Missing team data for CHI or Brooklyn Nets
Missing team data for MIN or LAL

Points stats:

,player_name,team,avg_points,std_dev_points,cv_points
14,Dominick Barlow,Atlanta Hawks,0.50,0.71,1.42
28,Karlo Matković,New Orleans Pelicans,0.80,1.10,1.38
11,Mouhamed Gueye,Atlanta Hawks,1.00,1.41,1.41
33,Trey Jemison III,New Orleans Pelicans,2.62,2.63,1.00
15,Vít Krejčí,Atlanta Hawks,2.89,3.18,1.10
23,Daniel Theis,New Orleans Pelicans,3.56,2.61,0.73
1,Keaton Wallace,Atlanta Hawks,4.67,4.19,0.90
22,Jamal Cain,New Orleans Pelicans,5.08,4.73,0.93
2,Kobe Bufkin,Atlanta Hawks,5.29,2.93,0.55
25,Antonio Reeves,New Orleans Pelicans,5.33,9.41,1.77
4,David Roddy,Atlanta Hawks,5.77,5.23,0.91
20,Javonte Green,New Orleans Pelicans,6.52,3.87,0.59
17,Herbert Jones,New Orleans Pelicans,6.75,4.27,0.63
32,Jeremiah Robinson-Earl,New Orleans Pelicans,7.52,5.06,0.67
18,Elfrid Payton,New Orleans Pelicans,7.83,4.58,0.58
12,Larry Nance Jr.,Atlanta Hawks,7.89,7.37,0.93
13,Garrison Mathews,Atlanta Hawks,8.17,5.64,0.69
29,Yves Missi,New Orleans Pelicans,8.30,5.03,0.61
9,Clint Capela,Atlanta Hawks,10.67,5.74,0.54
27,Jose Alvarado,New Orleans Pelicans,10.73,8.79,0.82
10,Onyeka Okongwu,Atlanta Hawks,11.00,6.01,0.55
8,Bogdan Bogdanović,Atlanta Hawks,11.57,5.29,0.46
5,Zaccharie Risacher,Atlanta Hawks,11.57,6.85,0.59
24,Brandon Boston Jr.,New Orleans Pelicans,11.61,6.59,0.57
30,Jordan Hawkins,New Orleans Pelicans,13.09,8.42,0.64
3,Dyson Daniels,Atlanta Hawks,13.53,6.05,0.45
21,Dejounte Murray,New Orleans Pelicans,14.75,4.57,0.31
31,Trey Murphy III,New Orleans Pelicans,17.75,5.12,0.29
7,De'Andre Hunter,Atlanta Hawks,18.20,6.44,0.35
19,CJ McCollum,New Orleans Pelicans,20.00,7.95,0.40
0,Jalen Johnson,Atlanta Hawks,20.05,5.74,0.29
6,Trae Young,Atlanta Hawks,21.35,9.39,0.44
16,Zion Williamson,New Orleans Pelicans,22.67,9.71,0.43
26,Brandon Ingram,New Orleans Pelicans,22.88,7.20,0.31

Rebounds stats:

,player_name,team,avg_rebounds,std_dev_rebounds,cv_rebounds
14,Dominick Barlow,Atlanta Hawks,0.00,0.00,NaN
11,Mouhamed Gueye,Atlanta Hawks,1.00,1.41,1.41
13,Garrison Mathews,Atlanta Hawks,1.06,0.94,0.89
15,Vít Krejčí,Atlanta Hawks,1.11,1.54,1.39
25,Antonio Reeves,New Orleans Pelicans,1.33,1.50,1.13
1,Keaton Wallace,Atlanta Hawks,1.50,1.31,0.87
28,Karlo Matković,New Orleans Pelicans,2.00,2.00,1.00
27,Jose Alvarado,New Orleans Pelicans,2.18,2.23,1.02
2,Kobe Bufkin,Atlanta Hawks,2.29,1.50,0.66
12,Larry Nance Jr.,Atlanta Hawks,2.44,1.67,0.68
17,Herbert Jones,New Orleans Pelicans,2.50,1.29,0.52
22,Jamal Cain,New Orleans Pelicans,2.77,2.35,0.85
33,Trey Jemison III,New Orleans Pelicans,2.85,1.86,0.65
4,David Roddy,Atlanta Hawks,3.00,2.86,0.95
20,Javonte Green,New Orleans Pelicans,3.38,1.69,0.50
23,Daniel Theis,New Orleans Pelicans,3.38,2.16,0.64
19,CJ McCollum,New Orleans Pelicans,3.50,1.31,0.37
8,Bogdan Bogdanović,Atlanta Hawks,3.57,2.15,0.60
5,Zaccharie Risacher,Atlanta Hawks,3.62,2.46,0.68
6,Trae Young,Atlanta Hawks,3.65,2.13,0.58
30,Jordan Hawkins,New Orleans Pelicans,3.82,1.94,0.51
24,Brandon Boston Jr.,New Orleans Pelicans,3.89,2.52,0.65
18,Elfrid Payton,New Orleans Pelicans,4.00,2.10,0.52
7,De'Andre Hunter,Atlanta Hawks,4.30,1.77,0.41
3,Dyson Daniels,Atlanta Hawks,5.11,2.58,0.50
32,Jeremiah Robinson-Earl,New Orleans Pelicans,5.29,3.13,0.59
31,Trey Murphy III,New Orleans Pelicans,5.38,2.26,0.42
26,Brandon Ingram,New Orleans Pelicans,5.75,1.65,0.29
21,Dejounte Murray,New Orleans Pelicans,6.50,1.91,0.29
10,Onyeka Okongwu,Atlanta Hawks,6.68,3.00,0.45
29,Yves Missi,New Orleans Pelicans,7.55,3.46,0.46
16,Zion Williamson,New Orleans Pelicans,8.00,3.29,0.41
9,Clint Capela,Atlanta Hawks,8.81,3.27,0.37
0,Jalen Johnson,Atlanta Hawks,9.90,3.68,0.37

Assists stats:

,player_name,team,avg_assists,std_dev_assists,cv_assists
11,Mouhamed Gueye,Atlanta Hawks,0.00,0.00,NaN
28,Karlo Matković,New Orleans Pelicans,0.00,0.00,NaN
14,Dominick Barlow,Atlanta Hawks,0.00,0.00,NaN
25,Antonio Reeves,New Orleans Pelicans,0.42,0.90,2.14
33,Trey Jemison III,New Orleans Pelicans,0.62,0.65,1.05
22,Jamal Cain,New Orleans Pelicans,0.69,0.85,1.23
20,Javonte Green,New Orleans Pelicans,0.86,1.11,1.29
17,Herbert Jones,New Orleans Pelicans,1.00,0.82,0.82
15,Vít Krejčí,Atlanta Hawks,1.11,1.17,1.05
32,Jeremiah Robinson-Earl,New Orleans Pelicans,1.14,1.15,1.01
12,Larry Nance Jr.,Atlanta Hawks,1.22,1.39,1.14
30,Jordan Hawkins,New Orleans Pelicans,1.27,1.01,0.80
7,De'Andre Hunter,Atlanta Hawks,1.30,1.06,0.82
23,Daniel Theis,New Orleans Pelicans,1.31,1.25,0.95
9,Clint Capela,Atlanta Hawks,1.33,0.86,0.65
5,Zaccharie Risacher,Atlanta Hawks,1.38,0.97,0.70
13,Garrison Mathews,Atlanta Hawks,1.44,1.42,0.99
29,Yves Missi,New Orleans Pelicans,1.45,1.28,0.88
4,David Roddy,Atlanta Hawks,1.46,1.27,0.87
10,Onyeka Okongwu,Atlanta Hawks,1.68,1.42,0.85
8,Bogdan Bogdanović,Atlanta Hawks,1.71,1.38,0.81
1,Keaton Wallace,Atlanta Hawks,1.83,2.21,1.21
31,Trey Murphy III,New Orleans Pelicans,2.00,1.60,0.80
2,Kobe Bufkin,Atlanta Hawks,2.00,1.63,0.82
3,Dyson Daniels,Atlanta Hawks,3.05,1.43,0.47
19,CJ McCollum,New Orleans Pelicans,3.25,1.39,0.43
24,Brandon Boston Jr.,New Orleans Pelicans,3.89,2.08,0.53
27,Jose Alvarado,New Orleans Pelicans,4.45,1.97,0.44
16,Zion Williamson,New Orleans Pelicans,5.33,2.66,0.50
26,Brandon Ingram,New Orleans Pelicans,5.44,2.16,0.40
0,Jalen Johnson,Atlanta Hawks,5.50,2.50,0.45
21,Dejounte Murray,New Orleans Pelicans,5.75,3.30,0.57
18,Elfrid Payton,New Orleans Pelicans,7.83,6.74,0.86
6,Trae Young,Atlanta Hawks,12.05,4.16,0.35

In [ ]:
# Install required package
!pip install nba_api

import json
from nba_api.stats.endpoints import teamestimatedmetrics, leaguedashteamstats, commonteamroster
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display
import time

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Positional mapping
POSITION_MAPPING = {
    "guard": "G",
    "forward": "F",
    "center": "C",
    "guard-forward": "G-F",
    "forward-center": "F-C",
    "forward-guard": "F-G",
    "center-forward": "C-F"
}

# Fetch Defense vs Position metrics
def fetch_dvp(position):
    try:
        stats = leaguedashteamstats.LeagueDashTeamStats(
            measure_type_detailed_defense="Opponent",
            per_mode_detailed="PerGame",
            player_position_abbreviation_nullable=position
        )
        dvp_df = stats.get_data_frames()[0]
        dvp_df = dvp_df[["TEAM_ID", "OPP_PTS", "OPP_REB", "OPP_AST"]]
        dvp_df.rename(columns={
            "OPP_PTS": f"OPP_PTS_{position}",
            "OPP_REB": f"OPP_REB_{position}",
            "OPP_AST": f"OPP_AST_{position}"
        }, inplace=True)
        return dvp_df
    except Exception as e:
        print(f"Error fetching DvP metrics for position {position}: {e}")
        return pd.DataFrame()

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        # Set timezone to EST
        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        )
        data = team_metrics.get_data_frames()[0]
        metrics = data[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        # Calculate league averages
        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        # Map abbreviations to full names
        team_name_mapping = {
            "ATL": "Atlanta Hawks", "BOS": "Boston Celtics", "BKN": "Brooklyn Nets", "CHA": "Charlotte Hornets",
            "CHI": "Chicago Bulls", "CLE": "Cleveland Cavaliers", "DAL": "Dallas Mavericks", "DEN": "Denver Nuggets",
            "DET": "Detroit Pistons", "GSW": "Golden State Warriors", "HOU": "Houston Rockets", "IND": "Indiana Pacers",
            "LAC": "Los Angeles Clippers", "LAL": "Los Angeles Lakers", "MEM": "Memphis Grizzlies", "MIA": "Miami Heat",
            "MIL": "Milwaukee Bucks", "MIN": "Minnesota Timberwolves", "NOP": "New Orleans Pelicans", "NYK": "New York Knicks",
            "OKC": "Oklahoma City Thunder", "ORL": "Orlando Magic", "PHI": "Philadelphia 76ers", "PHX": "Phoenix Suns",
            "POR": "Portland Trail Blazers", "SAC": "Sacramento Kings", "SAS": "San Antonio Spurs", "TOR": "Toronto Raptors",
            "UTA": "Utah Jazz", "WAS": "Washington Wizards"
        }

        # Adjusted metrics dictionary
        adjusted_metrics = {}
        for abbr, full_name in team_name_mapping.items():
            if full_name in metrics_dict:
                adjusted_metrics[abbr] = metrics_dict[full_name]
            else:
                print(f"Warning: Metrics not found for {abbr} ({full_name}).")

        return adjusted_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Analyze teams and players for today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()

    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    dvp_data = {pos: fetch_dvp(pos) for pos in POSITION_MAPPING.values()}
    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        if home_team not in team_metrics or away_team not in team_metrics:
            print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
            continue

        for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
            try:
                team_roster = commonteamroster.CommonTeamRoster(
                    team_id=teams.find_team_by_abbreviation(team_name)['id']
                ).get_data_frames()[0]

                for _, player in team_roster.iterrows():
                    player_id = player['PLAYER_ID']
                    player_name = player['PLAYER']
                    position = player['POSITION'].lower()
                    position_role = POSITION_MAPPING.get(position, None)

                    if position_role not in dvp_data:
                        print(f"DvP data not found for position {position_role}. Skipping player {player_name}.")
                        continue

                    game_logs = fetch_player_game_logs(player_id)
                    if game_logs.empty:
                        continue

                    mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                    mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                    mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                    dvp = dvp_data[position_role]
                    adjusted_ppg = adjust_with_dvp(mean_ppg, dvp, team_name)
                    adjusted_rpg = adjust_with_dvp(mean_rpg, dvp, team_name)
                    adjusted_apg = adjust_with_dvp(mean_apg, dvp, team_name)

                    all_players_data.append({
                        'Player': player_name,
                        'Team': team_name,
                        'Position': position,
                        'PPG': mean_ppg,
                        'PPG SD': std_dev_ppg,
                        'PPG CV': cv_ppg,
                        'RPG': mean_rpg,
                        'RPG SD': std_dev_rpg,
                        'RPG CV': cv_rpg,
                        'APG': mean_apg,
                        'APG SD': std_dev_apg,
                        'APG CV': cv_apg,
                        'Adjusted PPG': adjusted_ppg,
                        'Adjusted RPG': adjusted_rpg,
                        'Adjusted APG': adjusted_apg
                    })
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    player_stats_df = pd.DataFrame(all_players_data)
    display(player_stats_df)
    return player_stats_df

# Run analysis
player_stats = analyze_teams_for_today()

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Warning: Metrics not found for LAC (Los Angeles Clippers).
Error fetching DvP metrics for position G-F: 'resultSet'
Error fetching DvP metrics for position F-C: 'resultSet'
Error fetching DvP metrics for position F-G: 'resultSet'
Error fetching DvP metrics for position C-F: 'resultSet'
DvP data not found for position None. Skipping player Jalen Johnson.
DvP data not found for position None. Skipping player Keaton Wallace.
DvP data not found for position None. Skipping player Seth Lundy.
DvP data not found for position None. Skipping player Kobe Bufkin.
DvP data not found for position None. Skipping player Dyson Daniels.
DvP data not found for position None. Skipping player David Roddy.
DvP data not found for position None. Skipping player Zaccharie Risacher.
DvP data not found for position None. Skipping player Trae Young.
DvP data not found for position None. Skipping player De'Andre Hunter.
DvP data not found for position None. Skipping player Bogdan Bogdanović.
DvP data not found for position None. Skipping player Clint Capela.
DvP data not found for position None. Skipping player Onyeka Okongwu.
DvP data not found for position None. Skipping player Mouhamed Gueye.
DvP data not found for position None. Skipping player Larry Nance Jr..
DvP data not found for position None. Skipping player Garrison Mathews.
DvP data not found for position None. Skipping player Dominick Barlow.
DvP data not found for position None. Skipping player Vít Krejčí.
DvP data not found for position None. Skipping player Cody Zeller.
DvP data not found for position None. Skipping player Zion Williamson.
DvP data not found for position None. Skipping player Herbert Jones.
DvP data not found for position None. Skipping player Elfrid Payton.
DvP data not found for position None. Skipping player CJ McCollum.
DvP data not found for position None. Skipping player Javonte Green.
DvP data not found for position None. Skipping player Dejounte Murray.
DvP data not found for position None. Skipping player Jamal Cain.
DvP data not found for position None. Skipping player Daniel Theis.
DvP data not found for position None. Skipping player Brandon Boston Jr..
DvP data not found for position None. Skipping player Antonio Reeves.
DvP data not found for position None. Skipping player Brandon Ingram.
DvP data not found for position None. Skipping player Jose Alvarado.
DvP data not found for position None. Skipping player Karlo Matković.
DvP data not found for position None. Skipping player Yves Missi.
DvP data not found for position None. Skipping player Jordan Hawkins.
DvP data not found for position None. Skipping player Trey Murphy III.
DvP data not found for position None. Skipping player Jeremiah Robinson-Earl.
DvP data not found for position None. Skipping player Trey Jemison III.
DvP data not found for position None. Skipping player Jayson Tatum.
DvP data not found for position None. Skipping player Jrue Holiday.
DvP data not found for position None. Skipping player Jaylen Brown.
DvP data not found for position None. Skipping player Kristaps Porziņģis.
DvP data not found for position None. Skipping player Derrick White.
DvP data not found for position None. Skipping player Payton Pritchard.
DvP data not found for position None. Skipping player Drew Peterson.
DvP data not found for position None. Skipping player JD Davison.
DvP data not found for position None. Skipping player Xavier Tillman.
DvP data not found for position None. Skipping player Jordan Walsh.
DvP data not found for position None. Skipping player Anton Watson.
DvP data not found for position None. Skipping player Sam Hauser.
DvP data not found for position None. Skipping player Luke Kornet.
DvP data not found for position None. Skipping player Al Horford.
DvP data not found for position None. Skipping player Jaden Springer.
DvP data not found for position None. Skipping player Baylor Scheierman.
DvP data not found for position None. Skipping player Neemias Queta.
DvP data not found for position None. Skipping player Josh Richardson.
DvP data not found for position None. Skipping player Terry Rozier.
DvP data not found for position None. Skipping player Nikola Jović.
DvP data not found for position None. Skipping player Kel'el Ware.
DvP data not found for position None. Skipping player Josh Christopher.
DvP data not found for position None. Skipping player Pelle Larsson.
DvP data not found for position None. Skipping player Jaime Jaquez Jr..
DvP data not found for position None. Skipping player Dru Smith.
DvP data not found for position None. Skipping player Bam Adebayo.
DvP data not found for position None. Skipping player Tyler Herro.
DvP data not found for position None. Skipping player Keshad Johnson.
DvP data not found for position None. Skipping player Alec Burks.
DvP data not found for position None. Skipping player Jimmy Butler.
DvP data not found for position None. Skipping player Haywood Highsmith.
DvP data not found for position None. Skipping player Thomas Bryant.
DvP data not found for position None. Skipping player Kevin Love.
DvP data not found for position None. Skipping player Duncan Robinson.
DvP data not found for position None. Skipping player Coby White.
DvP data not found for position None. Skipping player DJ Steward.
DvP data not found for position None. Skipping player Lonzo Ball.
DvP data not found for position None. Skipping player Josh Giddey.
DvP data not found for position None. Skipping player Jevon Carter.
DvP data not found for position None. Skipping player Jalen Smith.
DvP data not found for position None. Skipping player Zach LaVine.
DvP data not found for position None. Skipping player Nikola Vučević.
DvP data not found for position None. Skipping player Ayo Dosunmu.
DvP data not found for position None. Skipping player Torrey Craig.
DvP data not found for position None. Skipping player Matas Buzelis.
DvP data not found for position None. Skipping player Julian Phillips.
DvP data not found for position None. Skipping player Adama Sanogo.
DvP data not found for position None. Skipping player Talen Horton-Tucker.
DvP data not found for position None. Skipping player Dalen Terry.
DvP data not found for position None. Skipping player Chris Duarte.
DvP data not found for position None. Skipping player E.J. Liddell.
DvP data not found for position None. Skipping player Patrick Williams.
DvP data not found for position None. Skipping player Dariq Whitehead.
DvP data not found for position None. Skipping player Ziaire Williams.
DvP data not found for position None. Skipping player Cameron Johnson.
DvP data not found for position None. Skipping player Shake Milton.
DvP data not found for position None. Skipping player Cui Yongxi.
DvP data not found for position None. Skipping player Trendon Watford.
DvP data not found for position None. Skipping player Ben Simmons.
DvP data not found for position None. Skipping player Tyrese Martin.
DvP data not found for position None. Skipping player Jaylen Martin.
DvP data not found for position None. Skipping player Dennis Schröder.
DvP data not found for position None. Skipping player Day'Ron Sharpe.
DvP data not found for position None. Skipping player Noah Clowney.
DvP data not found for position None. Skipping player Jalen Wilson.
DvP data not found for position None. Skipping player Cam Thomas.
DvP data not found for position None. Skipping player Dorian Finney-Smith.
DvP data not found for position None. Skipping player Nic Claxton.
DvP data not found for position None. Skipping player Bojan Bogdanović.
DvP data not found for position None. Skipping player Keon Johnson.
DvP data not found for position None. Skipping player Terrence Shannon Jr..
DvP data not found for position None. Skipping player Donte DiVincenzo.
DvP data not found for position None. Skipping player Daishen Nix.
DvP data not found for position None. Skipping player Jaden McDaniels.
DvP data not found for position None. Skipping player Rob Dillingham.
DvP data not found for position None. Skipping player Anthony Edwards.
DvP data not found for position None. Skipping player Joe Ingles.
DvP data not found for position None. Skipping player Josh Minott.
DvP data not found for position None. Skipping player Nickeil Alexander-Walker.
DvP data not found for position None. Skipping player Mike Conley.
DvP data not found for position None. Skipping player Naz Reid.
DvP data not found for position None. Skipping player Jesse Edwards.
DvP data not found for position None. Skipping player Jaylen Clark.
DvP data not found for position None. Skipping player Rudy Gobert.
DvP data not found for position None. Skipping player Julius Randle.
DvP data not found for position None. Skipping player Leonard Miller.
DvP data not found for position None. Skipping player PJ Dozier.
DvP data not found for position None. Skipping player Luka Garza.
DvP data not found for position None. Skipping player Jalen Hood-Schifino.
DvP data not found for position None. Skipping player D'Angelo Russell.
DvP data not found for position None. Skipping player Jarred Vanderbilt.
DvP data not found for position None. Skipping player Anthony Davis.
DvP data not found for position None. Skipping player Dalton Knecht.
DvP data not found for position None. Skipping player Cam Reddish.
DvP data not found for position None. Skipping player Gabe Vincent.
DvP data not found for position None. Skipping player Bronny James.
DvP data not found for position None. Skipping player Christian Koloko.
DvP data not found for position None. Skipping player Jaxson Hayes.
DvP data not found for position None. Skipping player Max Christie.
DvP data not found for position None. Skipping player Austin Reaves.
DvP data not found for position None. Skipping player Maxwell Lewis.
DvP data not found for position None. Skipping player LeBron James.
DvP data not found for position None. Skipping player Rui Hachimura.
DvP data not found for position None. Skipping player Christian Wood.
DvP data not found for position None. Skipping player Quincy Olivari.
DvP data not found for position None. Skipping player Armel Traoré.

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Install required package
!pip install nba_api

import json
from nba_api.stats.endpoints import teamestimatedmetrics
from nba_api.stats.endpoints import TeamVsPlayer
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, commonteamroster
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display
import time

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        # Set timezone to EST
        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Function to fetch DvP stats
def fetch_dvp_stats(team_id):
    try:
        # Correcting the season_type parameter
        stats = TeamVsPlayer(team_id=team_id, season_type='Regular Season')
        return stats.get_data_frames()[0]  # return the first dataframe
    except Exception as e:
        print(f"Error fetching DvP stats for team {team_id}: {e}")
        return None

# Function to process player data
def process_players(team):
    team_players = team['players']
    player_stats = []
    for player in team_players:
        player_data = {
            'Player': player['full_name'],
            'Position': player.get('position', 'Unknown')  # Handle missing 'POS' field
        }
        player_stats.append(player_data)
    return player_stats

# Fetch team metrics
def fetch_team_metrics():
    try:
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        )
        data = team_metrics.get_data_frames()[0]
        metrics = data[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        # Calculate league averages
        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        # Map abbreviations to full names
        team_name_mapping = {
            "ATL": "Atlanta Hawks", "BOS": "Boston Celtics", "BKN": "Brooklyn Nets", "CHA": "Charlotte Hornets",
            "CHI": "Chicago Bulls", "CLE": "Cleveland Cavaliers", "DAL": "Dallas Mavericks", "DEN": "Denver Nuggets",
            "DET": "Detroit Pistons", "GSW": "Golden State Warriors", "HOU": "Houston Rockets", "IND": "Indiana Pacers",
            "LAC": "Los Angeles Clippers", "LAL": "Los Angeles Lakers", "MEM": "Memphis Grizzlies", "MIA": "Miami Heat",
            "MIL": "Milwaukee Bucks", "MIN": "Minnesota Timberwolves", "NOP": "New Orleans Pelicans", "NYK": "New York Knicks",
            "OKC": "Oklahoma City Thunder", "ORL": "Orlando Magic", "PHI": "Philadelphia 76ers", "PHX": "Phoenix Suns",
            "POR": "Portland Trail Blazers", "SAC": "Sacramento Kings", "SAS": "San Antonio Spurs", "TOR": "Toronto Raptors",
            "UTA": "Utah Jazz", "WAS": "Washington Wizards"
        }

        # Adjusted metrics dictionary
        adjusted_metrics = {}
        for abbr, full_name in team_name_mapping.items():
            if full_name in metrics_dict:
                adjusted_metrics[abbr] = metrics_dict[full_name]
            else:
                print(f"Warning: Metrics not found for {abbr} ({full_name}).")

        return adjusted_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Analyze teams and players for today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()

    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        if home_team not in team_metrics or away_team not in team_metrics:
            print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
            continue

        for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
            try:
                team_roster = commonteamroster.CommonTeamRoster(
                    team_id=teams.find_team_by_abbreviation(team_name)['id']
                ).get_data_frames()[0]

                for _, player in team_roster.iterrows():
                    player_id = player['PLAYER_ID']
                    player_name = player['PLAYER']
                    print(f"Fetching data for {player_name} ({team_name})")

                    game_logs = fetch_player_game_logs(player_id)
                    if game_logs.empty:
                        continue

                    mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                    mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                    mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                    adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)

                    all_players_data.append({
                        'Player': player_name,
                        'Team': team_name,
                        'PPG': mean_ppg,
                        'PPG SD': std_dev_ppg,
                        'PPG CV': cv_ppg,
                        'RPG': mean_rpg,
                        'RPG SD': std_dev_rpg,
                        'RPG CV': cv_rpg,
                        'APG': mean_apg,
                        'APG SD': std_dev_apg,
                        'APG CV': cv_apg,
                        'Adjusted PPG': adjusted_ppg,
                        'Adjusted RPG': adjusted_rpg,
                        'Adjusted APG': adjusted_apg
                    })
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    player_stats_df = pd.DataFrame(all_players_data)
    display(player_stats_df)
    return player_stats_df

# Run analysis
player_stats = analyze_teams_for_today()

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Warning: Metrics not found for LAC (Los Angeles Clippers).
Fetching data for Jalen Johnson (ATL)
Fetching game logs for player ID: 1630552
Error processing team ATL: name 'adjust_prediction' is not defined
Fetching data for Zion Williamson (NOP)
Fetching game logs for player ID: 1629627
Error processing team NOP: name 'adjust_prediction' is not defined
Fetching data for Jayson Tatum (BOS)
Fetching game logs for player ID: 1628369
Error processing team BOS: name 'adjust_prediction' is not defined
Fetching data for Josh Richardson (MIA)
Fetching game logs for player ID: 1626196
Error processing team MIA: name 'adjust_prediction' is not defined
Fetching data for Coby White (CHI)
Fetching game logs for player ID: 1629632
Error processing team CHI: name 'adjust_prediction' is not defined
Fetching data for Dariq Whitehead (BKN)
Fetching game logs for player ID: 1641727
Error processing team BKN: name 'adjust_prediction' is not defined
Fetching data for Terrence Shannon Jr. (MIN)
Fetching game logs for player ID: 1630545
Error processing team MIN: name 'adjust_prediction' is not defined
Fetching data for Jalen Hood-Schifino (LAL)
Fetching game logs for player ID: 1641720
Error processing team LAL: name 'adjust_prediction' is not defined

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Install required package
!pip install nba_api

import json
from nba_api.stats.endpoints import teamestimatedmetrics, playergamelog, commonteamroster
from nba_api.stats.endpoints import TeamVsPlayer
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.static import teams
from IPython.display import display
import time

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        # Set timezone to EST
        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        logs = playergamelog.PlayerGameLog(player_id=player_id, season_all=SeasonAll.current_season).get_data_frames()[0]
        return logs
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

# Calculate statistics
def calculate_stats(series):
    mean = series.mean()
    std_dev = series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust prediction with team metrics
def adjust_prediction(stat, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating):
    pace_factor = team_metrics['E_PACE'] / avg_pace
    offensive_factor = opposing_metrics['E_DEF_RATING'] / avg_def_rating
    return stat * pace_factor * offensive_factor

# Fetch team metrics
def fetch_team_metrics():
    try:
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        )
        data = team_metrics.get_data_frames()[0]
        metrics = data[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        # Calculate league averages
        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        return metrics_dict, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Analyze teams and players for today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()

    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        for team_abbr in [game['home_team'], game['away_team']]:
            try:
                team_id = teams.find_team_by_abbreviation(team_abbr)['id']
                team_roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in team_roster.iterrows():
                    player_id = player['PLAYER_ID']
                    player_name = player['PLAYER']
                    print(f"Fetching data for {player_name} ({team_abbr})")

                    game_logs = fetch_player_game_logs(player_id)
                    if game_logs.empty:
                        continue

                    mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                    mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                    mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                    adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_abbr], team_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_abbr], team_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_abbr], team_metrics, avg_pace, avg_off_rating, avg_def_rating)

                    all_players_data.append({
                        'Player': player_name,
                        'Team': team_abbr,
                        'PPG': mean_ppg,
                        'PPG SD': std_dev_ppg,
                        'PPG CV': cv_ppg,
                        'RPG': mean_rpg,
                        'RPG SD': std_dev_rpg,
                        'RPG CV': cv_rpg,
                        'APG': mean_apg,
                        'APG SD': std_dev_apg,
                        'APG CV': cv_apg,
                        'Adjusted PPG': adjusted_ppg,
                        'Adjusted RPG': adjusted_rpg,
                        'Adjusted APG': adjusted_apg
                    })
            except Exception as e:
                print(f"Error processing team {team_abbr}: {e}")

    player_stats_df = pd.DataFrame(all_players_data)
    display(player_stats_df)
    return player_stats_df

# Run analysis
player_stats = analyze_teams_for_today()

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Fetching data for Jalen Johnson (ATL)
Error fetching game logs for player 1630552: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Keaton Wallace (ATL)
Error fetching game logs for player 1630811: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Seth Lundy (ATL)
Error fetching game logs for player 1641754: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Kobe Bufkin (ATL)
Error fetching game logs for player 1641723: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dyson Daniels (ATL)
Error fetching game logs for player 1630700: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for David Roddy (ATL)
Error fetching game logs for player 1631223: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Zaccharie Risacher (ATL)
Error fetching game logs for player 1642258: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Trae Young (ATL)
Error fetching game logs for player 1629027: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for De'Andre Hunter (ATL)
Error fetching game logs for player 1629631: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Bogdan Bogdanović (ATL)
Error fetching game logs for player 203992: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Clint Capela (ATL)
Error fetching game logs for player 203991: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Onyeka Okongwu (ATL)
Error fetching game logs for player 1630168: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Mouhamed Gueye (ATL)
Error fetching game logs for player 1631243: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Larry Nance Jr. (ATL)
Error fetching game logs for player 1626204: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Garrison Mathews (ATL)
Error fetching game logs for player 1629726: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dominick Barlow (ATL)
Error fetching game logs for player 1631230: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Vít Krejčí (ATL)
Error fetching game logs for player 1630249: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Cody Zeller (ATL)
Error fetching game logs for player 203469: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Zion Williamson (NOP)
Error fetching game logs for player 1629627: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Herbert Jones (NOP)
Error fetching game logs for player 1630529: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Elfrid Payton (NOP)
Error fetching game logs for player 203901: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for CJ McCollum (NOP)
Error fetching game logs for player 203468: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Javonte Green (NOP)
Error fetching game logs for player 1629750: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dejounte Murray (NOP)
Error fetching game logs for player 1627749: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jamal Cain (NOP)
Error fetching game logs for player 1631288: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Daniel Theis (NOP)
Error fetching game logs for player 1628464: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Brandon Boston Jr. (NOP)
Error fetching game logs for player 1630527: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Antonio Reeves (NOP)
Error fetching game logs for player 1641810: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Brandon Ingram (NOP)
Error fetching game logs for player 1627742: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jose Alvarado (NOP)
Error fetching game logs for player 1630631: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Karlo Matković (NOP)
Error fetching game logs for player 1631255: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Yves Missi (NOP)
Error fetching game logs for player 1642274: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jordan Hawkins (NOP)
Error fetching game logs for player 1641722: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Trey Murphy III (NOP)
Error fetching game logs for player 1630530: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jeremiah Robinson-Earl (NOP)
Error fetching game logs for player 1630526: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Trey Jemison III (NOP)
Error fetching game logs for player 1641998: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jayson Tatum (BOS)
Error fetching game logs for player 1628369: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jrue Holiday (BOS)
Error fetching game logs for player 201950: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jaylen Brown (BOS)
Error fetching game logs for player 1627759: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Kristaps Porziņģis (BOS)
Error fetching game logs for player 204001: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Derrick White (BOS)
Error fetching game logs for player 1628401: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Payton Pritchard (BOS)
Error fetching game logs for player 1630202: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Drew Peterson (BOS)
Error fetching game logs for player 1641809: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for JD Davison (BOS)
Error fetching game logs for player 1631120: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Xavier Tillman (BOS)
Error fetching game logs for player 1630214: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jordan Walsh (BOS)
Error fetching game logs for player 1641775: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Anton Watson (BOS)
Error fetching game logs for player 1641817: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Sam Hauser (BOS)
Error fetching game logs for player 1630573: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Luke Kornet (BOS)
Error fetching game logs for player 1628436: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Al Horford (BOS)
Error fetching game logs for player 201143: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jaden Springer (BOS)
Error fetching game logs for player 1630531: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Baylor Scheierman (BOS)
Error fetching game logs for player 1631248: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Neemias Queta (BOS)
Error fetching game logs for player 1629674: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Josh Richardson (MIA)
Error fetching game logs for player 1626196: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Terry Rozier (MIA)
Error fetching game logs for player 1626179: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Nikola Jović (MIA)
Error fetching game logs for player 1631107: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Kel'el Ware (MIA)
Error fetching game logs for player 1642276: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Josh Christopher (MIA)
Error fetching game logs for player 1630528: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Pelle Larsson (MIA)
Error fetching game logs for player 1641796: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jaime Jaquez Jr. (MIA)
Error fetching game logs for player 1631170: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dru Smith (MIA)
Error fetching game logs for player 1630696: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Bam Adebayo (MIA)
Error fetching game logs for player 1628389: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Tyler Herro (MIA)
Error fetching game logs for player 1629639: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Keshad Johnson (MIA)
Error fetching game logs for player 1642352: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Alec Burks (MIA)
Error fetching game logs for player 202692: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jimmy Butler (MIA)
Error fetching game logs for player 202710: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Haywood Highsmith (MIA)
Error fetching game logs for player 1629312: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Thomas Bryant (MIA)
Error fetching game logs for player 1628418: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Kevin Love (MIA)
Error fetching game logs for player 201567: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Duncan Robinson (MIA)
Error fetching game logs for player 1629130: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Coby White (CHI)
Error fetching game logs for player 1629632: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for DJ Steward (CHI)
Error fetching game logs for player 1630569: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Lonzo Ball (CHI)
Error fetching game logs for player 1628366: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Josh Giddey (CHI)
Error fetching game logs for player 1630581: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jevon Carter (CHI)
Error fetching game logs for player 1628975: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jalen Smith (CHI)
Error fetching game logs for player 1630188: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Zach LaVine (CHI)
Error fetching game logs for player 203897: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Nikola Vučević (CHI)
Error fetching game logs for player 202696: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Ayo Dosunmu (CHI)
Error fetching game logs for player 1630245: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Torrey Craig (CHI)
Error fetching game logs for player 1628470: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Matas Buzelis (CHI)
Error fetching game logs for player 1641824: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Julian Phillips (CHI)
Error fetching game logs for player 1641763: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Adama Sanogo (CHI)
Error fetching game logs for player 1641766: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Talen Horton-Tucker (CHI)
Error fetching game logs for player 1629659: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dalen Terry (CHI)
Error fetching game logs for player 1631207: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Chris Duarte (CHI)
Error fetching game logs for player 1630537: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for E.J. Liddell (CHI)
Error fetching game logs for player 1630604: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Patrick Williams (CHI)
Error fetching game logs for player 1630172: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dariq Whitehead (BKN)
Error fetching game logs for player 1641727: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Ziaire Williams (BKN)
Error fetching game logs for player 1630533: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Cameron Johnson (BKN)
Error fetching game logs for player 1629661: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Shake Milton (BKN)
Error fetching game logs for player 1629003: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Cui Yongxi (BKN)
Error fetching game logs for player 1642385: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Trendon Watford (BKN)
Error fetching game logs for player 1630570: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Ben Simmons (BKN)
Error fetching game logs for player 1627732: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Tyrese Martin (BKN)
Error fetching game logs for player 1631213: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jaylen Martin (BKN)
Error fetching game logs for player 1641798: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dennis Schröder (BKN)
Error fetching game logs for player 203471: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Day'Ron Sharpe (BKN)
Error fetching game logs for player 1630549: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Noah Clowney (BKN)
Error fetching game logs for player 1641730: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jalen Wilson (BKN)
Error fetching game logs for player 1630592: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Cam Thomas (BKN)
Error fetching game logs for player 1630560: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Dorian Finney-Smith (BKN)
Error fetching game logs for player 1627827: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Nic Claxton (BKN)
Error fetching game logs for player 1629651: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Bojan Bogdanović (BKN)
Error fetching game logs for player 202711: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Keon Johnson (BKN)
Error fetching game logs for player 1630553: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Terrence Shannon Jr. (MIN)
Error fetching game logs for player 1630545: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Donte DiVincenzo (MIN)
Error fetching game logs for player 1628978: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Daishen Nix (MIN)
Error fetching game logs for player 1630227: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jaden McDaniels (MIN)
Error fetching game logs for player 1630183: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Rob Dillingham (MIN)
Error fetching game logs for player 1642265: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Anthony Edwards (MIN)
Error fetching game logs for player 1630162: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Joe Ingles (MIN)
Error fetching game logs for player 204060: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Josh Minott (MIN)
Error fetching game logs for player 1631169: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Nickeil Alexander-Walker (MIN)
Error fetching game logs for player 1629638: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Mike Conley (MIN)
Error fetching game logs for player 201144: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Naz Reid (MIN)
Error fetching game logs for player 1629675: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jesse Edwards (MIN)
Error fetching game logs for player 1642399: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Jaylen Clark (MIN)
Error fetching game logs for player 1641740: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Rudy Gobert (MIN)
Error fetching game logs for player 203497: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Julius Randle (MIN)
Error fetching game logs for player 203944: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for Leonard Miller (MIN)
Error fetching game logs for player 1631159: PlayerGameLog.__init__() got an unexpected keyword argument 'season_all'
Fetching data for PJ Dozier (MIN)

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Install required package
!pip install nba_api

import json
from nba_api.stats.endpoints import teamestimatedmetrics
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, commonteamroster
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display
import time

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        # Set timezone to EST
        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        )
        data = team_metrics.get_data_frames()[0]
        metrics = data[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        # Calculate league averages
        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        # Map abbreviations to full names
        team_name_mapping = {
            "ATL": "Atlanta Hawks", "BOS": "Boston Celtics", "BKN": "Brooklyn Nets", "CHA": "Charlotte Hornets",
            "CHI": "Chicago Bulls", "CLE": "Cleveland Cavaliers", "DAL": "Dallas Mavericks", "DEN": "Denver Nuggets",
            "DET": "Detroit Pistons", "GSW": "Golden State Warriors", "HOU": "Houston Rockets", "IND": "Indiana Pacers",
            "LAC": "Los Angeles Clippers", "LAL": "Los Angeles Lakers", "MEM": "Memphis Grizzlies", "MIA": "Miami Heat",
            "MIL": "Milwaukee Bucks", "MIN": "Minnesota Timberwolves", "NOP": "New Orleans Pelicans", "NYK": "New York Knicks",
            "OKC": "Oklahoma City Thunder", "ORL": "Orlando Magic", "PHI": "Philadelphia 76ers", "PHX": "Phoenix Suns",
            "POR": "Portland Trail Blazers", "SAC": "Sacramento Kings", "SAS": "San Antonio Spurs", "TOR": "Toronto Raptors",
            "UTA": "Utah Jazz", "WAS": "Washington Wizards"
        }

        # Adjusted metrics dictionary
        adjusted_metrics = {}
        for abbr, full_name in team_name_mapping.items():
            if full_name in metrics_dict:
                adjusted_metrics[abbr] = metrics_dict[full_name]
            else:
                print(f"Warning: Metrics not found for {abbr} ({full_name}).")

        return adjusted_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Analyze teams and players for today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()

    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        if home_team not in team_metrics or away_team not in team_metrics:
            print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
            continue

        for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
            try:
                team_roster = commonteamroster.CommonTeamRoster(
                    team_id=teams.find_team_by_abbreviation(team_name)['id']
                ).get_data_frames()[0]

                for _, player in team_roster.iterrows():
                    player_id = player['PLAYER_ID']
                    player_name = player['PLAYER']
                    print(f"Fetching data for {player_name} ({team_name})")

                    game_logs = fetch_player_game_logs(player_id)
                    if game_logs.empty:
                        continue

                    mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                    mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                    mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                    adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)

                    all_players_data.append({
                        'Player': player_name,
                        'Team': team_name,
                        'PPG': mean_ppg,
                        'PPG SD': std_dev_ppg,
                        'PPG CV': cv_ppg,
                        'RPG': mean_rpg,
                        'RPG SD': std_dev_rpg,
                        'RPG CV': cv_rpg,
                        'APG': mean_apg,
                        'APG SD': std_dev_apg,
                        'APG CV': cv_apg,
                        'Adjusted PPG': adjusted_ppg,
                        'Adjusted RPG': adjusted_rpg,
                        'Adjusted APG': adjusted_apg
                    })
            except Exception as e:
                print(f"Error processing team {team_name}: {e}")

    player_stats_df = pd.DataFrame(all_players_data)
    display(player_stats_df)
    return player_stats_df

# Run analysis
player_stats = analyze_teams_for_today()

Collecting nba_api
  Downloading nba_api-1.7.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.11/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.11/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.12.14)
Downloading nba_api-1.7.0-py3-none-any.whl (280 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 3.4 MB/s eta 0:00:00
Installing collected packages: nba_api
Successfully installed nba_api-1.7.0
Warning: Metrics not found for LAC (Los Angeles Clippers).
Fetching data for Bilal Coulibaly (WAS)
Error processing team WAS: name 'fetch_player_game_logs' is not defined
Fetching data for Jalen Hood-Schifino (LAL)
Error processing team LAL: name 'fetch_player_game_logs' is not defined
Fetching data for Max Strus (CLE)
Error processing team CLE: name 'fetch_player_game_logs' is not defined
Fetching data for Jalen Johnson (ATL)
Error processing team ATL: name 'fetch_player_game_logs' is not defined
Fetching data for Jordan Clarkson (UTA)
Error processing team UTA: name 'fetch_player_game_logs' is not defined
Fetching data for Terrence Shannon Jr. (MIN)
Error processing team MIN: name 'fetch_player_game_logs' is not defined
Fetching data for Zyon Pullin (MEM)
Error processing team MEM: name 'fetch_player_game_logs' is not defined
Fetching data for Aaron Holiday (HOU)
Error processing team HOU: name 'fetch_player_game_logs' is not defined
Fetching data for Scoot Henderson (POR)
Error processing team POR: name 'fetch_player_game_logs' is not defined
Fetching data for Anthony Black (ORL)
Error processing team ORL: name 'fetch_player_game_logs' is not defined

Empty DataFrame
Columns: []
Index: []