In [4]:
# Install required package
!pip install nba_api

import json
import time
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.endpoints import teamestimatedmetrics, playerestimatedmetrics
from nba_api.stats.endpoints import leaguedashteamstats, commonteamroster
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, playergamelogs
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display

# Map of team names to abbreviations
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL", "Boston Celtics": "BOS", "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA", "Chicago Bulls": "CHI", "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL", "Denver Nuggets": "DEN", "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW", "Houston Rockets": "HOU", "Indiana Pacers": "IND",
    "LA Clippers": "LAC", "Los Angeles Lakers": "LAL", "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA", "Milwaukee Bucks": "MIL", "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP", "New York Knicks": "NYK", "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL", "Philadelphia 76ers": "PHI", "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR", "Sacramento Kings": "SAC", "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR", "Utah Jazz": "UTA", "Washington Wizards": "WAS"
}

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        stats = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        ).get_data_frames()[0]

        metrics = stats[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        team_metrics = {TEAM_NAME_TO_ABBREVIATION.get(k, k): v for k, v in metrics_dict.items()}
        return team_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Initialize DvP data
def initialize_dvp_data():
    try:
        stats = leaguedashteamstats.LeagueDashTeamStats(
            measure_type_detailed_defense='Opponent',
            per_mode_detailed='PerGame',
            season="2024-25",
            season_type_all_star="Regular Season"
        ).get_data_frames()[0]

        stats['TEAM_ABBREVIATION'] = stats['TEAM_NAME'].map(TEAM_NAME_TO_ABBREVIATION)

        dvp_data = {}
        for pos in ['C', 'F', 'G']:
            column = f'OPP_PTS_{pos.upper()}'
            if column in stats.columns:
                dvp_data[pos] = stats.groupby('TEAM_ABBREVIATION')[column].mean().to_dict()

        return dvp_data
    except Exception as e:
        print(f"Error fetching DvP stats: {e}")
        return {}

# Normalize player positions
def normalize_player_position(position):
    if not position or not isinstance(position, str):
        return []

    positions = position.split("-")
    valid_positions = {'C', 'F', 'G'}
    return [pos.strip() for pos in positions if pos.strip() in valid_positions]

# Initialize globally for consistent usage across functions
normalized_positions = []  # Collect all normalized positions globally

# Process team rosters
def process_team_roster(team_name):
    global normalized_positions  # Ensure this modifies the global list
    try:
        team_id = teams.find_team_by_abbreviation(team_name)['id']
        roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

        for _, player in roster.iterrows():
            player_name = player['PLAYER']
            player_position = player['POSITION']
            player_normalized_positions = normalize_player_position(player_position)
            normalized_positions.extend(player_normalized_positions)  # Collect positions
            print(f"Processed {player_name} with positions {player_normalized_positions}")
    except Exception as e:
        print(f"Error processing roster for team {team_name}: {e}")

# Adjust main analysis function
def analyze_teams_for_today():
    global normalized_positions  # To accumulate across games
    normalized_positions.clear()  # Reset at the start of the day's analysis

    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            process_team_roster(team_name)

    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        return playergamelog.PlayerGameLog(player_id=player_id, season="2024-25").get_data_frames()[0]
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

# Fetch injury data
def fetch_injury_data():
    try:
        url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        injuries = {}
        for league in data.get('leagues', []):
            for team in league.get('teams', []):
                team_abbr = TEAM_NAME_TO_ABBREVIATION.get(team['team']['displayName'], None)
                if team_abbr:
                    for player in team.get('injuries', []):
                        injuries[player['athlete']['displayName']] = player.get('description', 'Unknown')
        return injuries
    except Exception as e:
        print(f"Error fetching injury data: {e}")
        return {}

# Calculate stats
def calculate_stats(stat_series):
    mean = stat_series.mean()
    std_dev = stat_series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust predictions for DvP and other factors
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data):
    try:
        positions = player_position.split("-")
        dvp_factors = [dvp_data[pos].get(opposing_metrics['TEAM_ABBREVIATION'], 1) for pos in positions if pos in dvp_data]

        dvp_factor = sum(dvp_factors) / len(dvp_factors) if dvp_factors else 1
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        return stat_mean * pace_factor * offensive_factor / defensive_factor * dvp_factor
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Main analysis for today's games
def analyze_teams_for_today():
    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []
    normalized_positions = []  # Initialize here to store all normalized positions

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            try:
                team_id = teams.find_team_by_abbreviation(team_name)['id']
                roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in roster.iterrows():
                    player_position = player['POSITION']
                    player_normalized_positions = normalize_player_position(player_position)
                    normalized_positions.extend(player_normalized_positions)  # Collect positions

                    # Process player as needed, e.g., fetching game logs
            except Exception as e:
                print(f"Error processing team roster for {team_name}: {e}")

    # Adjust for multi-position players in DvP adjustment
    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

                # Continue processing
                if home_team not in team_metrics or away_team not in team_metrics:
                        print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
                        continue

                for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
                        try:
                            # Fetch team roster here
                            team_id = teams.find_team_by_abbreviation(team_name)['id']
                            roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                            for _, player in roster.iterrows():
                                player_id = player['PLAYER_ID']
                                player_name = player['PLAYER']
                                player_position = player['POSITION']
                                usg_pct = player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A')
                                injury_status = injury_data.get(player_name, 'Healthy')

                                game_logs = fetch_player_game_logs(player_id)
                                if game_logs.empty:
                                    continue

                                mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                                mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                                mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                                adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)

                                # Add new difference columns
                                ppg_diff = mean_ppg - std_dev_ppg
                                rpg_diff = mean_rpg - std_dev_rpg
                                apg_diff = mean_apg - std_dev_apg

                                all_players_data.append({
                                    'Player': player_name,
                                    'Team': team_name,
                                    'PPG': round(mean_ppg, 2),
                                    'PPG SD': round(std_dev_ppg, 2),
                                    'PPG CV': round(cv_ppg, 2),
                                    'PPG Diff': round(ppg_diff, 2),  # Added PPG Diff
                                    'Adj PPG': round(adjusted_ppg, 2),
                                    'RPG': round(mean_rpg, 2),
                                    'RPG SD': round(std_dev_rpg, 2),
                                    'RPG CV': round(cv_rpg, 2),
                                    'RPG Diff': round(rpg_diff, 2),  # Added RPG Diff
                                    'Adj RPG': round(adjusted_rpg, 2),
                                    'APG': round(mean_apg, 2),
                                    'APG SD': round(std_dev_apg, 2),
                                    'APG CV': round(cv_apg, 2),
                                    'APG Diff': round(apg_diff, 2),  # Added APG Diff
                                    'Adj APG': round(adjusted_apg, 2),
                                    'USG%': usg_pct,
                                    'Injury Status': injury_status
                                })

# Debug: Print player data added to all_players_data
                                print(f"Added data for player: {player_name}, Team: {team_name}")

                                time.sleep(1)  # To avoid rate-limiting
                        except Exception as e:
                            print(f"Error analyzing team {team_name}: {e}")
                            continue

        df = pd.DataFrame(all_players_data)
        df = df.drop_duplicates(subset=['Player', 'Team'])
        display(df)
        return df  # This is now correctly placed within the function

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.disable_dataframe_formatter()

Requirement already satisfied: nba_api in /usr/local/lib/python3.12/dist-packages (1.11.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.10.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
No games scheduled for 2025-11-12.
No games scheduled for today.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [5]:
# Install required package
!pip install nba_api

import json
import time
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.endpoints import teamestimatedmetrics, playerestimatedmetrics
from nba_api.stats.endpoints import leaguedashteamstats, commonteamroster
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, playergamelogs
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display

# Map of team names to abbreviations
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL", "Boston Celtics": "BOS", "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA", "Chicago Bulls": "CHI", "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL", "Denver Nuggets": "DEN", "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW", "Houston Rockets": "HOU", "Indiana Pacers": "IND",
    "LA Clippers": "LAC", "Los Angeles Lakers": "LAL", "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA", "Milwaukee Bucks": "MIL", "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP", "New York Knicks": "NYK", "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL", "Philadelphia 76ers": "PHI", "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR", "Sacramento Kings": "SAC", "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR", "Utah Jazz": "UTA", "Washington Wizards": "WAS"
}

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        stats = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        ).get_data_frames()[0]

        metrics = stats[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        team_metrics = {TEAM_NAME_TO_ABBREVIATION.get(k, k): v for k, v in metrics_dict.items()}
        return team_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Initialize DvP data
def initialize_dvp_data():
    try:
        stats = leaguedashteamstats.LeagueDashTeamStats(
            measure_type_detailed_defense='Opponent',
            per_mode_detailed='PerGame',
            season="2024-25",
            season_type_all_star="Regular Season"
        ).get_data_frames()[0]

        stats['TEAM_ABBREVIATION'] = stats['TEAM_NAME'].map(TEAM_NAME_TO_ABBREVIATION)

        dvp_data = {}
        for pos in ['C', 'F', 'G']:
            column = f'OPP_PTS_{pos.upper()}'
            if column in stats.columns:
                dvp_data[pos] = stats.groupby('TEAM_ABBREVIATION')[column].mean().to_dict()

        return dvp_data
    except Exception as e:
        print(f"Error fetching DvP stats: {e}")
        return {}

# Normalize player positions
def normalize_player_position(position):
    if not position or not isinstance(position, str):
        return []

    positions = position.split("-")
    valid_positions = {'C', 'F', 'G'}
    return [pos.strip() for pos in positions if pos.strip() in valid_positions]

# Initialize globally for consistent usage across functions
normalized_positions = []  # Collect all normalized positions globally

# Process team rosters
def process_team_roster(team_name):
    global normalized_positions  # Ensure this modifies the global list
    try:
        team_id = teams.find_team_by_abbreviation(team_name)['id']
        roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

        for _, player in roster.iterrows():
            player_name = player['PLAYER']
            player_position = player['POSITION']
            player_normalized_positions = normalize_player_position(player_position)
            normalized_positions.extend(player_normalized_positions)  # Collect positions
            print(f"Processed {player_name} with positions {player_normalized_positions}")
    except Exception as e:
        print(f"Error processing roster for team {team_name}: {e}")

# Adjust main analysis function
def analyze_teams_for_today():
    global normalized_positions  # To accumulate across games
    normalized_positions.clear()  # Reset at the start of the day's analysis

    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            process_team_roster(team_name)

    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        return playergamelog.PlayerGameLog(player_id=player_id, season="2024-25").get_data_frames()[0]
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

# Fetch injury data
def fetch_injury_data():
    try:
        url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        injuries = {}
        for league in data.get('leagues', []):
            for team in league.get('teams', []):
                team_abbr = TEAM_NAME_TO_ABBREVIATION.get(team['team']['displayName'], None)
                if team_abbr:
                    for player in team.get('injuries', []):
                        injuries[player['athlete']['displayName']] = player.get('description', 'Unknown')
        return injuries
    except Exception as e:
        print(f"Error fetching injury data: {e}")
        return {}

# Calculate stats
def calculate_stats(stat_series):
    mean = stat_series.mean()
    std_dev = stat_series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust predictions for DvP and other factors
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data):
    try:
        positions = player_position.split("-")
        dvp_factors = [dvp_data[pos].get(opposing_metrics['TEAM_ABBREVIATION'], 1) for pos in positions if pos in dvp_data]

        dvp_factor = sum(dvp_factors) / len(dvp_factors) if dvp_factors else 1
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        return stat_mean * pace_factor * offensive_factor / defensive_factor * dvp_factor
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Main analysis for today's games
def analyze_teams_for_today():
    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []
    normalized_positions = []  # Initialize here to store all normalized positions

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            try:
                team_id = teams.find_team_by_abbreviation(team_name)['id']
                roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in roster.iterrows():
                    player_position = player['POSITION']
                    player_normalized_positions = normalize_player_position(player_position)
                    normalized_positions.extend(player_normalized_positions)  # Collect positions

                    # Process player as needed, e.g., fetching game logs
            except Exception as e:
                print(f"Error processing team roster for {team_name}: {e}")

    # Adjust for multi-position players in DvP adjustment
    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

                # Continue processing
                if home_team not in team_metrics or away_team not in team_metrics:
                        print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
                        continue

                for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
                        try:
                            # Fetch team roster here
                            team_id = teams.find_team_by_abbreviation(team_name)['id']
                            roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                            for _, player in roster.iterrows():
                                player_id = player['PLAYER_ID']
                                player_name = player['PLAYER']
                                player_position = player['POSITION']
                                usg_pct = player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A')
                                injury_status = injury_data.get(player_name, 'Healthy')

                                game_logs = fetch_player_game_logs(player_id)
                                if game_logs.empty:
                                    continue

                                mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                                mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                                mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                                adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)

                                # Add new difference columns
                                low = mean_ppg - std_dev_ppg
                                high = mean_ppg + std_dev_ppg
                                ppg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_rpg - std_dev_rpg
                                high = mean_rpg + std_dev_rpg
                                rpg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_apg - std_dev_apg
                                high = mean_apg + std_dev_apg
                                apg_diff = f"{low:.2f} - {high:.2f}"

                                all_players_data.append({
                                    'Player': player_name,
                                    'Team': team_name,
                                    'PPG': round(mean_ppg, 2),
                                    'PPG SD': round(std_dev_ppg, 2),
                                    'PPG CV': round(cv_ppg, 2),
                                    'PPG Diff': ppg_diff,
                                    'Adj PPG': round(adjusted_ppg, 2),
                                    'RPG': round(mean_rpg, 2),
                                    'RPG SD': round(std_dev_rpg, 2),
                                    'RPG CV': round(cv_rpg, 2),
                                    'RPG Diff': rpg_diff,
                                    'Adj RPG': round(adjusted_rpg, 2),
                                    'APG': round(mean_apg, 2),
                                    'APG SD': round(std_dev_apg, 2),
                                    'APG CV': round(cv_apg, 2),
                                    'APG Diff': apg_diff,
                                    'Adj APG': round(adjusted_apg, 2),
                                    'USG%': usg_pct,
                                    'Injury Status': injury_status
                                })

# Debug: Print player data added to all_players_data
                                print(f"Added data for player: {player_name}, Team: {team_name}")

                                time.sleep(1)  # To avoid rate-limiting
                        except Exception as e:
                            print(f"Error analyzing team {team_name}: {e}")
                            continue

        df = pd.DataFrame(all_players_data)
        df = df.drop_duplicates(subset=['Player', 'Team'])
        df.columns = [col.center(10) for col in df.columns]
        df = df.apply(lambda row: row.map(lambda x: str(x).center(10)), axis=1)
        display(df)
        return df  # This is now correctly placed within the function

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.disable_dataframe_formatter()

Requirement already satisfied: nba_api in /usr/local/lib/python3.12/dist-packages (1.11.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.10.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
No games scheduled for 2025-11-12.
No games scheduled for today.

In [ ]:
# Install required package
!pip install nba_api

import json
import time
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.endpoints import teamestimatedmetrics, playerestimatedmetrics
from nba_api.stats.endpoints import leaguedashteamstats, commonteamroster
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, playergamelogs
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display

# Map of team names to abbreviations
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL", "Boston Celtics": "BOS", "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA", "Chicago Bulls": "CHI", "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL", "Denver Nuggets": "DEN", "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW", "Houston Rockets": "HOU", "Indiana Pacers": "IND",
    "LA Clippers": "LAC", "Los Angeles Lakers": "LAL", "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA", "Milwaukee Bucks": "MIL", "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP", "New York Knicks": "NYK", "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL", "Philadelphia 76ers": "PHI", "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR", "Sacramento Kings": "SAC", "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR", "Utah Jazz": "UTA", "Washington Wizards": "WAS"
}

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        stats = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        ).get_data_frames()[0]

        metrics = stats[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        team_metrics = {TEAM_NAME_TO_ABBREVIATION.get(k, k): v for k, v in metrics_dict.items()}
        return team_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Initialize DvP data
def initialize_dvp_data():
    try:
        stats = leaguedashteamstats.LeagueDashTeamStats(
            measure_type_detailed_defense='Opponent',
            per_mode_detailed='PerGame',
            season="2024-25",
            season_type_all_star="Regular Season"
        ).get_data_frames()[0]

        stats['TEAM_ABBREVIATION'] = stats['TEAM_NAME'].map(TEAM_NAME_TO_ABBREVIATION)

        dvp_data = {}
        for pos in ['C', 'F', 'G']:
            column = f'OPP_PTS_{pos.upper()}'
            if column in stats.columns:
                dvp_data[pos] = stats.groupby('TEAM_ABBREVIATION')[column].mean().to_dict()

        return dvp_data
    except Exception as e:
        print(f"Error fetching DvP stats: {e}")
        return {}

# Normalize player positions
def normalize_player_position(position):
    if not position or not isinstance(position, str):
        return []

    positions = position.split("-")
    valid_positions = {'C', 'F', 'G'}
    return [pos.strip() for pos in positions if pos.strip() in valid_positions]

# Initialize globally for consistent usage across functions
normalized_positions = []  # Collect all normalized positions globally

# Process team rosters
def process_team_roster(team_name):
    global normalized_positions  # Ensure this modifies the global list
    try:
        team_id = teams.find_team_by_abbreviation(team_name)['id']
        roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

        for _, player in roster.iterrows():
            player_name = player['PLAYER']
            player_position = player['POSITION']
            player_normalized_positions = normalize_player_position(player_position)
            normalized_positions.extend(player_normalized_positions)  # Collect positions
            print(f"Processed {player_name} with positions {player_normalized_positions}")
    except Exception as e:
        print(f"Error processing roster for team {team_name}: {e}")

# Adjust main analysis function
def analyze_teams_for_today():
    global normalized_positions  # To accumulate across games
    normalized_positions.clear()  # Reset at the start of the day's analysis

    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            process_team_roster(team_name)

    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        return playergamelog.PlayerGameLog(player_id=player_id, season="2024-25").get_data_frames()[0]
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

import requests

# ESPN API for NBA injuries
url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"

# Fetch the data
response = requests.get(url)
injury_data = response.json()

# Dictionary to store player injury statuses
injury_status_dict = {}

# Extract and store injury details
for team in injury_data.get("injuries", []):  # Loop through teams with injury reports
    team_name = team.get("team", {}).get("displayName", "Unknown Team")

    for player in team.get("players", []):  # Loop through injured players
        athlete = player.get("athlete", {})
        player_name = athlete.get("displayName", "Unknown Player")

        # Default to Healthy unless injury info is present
        injury_status = "Healthy"
        injury_type = player.get("type", {}).get("description", "")  # Example: "Out"
        injury_details = player.get("details", {})

        # Extract injury specifics if available
        if injury_type:
            injury_status = injury_type.capitalize()  # Convert "out" to "Out"

        if "type" in injury_details and "detail" in injury_details:
            injury_desc = f"{injury_details['type']} ({injury_details['detail']})"
            injury_status += f" - {injury_desc}"  # Example: "Out - Shoulder (Surgery)"

        # Store the player's injury status
        injury_status_dict[player_name] = injury_status

# Mark all missing players as Healthy (You might need a full roster source)
# This assumes you have a complete list of NBA players somewhere (e.g., API or CSV)
# Example:
# all_nba_players = ["LeBron James", "Kevin Durant", "Stephen Curry", ...]
# for player in all_nba_players:
#     if player not in injury_status_dict:
#         injury_status_dict[player] = "Healthy"

# Print all player statuses
for player, status in injury_status_dict.items():
    print(f"{player}: {status}")

# Calculate stats
def calculate_stats(stat_series):
    mean = stat_series.mean()
    std_dev = stat_series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust predictions for DvP and other factors
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data):
    try:
        positions = player_position.split("-")
        dvp_factors = [dvp_data[pos].get(opposing_metrics['TEAM_ABBREVIATION'], 1) for pos in positions if pos in dvp_data]

        dvp_factor = sum(dvp_factors) / len(dvp_factors) if dvp_factors else 1
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        return stat_mean * pace_factor * offensive_factor / defensive_factor * dvp_factor
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Main analysis for today's games
def analyze_teams_for_today():
    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = injury_status_dict  # Store all injury statuses

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []
    normalized_positions = []  # Initialize here to store all normalized positions

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            try:
                team_id = teams.find_team_by_abbreviation(team_name)['id']
                roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in roster.iterrows():
                    player_position = player['POSITION']
                    player_normalized_positions = normalize_player_position(player_position)
                    normalized_positions.extend(player_normalized_positions)  # Collect positions

                    # Process player as needed, e.g., fetching game logs
            except Exception as e:
                print(f"Error processing team roster for {team_name}: {e}")

    # Adjust for multi-position players in DvP adjustment
    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

                # Continue processing
                if home_team not in team_metrics or away_team not in team_metrics:
                        print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
                        continue

                for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
                        try:
                            # Fetch team roster here
                            team_id = teams.find_team_by_abbreviation(team_name)['id']
                            roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                            for _, player in roster.iterrows():
                                player_id = player['PLAYER_ID']
                                player_name = player['PLAYER']
                                player_position = player['POSITION']
                                usg_pct = player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A')
                                injury_status = injury_data.get(player_name, 'Healthy')

                                game_logs = fetch_player_game_logs(player_id)
                                if game_logs.empty:
                                    continue

                                mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                                mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                                mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                                adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)

                                # Add new difference columns
                                low = mean_ppg - std_dev_ppg
                                high = mean_ppg + std_dev_ppg
                                ppg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_rpg - std_dev_rpg
                                high = mean_rpg + std_dev_rpg
                                rpg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_apg - std_dev_apg
                                high = mean_apg + std_dev_apg
                                apg_diff = f"{low:.2f} - {high:.2f}"

                                all_players_data.append({
                                    'Player': player_name,
                                    'Team': team_name,
                                    'PPG': round(mean_ppg, 2),
                                    'PPG SD': round(std_dev_ppg, 2),
                                    'PPG CV': round(cv_ppg, 2),
                                    'PPG Diff': ppg_diff,
                                    'Adj PPG': round(adjusted_ppg, 2),
                                    'RPG': round(mean_rpg, 2),
                                    'RPG SD': round(std_dev_rpg, 2),
                                    'RPG CV': round(cv_rpg, 2),
                                    'RPG Diff': rpg_diff,
                                    'Adj RPG': round(adjusted_rpg, 2),
                                    'APG': round(mean_apg, 2),
                                    'APG SD': round(std_dev_apg, 2),
                                    'APG CV': round(cv_apg, 2),
                                    'APG Diff': apg_diff,
                                    'Adj APG': round(adjusted_apg, 2),
                                    'USG%': usg_pct,
                                    'Injury Status': injury_status
                                })

# Debug: Print player data added to all_players_data
                                print(f"Added data for player: {player_name}, Team: {team_name}")

                                time.sleep(1)  # To avoid rate-limiting
                        except Exception as e:
                            print(f"Error analyzing team {team_name}: {e}")
                            continue

        df = pd.DataFrame(all_players_data)
        df = df.drop_duplicates(subset=['Player', 'Team'])
        df.columns = [col.center(10) for col in df.columns]
        df = df.apply(lambda row: row.map(lambda x: str(x).center(10)), axis=1)
        display(df)
        return df  # This is now correctly placed within the function

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.disable_dataframe_formatter()

Requirement already satisfied: nba_api in /usr/local/lib/python3.11/dist-packages (1.7.0)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.11/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.11/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.12.14)
Error processing team roster for DAL: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position G against CHA: 1
Added data for player: Miles Bridges, Team: CHA
Added data for player: LaMelo Ball, Team: CHA
Added data for player: Grant Williams, Team: CHA
Added data for player: DaQuan Jeffries, Team: CHA
Added data for player: Mark Williams, Team: CHA
Added data for player: Nick Smith Jr., Team: CHA
Added data for player: Josh Green, Team: CHA
Added data for player: Cody Martin, Team: CHA
Added data for player: Josh Okogie, Team: CHA
Added data for player: Moussa Diabate, Team: CHA
Added data for player: Isaiah Wong, Team: CHA
Added data for player: Vasilije Micić, Team: CHA
Added data for player: Tre Mann, Team: CHA
Added data for player: Brandon Miller, Team: CHA
Added data for player: KJ Simpson, Team: CHA
Added data for player: Seth Curry, Team: CHA
Added data for player: Tidjane Salaun, Team: CHA
Added data for player: Taj Gibson, Team: CHA
Added data for player: Dariq Whitehead, Team: BKN
Added data for player: D'Angelo Russell, Team: BKN
Added data for player: Cameron Johnson, Team: BKN
Added data for player: Reece Beekman, Team: BKN
Added data for player: Ziaire Williams, Team: BKN
Added data for player: Trendon Watford, Team: BKN
Added data for player: Ben Simmons, Team: BKN
Added data for player: Tosan Evbuomwan, Team: BKN
Added data for player: Tyrese Martin, Team: BKN
Added data for player: De'Anthony Melton, Team: BKN
Added data for player: Day'Ron Sharpe, Team: BKN
Added data for player: Noah Clowney, Team: BKN
Added data for player: Jalen Wilson, Team: BKN
Added data for player: Cam Thomas, Team: BKN
Added data for player: Maxwell Lewis, Team: BKN
Added data for player: Nic Claxton, Team: BKN
Added data for player: Keon Johnson, Team: BKN
DvP adjustment for position G against BKN: 1
Added data for player: Miles Bridges, Team: CHA
Added data for player: LaMelo Ball, Team: CHA
Added data for player: Grant Williams, Team: CHA
Added data for player: DaQuan Jeffries, Team: CHA
Added data for player: Mark Williams, Team: CHA
Added data for player: Nick Smith Jr., Team: CHA
Added data for player: Josh Green, Team: CHA
Added data for player: Cody Martin, Team: CHA
Added data for player: Josh Okogie, Team: CHA
Added data for player: Moussa Diabate, Team: CHA
Added data for player: Isaiah Wong, Team: CHA
Added data for player: Vasilije Micić, Team: CHA
Added data for player: Tre Mann, Team: CHA
Added data for player: Brandon Miller, Team: CHA
Added data for player: KJ Simpson, Team: CHA
Added data for player: Seth Curry, Team: CHA
Added data for player: Tidjane Salaun, Team: CHA
Added data for player: Taj Gibson, Team: CHA
Added data for player: Dariq Whitehead, Team: BKN
Added data for player: D'Angelo Russell, Team: BKN
Added data for player: Cameron Johnson, Team: BKN
Added data for player: Reece Beekman, Team: BKN
Added data for player: Ziaire Williams, Team: BKN
Added data for player: Trendon Watford, Team: BKN
Added data for player: Ben Simmons, Team: BKN
Added data for player: Tosan Evbuomwan, Team: BKN
Added data for player: Tyrese Martin, Team: BKN
Added data for player: De'Anthony Melton, Team: BKN
Added data for player: Day'Ron Sharpe, Team: BKN
Added data for player: Noah Clowney, Team: BKN
Added data for player: Jalen Wilson, Team: BKN
Added data for player: Cam Thomas, Team: BKN
Added data for player: Maxwell Lewis, Team: BKN
Added data for player: Nic Claxton, Team: BKN
Added data for player: Keon Johnson, Team: BKN
DvP adjustment for position G against IND: 1
Added data for player: Tyrese Haliburton, Team: IND
Added data for player: Bennedict Mathurin, Team: IND
Added data for player: Obi Toppin, Team: IND
Added data for player: Andrew Nembhard, Team: IND
Added data for player: Thomas Bryant, Team: IND
Added data for player: Jarace Walker, Team: IND
Added data for player: Enrique Freeman, Team: IND
Added data for player: T.J. McConnell, Team: IND
Added data for player: RayJ Dennis, Team: IND
Added data for player: Johnny Furphy, Team: IND
Added data for player: James Wiseman, Team: IND
Added data for player: James Johnson, Team: IND
Added data for player: Isaiah Jackson, Team: IND
Added data for player: Aaron Nesmith, Team: IND
Added data for player: Ben Sheppard, Team: IND
Added data for player: Quenton Jackson, Team: IND
Added data for player: Myles Turner, Team: IND
Added data for player: Pascal Siakam, Team: IND
Added data for player: Jalen Duren, Team: DET
Added data for player: Ronald Holland II, Team: DET
Added data for player: Cade Cunningham, Team: DET
Added data for player: Malik Beasley, Team: DET
Added data for player: Paul Reed, Team: DET
Added data for player: Tim Hardaway Jr., Team: DET
Added data for player: Ausar Thompson, Team: DET
Added data for player: Tobias Harris, Team: DET
Added data for player: Wendell Moore Jr., Team: DET
Added data for player: Simone Fontecchio, Team: DET
Added data for player: Jaden Ivey, Team: DET
Added data for player: Daniss Jenkins, Team: DET
Added data for player: Marcus Sasser, Team: DET
Added data for player: Isaiah Stewart, Team: DET
Added data for player: Bobi Klintman, Team: DET
DvP adjustment for position G against DET: 1
Added data for player: Tyrese Haliburton, Team: IND
Added data for player: Bennedict Mathurin, Team: IND
Added data for player: Obi Toppin, Team: IND
Added data for player: Andrew Nembhard, Team: IND
Added data for player: Thomas Bryant, Team: IND
Added data for player: Jarace Walker, Team: IND
Added data for player: Enrique Freeman, Team: IND
Added data for player: T.J. McConnell, Team: IND
Added data for player: RayJ Dennis, Team: IND
Added data for player: Johnny Furphy, Team: IND
Added data for player: James Wiseman, Team: IND
Added data for player: James Johnson, Team: IND
Added data for player: Isaiah Jackson, Team: IND
Added data for player: Aaron Nesmith, Team: IND
Added data for player: Ben Sheppard, Team: IND
Added data for player: Quenton Jackson, Team: IND
Added data for player: Myles Turner, Team: IND
Added data for player: Pascal Siakam, Team: IND
Added data for player: Jalen Duren, Team: DET
Added data for player: Ronald Holland II, Team: DET
Added data for player: Cade Cunningham, Team: DET
Added data for player: Malik Beasley, Team: DET
Added data for player: Paul Reed, Team: DET
Added data for player: Tim Hardaway Jr., Team: DET
Added data for player: Ausar Thompson, Team: DET
Added data for player: Tobias Harris, Team: DET
Added data for player: Wendell Moore Jr., Team: DET
Added data for player: Simone Fontecchio, Team: DET
Added data for player: Jaden Ivey, Team: DET
Added data for player: Daniss Jenkins, Team: DET
Added data for player: Marcus Sasser, Team: DET
Added data for player: Isaiah Stewart, Team: DET
Added data for player: Bobi Klintman, Team: DET
DvP adjustment for position G against WAS: 1
Added data for player: Bilal Coulibaly, Team: WAS
Added data for player: Tristan Vukcevic, Team: WAS
Added data for player: Johnny Davis, Team: WAS
Added data for player: Jared Butler, Team: WAS
Added data for player: Patrick Baldwin Jr., Team: WAS
Added data for player: Bub Carrington, Team: WAS
Added data for player: Justin Champagnie, Team: WAS
Added data for player: Jordan Poole, Team: WAS
Added data for player: Malcolm Brogdon, Team: WAS
Added data for player: Anthony Gill, Team: WAS
Added data for player: Jonas Valančiūnas, Team: WAS
Added data for player: Kyshawn George, Team: WAS
Added data for player: Alex Sarr, Team: WAS
Added data for player: Richaun Holmes, Team: WAS
Added data for player: Corey Kispert, Team: WAS
Added data for player: Kyle Kuzma, Team: WAS
Added data for player: Marvin Bagley III, Team: WAS
Added data for player: A.J. Lawson, Team: TOR
Added data for player: Gradey Dick, Team: TOR
Added data for player: Jonathan Mogbo, Team: TOR
Added data for player: Scottie Barnes, Team: TOR
Added data for player: Immanuel Quickley, Team: TOR
Added data for player: RJ Barrett, Team: TOR
Added data for player: Bruce Brown, Team: TOR
Added data for player: Ja'Kobe Walter, Team: TOR
Added data for player: Garrett Temple, Team: TOR
Added data for player: Jakob Poeltl, Team: TOR
Added data for player: Ulrich Chomche, Team: TOR
Added data for player: Jamal Shead, Team: TOR
Added data for player: Chris Boucher, Team: TOR
Added data for player: Ochai Agbaji, Team: TOR
Added data for player: Kelly Olynyk, Team: TOR
Added data for player: Davion Mitchell, Team: TOR
Added data for player: Jamison Battle, Team: TOR
Added data for player: Orlando Robinson, Team: TOR
DvP adjustment for position G against TOR: 1
Added data for player: Bilal Coulibaly, Team: WAS
Added data for player: Tristan Vukcevic, Team: WAS
Added data for player: Johnny Davis, Team: WAS
Added data for player: Jared Butler, Team: WAS
Added data for player: Patrick Baldwin Jr., Team: WAS
Added data for player: Bub Carrington, Team: WAS
Added data for player: Justin Champagnie, Team: WAS
Added data for player: Jordan Poole, Team: WAS
Added data for player: Malcolm Brogdon, Team: WAS
Added data for player: Anthony Gill, Team: WAS
Added data for player: Jonas Valančiūnas, Team: WAS
Added data for player: Kyshawn George, Team: WAS
Added data for player: Alex Sarr, Team: WAS
Added data for player: Richaun Holmes, Team: WAS
Added data for player: Corey Kispert, Team: WAS
Added data for player: Kyle Kuzma, Team: WAS
Added data for player: Marvin Bagley III, Team: WAS
Added data for player: A.J. Lawson, Team: TOR
Added data for player: Gradey Dick, Team: TOR
Added data for player: Jonathan Mogbo, Team: TOR
Added data for player: Scottie Barnes, Team: TOR
Added data for player: Immanuel Quickley, Team: TOR
Added data for player: RJ Barrett, Team: TOR
Added data for player: Bruce Brown, Team: TOR
Added data for player: Ja'Kobe Walter, Team: TOR
Added data for player: Garrett Temple, Team: TOR
Added data for player: Jakob Poeltl, Team: TOR
Added data for player: Ulrich Chomche, Team: TOR
Added data for player: Jamal Shead, Team: TOR
Added data for player: Chris Boucher, Team: TOR
Added data for player: Ochai Agbaji, Team: TOR
Added data for player: Kelly Olynyk, Team: TOR
Added data for player: Davion Mitchell, Team: TOR
Added data for player: Jamison Battle, Team: TOR
Added data for player: Orlando Robinson, Team: TOR
DvP adjustment for position G against BOS: 1
Added data for player: Jayson Tatum, Team: BOS
Added data for player: Jrue Holiday, Team: BOS
Added data for player: Jaylen Brown, Team: BOS
Added data for player: Kristaps Porziņģis, Team: BOS
Added data for player: Derrick White, Team: BOS
Added data for player: Payton Pritchard, Team: BOS
Added data for player: Drew Peterson, Team: BOS
Added data for player: JD Davison, Team: BOS
Added data for player: Xavier Tillman, Team: BOS
Added data for player: Jordan Walsh, Team: BOS
Added data for player: Sam Hauser, Team: BOS
Added data for player: Luke Kornet, Team: BOS
Added data for player: Al Horford, Team: BOS
Added data for player: Jaden Springer, Team: BOS
Added data for player: Baylor Scheierman, Team: BOS
Added data for player: Neemias Queta, Team: BOS
Added data for player: Coby White, Team: CHI
Added data for player: Lonzo Ball, Team: CHI
Added data for player: Josh Giddey, Team: CHI
Added data for player: Jevon Carter, Team: CHI
Added data for player: Jalen Smith, Team: CHI
Added data for player: Zach LaVine, Team: CHI
Added data for player: Nikola Vučević, Team: CHI
Added data for player: Ayo Dosunmu, Team: CHI
Added data for player: Torrey Craig, Team: CHI
Added data for player: Matas Buzelis, Team: CHI
Added data for player: Julian Phillips, Team: CHI
Added data for player: Adama Sanogo, Team: CHI
Added data for player: Talen Horton-Tucker, Team: CHI
Added data for player: Dalen Terry, Team: CHI
Added data for player: Chris Duarte, Team: CHI
Added data for player: E.J. Liddell, Team: CHI
Added data for player: Patrick Williams, Team: CHI
DvP adjustment for position G against CHI: 1
Added data for player: Jayson Tatum, Team: BOS
Added data for player: Jrue Holiday, Team: BOS
Added data for player: Jaylen Brown, Team: BOS
Added data for player: Kristaps Porziņģis, Team: BOS
Added data for player: Derrick White, Team: BOS
Added data for player: Payton Pritchard, Team: BOS
Added data for player: Drew Peterson, Team: BOS
Added data for player: JD Davison, Team: BOS
Added data for player: Xavier Tillman, Team: BOS
Added data for player: Jordan Walsh, Team: BOS
Added data for player: Sam Hauser, Team: BOS
Added data for player: Luke Kornet, Team: BOS
Added data for player: Al Horford, Team: BOS
Added data for player: Jaden Springer, Team: BOS
Added data for player: Baylor Scheierman, Team: BOS
Added data for player: Neemias Queta, Team: BOS
Added data for player: Coby White, Team: CHI
Added data for player: Lonzo Ball, Team: CHI
Added data for player: Josh Giddey, Team: CHI
Added data for player: Jevon Carter, Team: CHI
Added data for player: Jalen Smith, Team: CHI
Added data for player: Zach LaVine, Team: CHI
Added data for player: Nikola Vučević, Team: CHI
Added data for player: Ayo Dosunmu, Team: CHI
Added data for player: Torrey Craig, Team: CHI
Added data for player: Matas Buzelis, Team: CHI
Added data for player: Julian Phillips, Team: CHI
Added data for player: Adama Sanogo, Team: CHI
Added data for player: Talen Horton-Tucker, Team: CHI
Added data for player: Dalen Terry, Team: CHI
Added data for player: Chris Duarte, Team: CHI
Added data for player: E.J. Liddell, Team: CHI
Added data for player: Patrick Williams, Team: CHI
DvP adjustment for position G against MIA: 1
Added data for player: Josh Richardson, Team: MIA
Added data for player: Terry Rozier, Team: MIA
Added data for player: Nikola Jović, Team: MIA
Added data for player: Kel'el Ware, Team: MIA
Added data for player: Josh Christopher, Team: MIA
Added data for player: Pelle Larsson, Team: MIA
Added data for player: Jaime Jaquez Jr., Team: MIA
Added data for player: Dru Smith, Team: MIA
Added data for player: Bam Adebayo, Team: MIA
Added data for player: Tyler Herro, Team: MIA
Added data for player: Keshad Johnson, Team: MIA
Added data for player: Alec Burks, Team: MIA
Added data for player: Jimmy Butler, Team: MIA
Added data for player: Haywood Highsmith, Team: MIA
Added data for player: Kevin Love, Team: MIA
Added data for player: Duncan Robinson, Team: MIA
Added data for player: Max Strus, Team: CLE
Added data for player: Ty Jerome, Team: CLE
Added data for player: Caris LeVert, Team: CLE
Added data for player: Evan Mobley, Team: CLE
Added data for player: Sam Merrill, Team: CLE
Added data for player: Craig Porter Jr., Team: CLE
Added data for player: Darius Garland, Team: CLE
Added data for player: Tristan Thompson, Team: CLE
Added data for player: JT Thor, Team: CLE
Added data for player: Georges Niang, Team: CLE
Added data for player: Emoni Bates, Team: CLE
Added data for player: Jaylon Tyson, Team: CLE
Added data for player: Jarrett Allen, Team: CLE
Added data for player: Dean Wade, Team: CLE
Added data for player: Luke Travers, Team: CLE
Added data for player: Isaac Okoro, Team: CLE
Added data for player: Donovan Mitchell, Team: CLE
DvP adjustment for position G against CLE: 1
Added data for player: Josh Richardson, Team: MIA
Added data for player: Terry Rozier, Team: MIA
Added data for player: Nikola Jović, Team: MIA
Added data for player: Kel'el Ware, Team: MIA
Added data for player: Josh Christopher, Team: MIA
Added data for player: Pelle Larsson, Team: MIA
Added data for player: Jaime Jaquez Jr., Team: MIA
Added data for player: Dru Smith, Team: MIA
Added data for player: Bam Adebayo, Team: MIA
Added data for player: Tyler Herro, Team: MIA
Added data for player: Keshad Johnson, Team: MIA
Added data for player: Alec Burks, Team: MIA
Added data for player: Jimmy Butler, Team: MIA
Added data for player: Haywood Highsmith, Team: MIA
Added data for player: Kevin Love, Team: MIA
Added data for player: Duncan Robinson, Team: MIA
Added data for player: Max Strus, Team: CLE
Added data for player: Ty Jerome, Team: CLE
Added data for player: Caris LeVert, Team: CLE
Added data for player: Evan Mobley, Team: CLE
Added data for player: Sam Merrill, Team: CLE
Added data for player: Craig Porter Jr., Team: CLE
Added data for player: Darius Garland, Team: CLE
Added data for player: Tristan Thompson, Team: CLE
Added data for player: JT Thor, Team: CLE
Added data for player: Georges Niang, Team: CLE
Added data for player: Emoni Bates, Team: CLE
Added data for player: Jaylon Tyson, Team: CLE
Added data for player: Jarrett Allen, Team: CLE
Added data for player: Dean Wade, Team: CLE
Added data for player: Luke Travers, Team: CLE
Added data for player: Isaac Okoro, Team: CLE
Added data for player: Donovan Mitchell, Team: CLE
DvP adjustment for position G against NYK: 1
Added data for player: Jacob Toppin, Team: NYK
Added data for player: Cameron Payne, Team: NYK
Added data for player: Miles McBride, Team: NYK
Added data for player: Josh Hart, Team: NYK
Added data for player: Pacôme Dadiet, Team: NYK
Added data for player: Precious Achiuwa, Team: NYK
Added data for player: OG Anunoby, Team: NYK
Added data for player: Jalen Brunson, Team: NYK
Added data for player: Tyler Kolek, Team: NYK
Added data for player: Jericho Sims, Team: NYK
Added data for player: Mikal Bridges, Team: NYK
Added data for player: Karl-Anthony Towns, Team: NYK
Added data for player: Matt Ryan, Team: NYK
Added data for player: Landry Shamet, Team: NYK
Added data for player: Ariel Hukporti, Team: NYK
Added data for player: Christian Braun, Team: DEN
Added data for player: Michael Porter Jr., Team: DEN
Added data for player: Julian Strawther, Team: DEN
Added data for player: Russell Westbrook, Team: DEN
Added data for player: Hunter Tyson, Team: DEN
Added data for player: DeAndre Jordan, Team: DEN
Added data for player: Peyton Watson, Team: DEN
Added data for player: Dario Šarić, Team: DEN
Added data for player: PJ Hall, Team: DEN
Added data for player: Nikola Jokić, Team: DEN
Added data for player: Spencer Jones, Team: DEN
Added data for player: Zeke Nnaji, Team: DEN
Added data for player: Trey Alexander, Team: DEN
Added data for player: Jalen Pickett, Team: DEN
Added data for player: Jamal Murray, Team: DEN
Added data for player: Vlatko Čančar, Team: DEN
Added data for player: Aaron Gordon, Team: DEN
DvP adjustment for position G against DEN: 1
Added data for player: Jacob Toppin, Team: NYK
Added data for player: Cameron Payne, Team: NYK
Added data for player: Miles McBride, Team: NYK
Added data for player: Josh Hart, Team: NYK
Added data for player: Pacôme Dadiet, Team: NYK
Added data for player: Precious Achiuwa, Team: NYK
Added data for player: OG Anunoby, Team: NYK
Added data for player: Jalen Brunson, Team: NYK
Added data for player: Tyler Kolek, Team: NYK
Added data for player: Jericho Sims, Team: NYK
Added data for player: Mikal Bridges, Team: NYK
Added data for player: Karl-Anthony Towns, Team: NYK
Added data for player: Matt Ryan, Team: NYK
Added data for player: Landry Shamet, Team: NYK

                    Player       Team        PPG        PPG SD      PPG CV        PPG Diff    Adj PPG       RPG        RPG SD      RPG CV        RPG Diff    Adj RPG       APG        APG SD      APG CV       APG Diff    Adj APG       USG%    Injury Status
0              Miles Bridges     CHA         18.9        6.22        0.33     12.67 - 25.12    17.37        7.34        2.47        0.34       4.88 - 9.81     6.75        3.66        1.9         0.52      1.76 - 5.55     3.36       0.254        Healthy
1                LaMelo Ball     CHA        28.16        8.84        0.31     19.32 - 37.00    25.89        5.26        2.68        0.51       2.58 - 7.94     4.83        7.29        2.78        0.38     4.51 - 10.07     6.7        0.365        Healthy
2             Grant Williams     CHA        10.38        4.43        0.43      5.95 - 14.80     9.54        5.12        2.39        0.47       2.73 - 7.52     4.71        2.31        1.54        0.66      0.78 - 3.85     2.13       0.147        Healthy
3            DaQuan Jeffries     CHA         6.42        4.68        0.73      1.74 - 11.10     5.9         3.33        2.23        0.67       1.10 - 5.56     3.06        0.83        0.94        1.12     -0.10 - 1.77     0.77        0.15        Healthy
4              Mark Williams     CHA        15.45        8.2         0.53      7.25 - 23.65     14.2        9.35        3.95        0.42      5.40 - 13.30     8.59        2.5         1.43        0.57      1.07 - 3.93     2.3        0.223        Healthy
5             Nick Smith Jr.     CHA         6.0         5.77        0.96      0.23 - 11.77     5.52        1.68        1.68        1.0        0.00 - 3.36     1.54        1.56        1.78        1.14     -0.22 - 3.34     1.43       0.198        Healthy
6                 Josh Green     CHA         7.44        5.16        0.69      2.28 - 12.60     6.84        2.85        1.68        0.59       1.17 - 4.54     2.62        1.44        1.25        0.87      0.19 - 2.68     1.32       0.113        Healthy
7                Cody Martin     CHA         7.85        4.63        0.59      3.21 - 12.48     7.21        4.51        1.99        0.44       2.53 - 6.50     4.15        2.28        1.67        0.73      0.61 - 3.95     2.1        0.143        Healthy
8                Josh Okogie     CHA         6.77        5.92        0.87      0.85 - 12.68     6.22        3.07        2.86        0.93       0.20 - 5.93     2.82        0.73        0.98        1.34     -0.25 - 1.71     0.67        0.18        Healthy
9             Moussa Diabate     CHA         3.81        3.79        1.0        0.01 - 7.60     3.5         6.53        4.27        0.65      2.26 - 10.79     6.0         0.67        0.93        1.39     -0.26 - 1.59     0.61       0.095        Healthy
10               Isaiah Wong     CHA         5.64        3.56        0.63       2.08 - 9.21     5.19        1.79        1.63        0.91       0.16 - 3.41     1.64        1.43        1.55        1.09     -0.13 - 2.98     1.31       0.229        Healthy
11            Vasilije Micić     CHA         6.91        5.68        0.82      1.23 - 12.58     6.35        2.25        2.0         0.89       0.25 - 4.25     2.07        3.44        2.8         0.82      0.63 - 6.24     3.16       0.205        Healthy
12                 Tre Mann      CHA        14.08        7.57        0.54      6.51 - 21.64    12.94        2.92        1.71        0.58       1.22 - 4.63     2.69        3.0         2.2         0.73      0.80 - 5.20     2.76       0.261        Healthy
13            Brandon Miller     CHA        21.04        8.11        0.39     12.93 - 29.14    19.34        4.85        2.41        0.5        2.44 - 7.27     4.46        3.63        1.94        0.54      1.69 - 5.57     3.34       0.275        Healthy
14                KJ Simpson     CHA         4.46        3.73        0.84       0.73 - 8.19     4.1         2.0         1.87        0.94       0.13 - 3.87     1.84        1.62        2.36        1.46     -0.75 - 3.98     1.48        0.19        Healthy
15                Seth Curry     CHA         5.47        5.6         1.02     -0.13 - 11.08     5.03        1.39        1.38        0.99       0.01 - 2.77     1.28        0.53        0.81        1.54     -0.28 - 1.34     0.49       0.146        Healthy
16            Tidjane Salaun     CHA         4.68        4.33        0.93       0.34 - 9.01     4.3         4.09        2.96        0.72       1.13 - 7.05     3.76        1.09        1.03        0.94      0.06 - 2.11     1.0        0.144        Healthy
17                Taj Gibson     CHA         2.44        2.38        0.97       0.06 - 4.83     2.25        2.83        2.09        0.74       0.74 - 4.93     2.6         0.5         0.92        1.85     -0.42 - 1.42     0.46       0.125        Healthy
18           Dariq Whitehead     BKN         4.5         6.8         1.51     -2.30 - 11.30     4.18        0.62        0.92        1.47      -0.29 - 1.54     0.58        0.12        0.35        2.83     -0.23 - 0.48     0.12       0.213        Healthy
19          D'Angelo Russell     BKN        13.21        5.98        0.45      7.23 - 19.19    12.26        2.79        1.83        0.66       0.96 - 4.62     2.59        5.34        2.89        0.54      2.45 - 8.23     4.96       0.227        Healthy
20           Cameron Johnson     BKN         19.4        7.52        0.39     11.88 - 26.92     18.0        4.06        2.36        0.58       1.69 - 6.42     3.77        2.94        1.64        0.56      1.30 - 4.59     2.73       0.226        Healthy
21             Reece Beekman     BKN         2.35        2.74        1.16      -0.38 - 5.09     2.18        0.76        1.15        1.5       -0.38 - 1.91     0.71        1.35        1.41        1.04     -0.06 - 2.76     1.26       0.134        Healthy
22           Ziaire Williams     BKN         9.18        5.99        0.65      3.19 - 15.17     8.52        4.61        2.69        0.58       1.91 - 7.30     4.27        1.39        1.27        0.91      0.12 - 2.67     1.29       0.193        Healthy
23           Trendon Watford     BKN         8.31        4.96        0.6       3.35 - 13.26     7.71        2.77        1.42        0.51       1.35 - 4.19     2.57        1.15        1.07        0.93      0.09 - 2.22     1.07       0.236        Healthy
24               Ben Simmons     BKN         6.27        4.16        0.66      2.11 - 10.43     5.82        5.33        2.01        0.38       3.33 - 7.34     4.95        7.1         2.52        0.36      4.58 - 9.62     6.59       0.146        Healthy
25           Tosan Evbuomwan     BKN         9.62        5.55        0.58      4.07 - 15.16     8.92        4.31        2.25        0.52       2.06 - 6.56     4.0         1.38        0.51        0.37      0.88 - 1.89     1.29       0.197        Healthy
26             Tyrese Martin     BKN         8.13        6.84        0.84      1.29 - 14.97     7.54        3.9         2.59        0.66       1.32 - 6.49     3.62        1.77        1.26        0.71      0.52 - 3.03     1.65       0.185        Healthy
27         De'Anthony Melton     BKN        10.33        6.35        0.61      3.99 - 16.68     9.59        3.33        3.44        1.03      -0.11 - 6.78     3.09        2.83        1.6         0.57      1.23 - 4.44     2.63       0.231        Healthy
28            Day'Ron Sharpe     BKN         7.8         4.0         0.51      3.80 - 11.80     7.24        6.32        3.2         0.51       3.12 - 9.52     5.87        1.4         1.32        0.94      0.08 - 2.72     1.3        0.199        Healthy
29              Noah Clowney     BKN         9.43        6.42        0.68      3.01 - 15.86     8.75        3.92        1.82        0.46       2.10 - 5.74     3.64        0.81        0.81        1.0      -0.00 - 1.62     0.75       0.185        Healthy
30              Jalen Wilson     BKN         9.41        4.76        0.51      4.65 - 14.17     8.74        3.48        2.0         0.57       1.48 - 5.48     3.23        1.93        1.53        0.79      0.41 - 3.46     1.8        0.166        Healthy
31                Cam Thomas     BKN        24.68        8.08        0.33     16.60 - 32.77    22.91        3.58        1.98        0.55       1.60 - 5.56     3.32        3.37        1.8         0.53      1.57 - 5.17     3.13       0.326        Healthy
32             Maxwell Lewis     BKN         0.88        1.64        1.88      -0.77 - 2.52     0.81        0.25        0.46        1.85      -0.21 - 0.71     0.23        0.25        0.71        2.83     -0.46 - 0.96     0.23       0.136        Healthy
33               Nic Claxton     BKN         9.65        4.27        0.44      5.38 - 13.92     8.96        7.6         2.64        0.35      4.96 - 10.24     7.05        2.02        1.35        0.67      0.68 - 3.37     1.88       0.169        Healthy
34              Keon Johnson     BKN         9.18        6.36        0.69      2.81 - 15.54     8.52        3.18        2.26        0.71       0.92 - 5.44     2.95        1.78        1.64        0.92      0.14 - 3.41     1.65       0.212        Healthy
70         Tyrese Haliburton     IND         18.0        8.87        0.49      9.13 - 26.87    18.43        3.57        1.92        0.54       1.65 - 5.49     3.65        8.66        3.0         0.35     5.66 - 11.66     8.87       0.215        Healthy
71        Bennedict Mathurin     IND        16.41        7.1         0.43      9.31 - 23.51     16.8        5.91        3.09        0.52       2.82 - 9.00     6.05        1.89        1.24        0.66      0.64 - 3.13     1.93       0.219        Healthy
72                Obi Toppin     IND        10.02        5.25        0.52      4.77 - 15.28    10.27        3.98        2.1         0.53       1.88 - 6.08     4.07        1.64        1.27        0.77      0.38 - 2.91     1.68       0.185        Healthy
73           Andrew Nembhard     IND        10.63        5.22        0.49      5.42 - 15.85    10.89        3.47        2.32        0.67       1.15 - 5.78     3.55        5.2         2.19        0.42      3.01 - 7.39     5.33       0.176        Healthy
74             Thomas Bryant     IND         6.0         4.77        0.79      1.23 - 10.77     6.14        3.62        2.16        0.6        1.46 - 5.78     3.71        0.66        0.81        1.24     -0.16 - 1.47     0.67       0.156        Healthy
75             Jarace Walker     IND         6.31        4.55        0.72      1.76 - 10.86     6.46        3.31        2.61        0.79       0.70 - 5.92     3.39        1.47        1.41        0.96      0.06 - 2.87     1.5        0.167        Healthy
76           Enrique Freeman     IND         1.78        1.9         1.07      -0.12 - 3.67     1.82        1.0         1.28        1.28      -0.28 - 2.28     1.02        0.39        0.61        1.56     -0.22 - 1.00     0.4        0.106        Healthy
77            T.J. McConnell     IND        10.07        5.0         0.5       5.07 - 15.07    10.31        2.57        1.69        0.66       0.88 - 4.26     2.63        4.45        2.14        0.48      2.31 - 6.59     4.56        0.24        Healthy
78               RayJ Dennis     IND         0.4         0.89        2.24      -0.49 - 1.29     0.41        0.6         0.89        1.49      -0.29 - 1.49     0.61        0.2         0.45        2.24     -0.25 - 0.65     0.2        0.236        Healthy
79             Johnny Furphy     IND         2.07        2.91        1.41      -0.85 - 4.98     2.12        1.1         1.58        1.44      -0.48 - 2.68     1.13        0.3         0.6         1.99     -0.30 - 0.90     0.31       0.128        Healthy
80             James Wiseman     IND         6.0         nan         nan         nan - nan      6.14        1.0         nan         nan         nan - nan      1.02        0.0         nan         0.0        nan - nan      0.0        0.454        Healthy
81             James Johnson     IND         1.0         1.51        1.51      -0.51 - 2.51     1.02        0.5         0.93        1.85      -0.43 - 1.43     0.51        0.38        0.52        1.38     -0.14 - 0.89     0.38       0.195        Healthy
82            Isaiah Jackson     IND         7.0         3.32        0.47      3.68 - 10.32     7.17        5.6         3.13        0.56       2.47 - 8.73     5.74        1.0         1.0         1.0       0.00 - 2.00     1.02       0.166        Healthy
83             Aaron Nesmith     IND         8.8         3.22        0.37      5.58 - 12.02     9.01        3.5         2.46        0.7        1.04 - 5.96     3.58        0.9         0.99        1.1      -0.09 - 1.89     0.92       0.167        Healthy
84              Ben Sheppard     IND         5.29        4.4         0.83       0.89 - 9.69     5.42        2.48        1.77        0.71       0.72 - 4.25     2.54        1.03        1.08        1.05     -0.05 - 2.11     1.06       0.113        Healthy
85           Quenton Jackson     IND         5.67        6.08        1.07     -0.41 - 11.74     5.8         1.5         1.38        0.92       0.12 - 2.88     1.54        1.72        1.49        0.86      0.23 - 3.21     1.76       0.164        Healthy
86              Myles Turner     IND        15.38        5.93        0.39      9.45 - 21.32    15.75        6.83        2.67        0.39       4.17 - 9.50     7.0         1.5         1.02        0.68      0.48 - 2.52     1.54       0.211        Healthy
87             Pascal Siakam     IND        20.16        4.79        0.24     15.36 - 24.95    20.64        7.36        2.76        0.38      4.59 - 10.12     7.53        3.44        2.04        0.59      1.40 - 5.48     3.53       0.234        Healthy
88               Jalen Duren     DET        10.14        4.35        0.43      5.79 - 14.49     9.83        9.86        4.25        0.43      5.61 - 14.11     9.56        2.23        1.36        0.61      0.87 - 3.59     2.17       0.155        Healthy
89         Ronald Holland II     DET         6.37        4.64        0.73      1.73 - 11.01     6.18        2.85        1.79        0.63       1.06 - 4.64     2.76        0.78        0.81        1.04     -0.03 - 1.60     0.76       0.183        Healthy
90           Cade Cunningham     DET        24.79        6.46        0.26     18.33 - 31.24    24.04        6.4         2.51        0.39       3.90 - 8.91     6.21        9.36        3.1         0.33     6.26 - 12.46     9.08       0.326        Healthy
91             Malik Beasley     DET        16.28        7.12        0.44      9.17 - 23.40    15.79        2.96        1.85        0.63       1.11 - 4.81     2.87        1.8         1.45        0.81      0.35 - 3.26     1.75       0.227        Healthy
92                Paul Reed      DET         4.32        3.68        0.85       0.64 - 8.00     4.19        2.08        2.23        1.07      -0.15 - 4.31     2.02        1.0         1.19        1.19     -0.19 - 2.19     0.97       0.169        Healthy
93          Tim Hardaway Jr.     DET        11.05        6.21        0.56      4.84 - 17.26    10.72        2.17        1.61        0.74       0.56 - 3.77     2.1         1.55        1.11        0.72      0.44 - 2.66     1.5        0.153        Healthy
94            Ausar Thompson     DET         8.08        4.4         0.54      3.68 - 12.49     7.84        4.79        2.59        0.54       2.20 - 7.38     4.65        1.62        1.44        0.89      0.19 - 3.06     1.58        0.19        Healthy
95             Tobias Harris     DET        12.59        6.02        0.48      6.57 - 18.61    12.21        6.11        3.02        0.49       3.09 - 9.13     5.93        2.43        1.3         0.54      1.13 - 3.73     2.36       0.171        Healthy
96         Wendell Moore Jr.     DET         3.5         3.67        1.05      -0.17 - 7.17     3.39        2.44        2.57        1.05      -0.13 - 5.02     2.37        1.22        1.4         1.14     -0.17 - 2.62     1.19       0.131        Healthy
97         Simone Fontecchio     DET         6.39        4.42        0.69      1.98 - 10.81     6.2         2.93        2.0         0.68       0.92 - 4.93     2.84        0.88        0.93        1.06     -0.05 - 1.81     0.85       0.157        Healthy
98                Jaden Ivey     DET         17.6        5.49        0.31     12.11 - 23.09    17.07        4.13        1.98        0.48       2.16 - 6.11     4.01        3.97        2.2         0.56      1.76 - 6.17     3.85       0.263        Healthy
99            Daniss Jenkins     DET         0.0         0.0         0.0        0.00 - 0.00     0.0         0.0         0.0         0.0        0.00 - 0.00     0.0         0.0         0.0         0.0       0.00 - 0.00     0.0        0.304        Healthy
100            Marcus Sasser     DET         6.03        5.07        0.84      0.96 - 11.10     5.85        1.2         1.37        1.14      -0.17 - 2.57     1.16        2.11        1.64        0.78      0.47 - 3.76     2.05       0.182        Healthy
101           Isaiah Stewart     DET         5.55        3.58        0.65       1.96 - 9.13     5.38        5.95        3.19        0.54       2.76 - 9.14     5.77        1.74        1.5         0.86      0.24 - 3.24     1.69       0.119        Healthy
102            Bobi Klintman     DET         0.0         nan         0.0         nan - nan      0.0         2.0         nan         nan         nan - nan      1.94        0.0         nan         0.0        nan - nan      0.0         0.0         Healthy
136          Bilal Coulibaly     WAS        12.41        6.75        0.54      5.67 - 19.16    11.52        5.07        2.26        0.45       2.81 - 7.34     4.71        3.41        1.94        0.57      1.48 - 5.35     3.17       0.177        Healthy
137         Tristan Vukcevic     WAS         1.71        3.73        2.18      -2.01 - 5.44     1.59        0.57        0.79        1.38      -0.22 - 1.36     0.53        0.14        0.38        2.65     -0.24 - 0.52     0.13       0.276        Healthy
138             Johnny Davis     WAS         2.52        2.83        1.12      -0.31 - 5.34     2.33        1.13        1.61        1.42      -0.48 - 2.74     1.05        0.32        0.54        1.68     -0.22 - 0.86     0.3        0.154        Healthy
139             Jared Butler     WAS         6.84        5.91        0.86      0.93 - 12.75     6.34        1.32        1.74        1.32      -0.42 - 3.06     1.23        2.55        2.06        0.81      0.49 - 4.61     2.36       0.253        Healthy
140      Patrick Baldwin Jr.     WAS         2.2         2.07        0.94       0.13 - 4.27     2.04        0.85        1.18        1.39      -0.33 - 2.03     0.79        0.05        0.22        4.47     -0.17 - 0.27     0.05       0.152        Healthy
141           Bub Carrington     WAS         8.91        4.71        0.53      4.20 - 13.62     8.27        4.13        2.4         0.58       1.73 - 6.53     3.83        3.84        2.04        0.53      1.80 - 5.89     3.57       0.144        Healthy
142        Justin Champagnie     WAS         7.96        7.64        0.96      0.32 - 15.60     7.39        4.85        3.49        0.72       1.36 - 8.35     4.5         1.04        1.22        1.18     -0.19 - 2.26     0.96       0.151        Healthy
143             Jordan Poole     WAS        21.21        8.56        0.4      12.65 - 29.77    19.68        3.08        1.94        0.63       1.14 - 5.02     2.86        4.97        2.32        0.47      2.65 - 7.29     4.61       0.285        Healthy
144          Malcolm Brogdon     WAS        13.83        7.44        0.54      6.40 - 21.27    12.83        4.06        2.94        0.72       1.12 - 7.00     3.76        3.94        2.26        0.57      1.68 - 6.21     3.66       0.243        Healthy
145             Anthony Gill     WAS         1.94        2.24        1.16      -0.30 - 4.18     1.8         0.88        1.31        1.5       -0.44 - 2.19     0.81        0.22        0.49        2.24     -0.27 - 0.71     0.2         0.13        Healthy

In [ ]:
import requests

# API URL for NBA injury data
url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"

# Send a GET request to the API
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()

    # Print player name and status for each injury
    for team in data.get('injuries', []):
        for injury in team.get('injuries', []):
            player_name = injury.get('athlete', {}).get('displayName', 'Unknown Player')
            status = injury.get('status', 'Unknown Status')
            print(f"Player: {player_name}, Status: {status}")
else:
    print("Failed to retrieve injury data.")

Player: Bogdan Bogdanovic, Status: Out
Player: Clint Capela, Status: Out
Player: Trae Young, Status: Day-To-Day
Player: Jalen Johnson, Status: Out
Player: Cody Zeller, Status: Out
Player: Kobe Bufkin, Status: Out
Player: Sam Hauser, Status: Out
Player: Al Horford, Status: Out
Player: Tyrese Martin, Status: Out
Player: Noah Clowney, Status: Out
Player: Cam Thomas, Status: Out
Player: Cameron Johnson, Status: Out
Player: Bojan Bogdanovic, Status: Out
Player: Maxwell Lewis, Status: Out
Player: Torrey Craig, Status: Out
Player: Zach LaVine, Status: Out
Player: Sam Merrill, Status: Out
Player: Darius Garland, Status: Out
Player: Caris LeVert, Status: Out
Player: Isaac Okoro, Status: Out
Player: Dean Wade, Status: Out
Player: Luke Travers, Status: Out
Player: Dante Exum, Status: Out
Player: Dwight Powell, Status: Out
Player: Maxi Kleber, Status: Out
Player: Dereck Lively II, Status: Out
Player: Luka Doncic, Status: Out
Player: Vlatko Cancar, Status: Out
Player: DaRon Holmes II, Status: Out
Player: Tolu Smith, Status: Day-To-Day
Player: Jaden Ivey, Status: Out
Player: Stephen Curry, Status: Day-To-Day
Player: Draymond Green, Status: Out
Player: Jonathan Kuminga, Status: Out
Player: Alperen Sengun, Status: Day-To-Day
Player: Steven Adams, Status: Day-To-Day
Player: Jabari Smith Jr., Status: Out
Player: Bennedict Mathurin, Status: Out
Player: Andrew Nembhard, Status: Out
Player: Isaiah Jackson, Status: Out
Player: James Wiseman, Status: Out
Player: Kris Dunn, Status: Out
Player: Cam Christie, Status: Out
Player: P.J. Tucker, Status: Out
Player: Jalen Hood-Schifino, Status: Out
Player: Gabe Vincent, Status: Day-To-Day
Player: Dorian Finney-Smith, Status: Day-To-Day
Player: LeBron James, Status: Day-To-Day
Player: Rui Hachimura, Status: Day-To-Day
Player: Anthony Davis, Status: Out
Player: Christian Wood, Status: Out
Player: Vince Williams Jr., Status: Out
Player: Marcus Smart, Status: Out
Player: Cam Spencer, Status: Out
Player: Isaiah Stevens, Status: Out
Player: Josh Richardson, Status: Out
Player: Jimmy Butler, Status: Suspension
Player: Dru Smith, Status: Out
Player: Liam Robbins, Status: Day-To-Day
Player: Tyler Smith, Status: Day-To-Day
Player: AJ Green, Status: Out
Player: Bobby Portis, Status: Out
Player: Naz Reid, Status: Day-To-Day
Player: Rob Dillingham, Status: Day-To-Day
Player: Jesse Edwards, Status: Out
Player: Donte DiVincenzo, Status: Out
Player: Terrence Shannon Jr., Status: Out
Player: Jordan Hawkins, Status: Out
Player: Brandon Ingram, Status: Out
Player: Herbert Jones, Status: Out
Player: Josh Hart, Status: Day-To-Day
Player: Pacome Dadiet, Status: Out
Player: Mitchell Robinson, Status: Out
Player: Kevin McCullar Jr., Status: Out
Player: Chet Holmgren, Status: Out
Player: Nikola Topic, Status: Out
Player: Ajay Mitchell, Status: Out
Player: Gary Harris, Status: Out
Player: Jalen Suggs, Status: Day-To-Day
Player: Moritz Wagner, Status: Out
Player: Caleb Martin, Status: Out
Player: KJ Martin, Status: Out
Player: Andre Drummond, Status: Out
Player: Paul George, Status: Out
Player: Joel Embiid, Status: Out
Player: Jared McCain, Status: Out
Player: Kevin Durant, Status: Day-To-Day
Player: Ryan Dunn, Status: Day-To-Day
Player: Jerami Grant, Status: Day-To-Day
Player: Matisse Thybulle, Status: Out
Player: Doug McDermott, Status: Out
Player: Sidy Cissoko, Status: Out
Player: Riley Minix, Status: Out
Player: Gradey Dick, Status: Out
Player: Kelly Olynyk, Status: Out
Player: Immanuel Quickley, Status: Out
Player: Cody Williams, Status: Out
Player: Lauri Markkanen, Status: Day-To-Day
Player: Jordan Clarkson, Status: Day-To-Day
Player: Walker Kessler, Status: Day-To-Day
Player: John Collins, Status: Out
Player: Johnny Juzang, Status: Out
Player: Taylor Hendricks, Status: Out
Player: Alex Sarr, Status: Out
Player: Malcolm Brogdon, Status: Out
Player: Marvin Bagley III, Status: Out
Player: Saddiq Bey, Status: Out

In [ ]:
# Install required package
!pip install nba_api

import json
import time
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.endpoints import teamestimatedmetrics, playerestimatedmetrics
from nba_api.stats.endpoints import leaguedashteamstats, commonteamroster
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, playergamelogs
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display

# Map of team names to abbreviations
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL", "Boston Celtics": "BOS", "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA", "Chicago Bulls": "CHI", "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL", "Denver Nuggets": "DEN", "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW", "Houston Rockets": "HOU", "Indiana Pacers": "IND",
    "LA Clippers": "LAC", "Los Angeles Lakers": "LAL", "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA", "Milwaukee Bucks": "MIL", "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP", "New York Knicks": "NYK", "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL", "Philadelphia 76ers": "PHI", "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR", "Sacramento Kings": "SAC", "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR", "Utah Jazz": "UTA", "Washington Wizards": "WAS"
}

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        stats = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        ).get_data_frames()[0]

        metrics = stats[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        team_metrics = {TEAM_NAME_TO_ABBREVIATION.get(k, k): v for k, v in metrics_dict.items()}
        return team_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Initialize DvP data
def initialize_dvp_data():
    try:
        stats = leaguedashteamstats.LeagueDashTeamStats(
            measure_type_detailed_defense='Opponent',
            per_mode_detailed='PerGame',
            season="2024-25",
            season_type_all_star="Regular Season"
        ).get_data_frames()[0]

        stats['TEAM_ABBREVIATION'] = stats['TEAM_NAME'].map(TEAM_NAME_TO_ABBREVIATION)

        dvp_data = {}
        for pos in ['C', 'F', 'G']:
            column = f'OPP_PTS_{pos.upper()}'
            if column in stats.columns:
                dvp_data[pos] = stats.groupby('TEAM_ABBREVIATION')[column].mean().to_dict()

        return dvp_data
    except Exception as e:
        print(f"Error fetching DvP stats: {e}")
        return {}

# Normalize player positions
def normalize_player_position(position):
    if not position or not isinstance(position, str):
        return []

    positions = position.split("-")
    valid_positions = {'C', 'F', 'G'}
    return [pos.strip() for pos in positions if pos.strip() in valid_positions]

# Initialize globally for consistent usage across functions
normalized_positions = []  # Collect all normalized positions globally

# Process team rosters
def process_team_roster(team_name):
    global normalized_positions  # Ensure this modifies the global list
    try:
        team_id = teams.find_team_by_abbreviation(team_name)['id']
        roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

        for _, player in roster.iterrows():
            player_name = player['PLAYER']
            player_position = player['POSITION']
            player_normalized_positions = normalize_player_position(player_position)
            normalized_positions.extend(player_normalized_positions)  # Collect positions
            print(f"Processed {player_name} with positions {player_normalized_positions}")
    except Exception as e:
        print(f"Error processing roster for team {team_name}: {e}")

# Adjust main analysis function
def analyze_teams_for_today():
    global normalized_positions  # To accumulate across games
    normalized_positions.clear()  # Reset at the start of the day's analysis

    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            process_team_roster(team_name)

    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        return playergamelog.PlayerGameLog(player_id=player_id, season="2024-25").get_data_frames()[0]
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

def fetch_injury_data():
    url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        injury_status_dict = {}  # Store injuries in {player_name: status} format

        for team in data.get('injuries', []):
            for injury in team.get('injuries', []):
                player_name = injury.get('athlete', {}).get('displayName', 'Unknown Player')
                status = injury.get('status', 'Healthy')  # Default to 'Healthy'
                injury_status_dict[player_name] = status

        return injury_status_dict
    except Exception as e:
        print(f"Error fetching injury data: {e}")
        return {}

# Calculate stats
def calculate_stats(stat_series):
    mean = stat_series.mean()
    std_dev = stat_series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust predictions for DvP and other factors
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data):
    try:
        positions = player_position.split("-")
        dvp_factors = [dvp_data[pos].get(opposing_metrics['TEAM_ABBREVIATION'], 1) for pos in positions if pos in dvp_data]

        dvp_factor = sum(dvp_factors) / len(dvp_factors) if dvp_factors else 1
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        return stat_mean * pace_factor * offensive_factor / defensive_factor * dvp_factor
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Main analysis for today's games
def analyze_teams_for_today():
    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_status_dict = fetch_injury_data()  # Assuming this function fetches injury data
    injury_data = injury_status_dict  # Store all injury statuses

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []
    normalized_positions = []  # Initialize here to store all normalized positions

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            try:
                team_id = teams.find_team_by_abbreviation(team_name)['id']
                roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in roster.iterrows():
                    player_position = player['POSITION']
                    player_normalized_positions = normalize_player_position(player_position)
                    normalized_positions.extend(player_normalized_positions)  # Collect positions

                    # Process player as needed, e.g., fetching game logs
            except Exception as e:
                print(f"Error processing team roster for {team_name}: {e}")

    # Adjust for multi-position players in DvP adjustment
    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

                # Continue processing
                if home_team not in team_metrics or away_team not in team_metrics:
                        print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
                        continue

                for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
                        try:
                            # Fetch team roster here
                            team_id = teams.find_team_by_abbreviation(team_name)['id']
                            roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                            # Fetch injury data once to use throughout the script
                            injury_data = fetch_injury_data()

                            for _, player in roster.iterrows():
                                player_id = player['PLAYER_ID']
                                player_name = player['PLAYER']
                                player_position = player['POSITION']
                                usg_pct = player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A')
                                injury_status = injury_data.get(player_name, 'Healthy')

                                game_logs = fetch_player_game_logs(player_id)
                                if game_logs.empty:
                                    continue

                                mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                                mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                                mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                                adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)

                                # Add new difference columns
                                low = mean_ppg - std_dev_ppg
                                high = mean_ppg + std_dev_ppg
                                ppg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_rpg - std_dev_rpg
                                high = mean_rpg + std_dev_rpg
                                rpg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_apg - std_dev_apg
                                high = mean_apg + std_dev_apg
                                apg_diff = f"{low:.2f} - {high:.2f}"

                                all_players_data.append({
                                    'Player': player_name,
                                    'Position': player_normalized_positions,
                                    'Team': team_name,
                                    'PPG': round(mean_ppg, 2),
                                    'PPG SD': round(std_dev_ppg, 2),
                                    'PPG CV': round(cv_ppg, 2),
                                    'PPG Diff': ppg_diff,
                                    'Adj PPG': round(adjusted_ppg, 2),
                                    'RPG': round(mean_rpg, 2),
                                    'RPG SD': round(std_dev_rpg, 2),
                                    'RPG CV': round(cv_rpg, 2),
                                    'RPG Diff': rpg_diff,
                                    'Adj RPG': round(adjusted_rpg, 2),
                                    'APG': round(mean_apg, 2),
                                    'APG SD': round(std_dev_apg, 2),
                                    'APG CV': round(cv_apg, 2),
                                    'APG Diff': apg_diff,
                                    'Adj APG': round(adjusted_apg, 2),
                                    'USG%': usg_pct,
                                    'Injury Status': injury_status
                                })

# Debug: Print player data added to all_players_data
                                print(f"Added data for player: {player_name}, Team: {team_name}")

                                time.sleep(1)  # To avoid rate-limiting
                        except Exception as e:
                            print(f"Error analyzing team {team_name}: {e}")
                            continue

        df = pd.DataFrame(all_players_data)
        df = df.drop_duplicates(subset=['Player', 'Team'])
        df.columns = [col.center(10) for col in df.columns]
        df = df.apply(lambda row: row.map(lambda x: str(x).center(10)), axis=1)
        display(df)
        return df  # This is now correctly placed within the function

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.disable_dataframe_formatter()

Requirement already satisfied: nba_api in /usr/local/lib/python3.11/dist-packages (1.7.0)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.11/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.11/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.12.14)
DvP adjustment for position C against WAS: 1
Added data for player: Bilal Coulibaly, Team: WAS
Added data for player: Tristan Vukcevic, Team: WAS
Added data for player: Johnny Davis, Team: WAS
Added data for player: Jared Butler, Team: WAS
Added data for player: Patrick Baldwin Jr., Team: WAS
Added data for player: Bub Carrington, Team: WAS
Added data for player: Justin Champagnie, Team: WAS
Added data for player: Jordan Poole, Team: WAS
Added data for player: Malcolm Brogdon, Team: WAS
Added data for player: Anthony Gill, Team: WAS
Added data for player: Jonas Valančiūnas, Team: WAS
Added data for player: Kyshawn George, Team: WAS
Added data for player: Alex Sarr, Team: WAS
Added data for player: Richaun Holmes, Team: WAS
Added data for player: Corey Kispert, Team: WAS
Added data for player: Kyle Kuzma, Team: WAS
Added data for player: Marvin Bagley III, Team: WAS
Added data for player: Jalen Hood-Schifino, Team: LAL
Added data for player: Jarred Vanderbilt, Team: LAL
Added data for player: Anthony Davis, Team: LAL
Added data for player: Dalton Knecht, Team: LAL
Added data for player: Cam Reddish, Team: LAL
Added data for player: Gabe Vincent, Team: LAL
Added data for player: Bronny James, Team: LAL
Added data for player: Christian Koloko, Team: LAL
Added data for player: Jaxson Hayes, Team: LAL
Added data for player: Max Christie, Team: LAL
Added data for player: Austin Reaves, Team: LAL
Added data for player: Dorian Finney-Smith, Team: LAL
Added data for player: Shake Milton, Team: LAL
Added data for player: LeBron James, Team: LAL
Added data for player: Rui Hachimura, Team: LAL
Added data for player: Trey Jemison III, Team: LAL
Added data for player: Armel Traoré, Team: LAL
DvP adjustment for position C against LAL: 1
Added data for player: Bilal Coulibaly, Team: WAS
Added data for player: Tristan Vukcevic, Team: WAS
Added data for player: Johnny Davis, Team: WAS
Added data for player: Jared Butler, Team: WAS
Added data for player: Patrick Baldwin Jr., Team: WAS
Added data for player: Bub Carrington, Team: WAS
Added data for player: Justin Champagnie, Team: WAS
Added data for player: Jordan Poole, Team: WAS
Added data for player: Malcolm Brogdon, Team: WAS
Added data for player: Anthony Gill, Team: WAS
Added data for player: Jonas Valančiūnas, Team: WAS
Added data for player: Kyshawn George, Team: WAS
Added data for player: Alex Sarr, Team: WAS
Added data for player: Richaun Holmes, Team: WAS
Added data for player: Corey Kispert, Team: WAS
Added data for player: Kyle Kuzma, Team: WAS
Added data for player: Marvin Bagley III, Team: WAS
Added data for player: Jalen Hood-Schifino, Team: LAL
Added data for player: Jarred Vanderbilt, Team: LAL
Added data for player: Anthony Davis, Team: LAL
Added data for player: Dalton Knecht, Team: LAL
Added data for player: Cam Reddish, Team: LAL
Added data for player: Gabe Vincent, Team: LAL
Added data for player: Bronny James, Team: LAL
Added data for player: Christian Koloko, Team: LAL
Added data for player: Jaxson Hayes, Team: LAL
Added data for player: Max Christie, Team: LAL
Added data for player: Austin Reaves, Team: LAL
Added data for player: Dorian Finney-Smith, Team: LAL
Added data for player: Shake Milton, Team: LAL
Added data for player: LeBron James, Team: LAL
Added data for player: Rui Hachimura, Team: LAL
Added data for player: Trey Jemison III, Team: LAL
Added data for player: Armel Traoré, Team: LAL
DvP adjustment for position C against CLE: 1
Added data for player: Max Strus, Team: CLE
Added data for player: Ty Jerome, Team: CLE
Added data for player: Caris LeVert, Team: CLE
Added data for player: Evan Mobley, Team: CLE
Added data for player: Sam Merrill, Team: CLE
Added data for player: Craig Porter Jr., Team: CLE
Added data for player: Darius Garland, Team: CLE
Added data for player: Tristan Thompson, Team: CLE
Added data for player: JT Thor, Team: CLE
Added data for player: Georges Niang, Team: CLE
Added data for player: Emoni Bates, Team: CLE
Added data for player: Jaylon Tyson, Team: CLE
Added data for player: Jarrett Allen, Team: CLE
Added data for player: Dean Wade, Team: CLE
Added data for player: Luke Travers, Team: CLE
Added data for player: Isaac Okoro, Team: CLE
Added data for player: Donovan Mitchell, Team: CLE
Added data for player: Jalen Johnson, Team: ATL
Added data for player: Keaton Wallace, Team: ATL
Added data for player: Kobe Bufkin, Team: ATL
Added data for player: Dyson Daniels, Team: ATL
Added data for player: David Roddy, Team: ATL
Added data for player: Zaccharie Risacher, Team: ATL
Added data for player: Trae Young, Team: ATL
Added data for player: De'Andre Hunter, Team: ATL
Added data for player: Bogdan Bogdanović, Team: ATL
Added data for player: Clint Capela, Team: ATL
Added data for player: Onyeka Okongwu, Team: ATL
Added data for player: Mouhamed Gueye, Team: ATL
Added data for player: Larry Nance Jr., Team: ATL
Added data for player: Garrison Mathews, Team: ATL
Added data for player: Dominick Barlow, Team: ATL
Added data for player: Vít Krejčí, Team: ATL
Added data for player: Daeqwon Plowden, Team: ATL
DvP adjustment for position C against ATL: 1
Added data for player: Max Strus, Team: CLE
Added data for player: Ty Jerome, Team: CLE
Added data for player: Caris LeVert, Team: CLE
Added data for player: Evan Mobley, Team: CLE
Added data for player: Sam Merrill, Team: CLE
Added data for player: Craig Porter Jr., Team: CLE
Added data for player: Darius Garland, Team: CLE
Added data for player: Tristan Thompson, Team: CLE
Added data for player: JT Thor, Team: CLE
Added data for player: Georges Niang, Team: CLE
Added data for player: Emoni Bates, Team: CLE
Added data for player: Jaylon Tyson, Team: CLE
Added data for player: Jarrett Allen, Team: CLE
Added data for player: Dean Wade, Team: CLE
Added data for player: Luke Travers, Team: CLE
Added data for player: Isaac Okoro, Team: CLE
Added data for player: Donovan Mitchell, Team: CLE
Added data for player: Jalen Johnson, Team: ATL
Added data for player: Keaton Wallace, Team: ATL
Added data for player: Kobe Bufkin, Team: ATL
Added data for player: Dyson Daniels, Team: ATL
Error fetching game logs for player 1631223: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Added data for player: Zaccharie Risacher, Team: ATL
Error fetching game logs for player 1629027: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1629631: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 203992: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 203991: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1630168: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1631243: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1626204: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1629726: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Added data for player: Dominick Barlow, Team: ATL
Error fetching game logs for player 1630249: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1631342: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 203469: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position C against UTA: 1
Error fetching game logs for player 203903: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1641707: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1629012: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Added data for player: Keyonte George, Team: UTA
Added data for player: Cody Williams, Team: UTA
Added data for player: Patty Mills, Team: UTA
Error fetching game logs for player 1642268: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Added data for player: Drew Eubanks, Team: UTA
Error fetching game logs for player 1641989: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1629004: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1628381: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1642271: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1628374: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1631117: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1630695: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1641729: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1630548: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1631131: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error analyzing team MIN: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position C against MIN: 1
Error analyzing team UTA: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error analyzing team MIN: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position C against MEM: 1
Error analyzing team MEM: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error analyzing team HOU: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position C against HOU: 1
Error analyzing team MEM: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error analyzing team HOU: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position C against POR: 1
Error analyzing team POR: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error analyzing team ORL: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
DvP adjustment for position C against ORL: 1
Error analyzing team POR: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Error fetching game logs for player 1641710: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Added data for player: Jonathan Isaac, Team: ORL
Added data for player: Caleb Houstan, Team: ORL
Error fetching game logs for player 203484: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
Added data for player: Jalen Suggs, Team: ORL
Added data for player: Paolo Banchero, Team: ORL
Added data for player: Mac McClung, Team: ORL
Added data for player: Cory Joseph, Team: ORL
Added data for player: Trevelin Queen, Team: ORL
Added data for player: Jett Howard, Team: ORL
Added data for player: Gary Harris, Team: ORL
Added data for player: Moritz Wagner, Team: ORL
Added data for player: Franz Wagner, Team: ORL
Added data for player: Tristan da Silva, Team: ORL
Added data for player: Wendell Carter Jr., Team: ORL
Added data for player: Goga Bitadze, Team: ORL
Added data for player: Cole Anthony, Team: ORL

                Player     Position      Team        PPG        PPG SD      PPG CV        PPG Diff    Adj PPG       RPG        RPG SD      RPG CV       RPG Diff    Adj RPG       APG        APG SD      APG CV       APG Diff    Adj APG       USG%    Injury Status
0        Bilal Coulibaly    ['G']        WAS        12.31        6.7         0.54      5.61 - 19.01    11.53        5.0         2.28        0.46      2.72 - 7.28     4.68        3.36        1.95        0.58      1.41 - 5.31     3.14       0.177        Healthy
1       Tristan Vukcevic    ['G']        WAS         1.88        3.48        1.86      -1.61 - 5.36     1.76        0.62        0.74        1.19     -0.12 - 1.37     0.59        0.38        0.74        1.98     -0.37 - 1.12     0.35       0.244        Healthy
2           Johnny Davis    ['G']        WAS         2.44        2.82        1.16      -0.38 - 5.25     2.28        1.12        1.58        1.41     -0.46 - 2.71     1.05        0.34        0.55        1.59     -0.20 - 0.89     0.32       0.156        Healthy
3           Jared Butler    ['G']        WAS         6.84        5.91        0.86      0.93 - 12.75     6.4         1.32        1.74        1.32     -0.42 - 3.06     1.24        2.55        2.06        0.81      0.49 - 4.61     2.39       0.253        Healthy
4    Patrick Baldwin Jr.    ['G']        WAS         2.1         2.07        0.99       0.02 - 4.17     1.96        0.95        1.24        1.31     -0.29 - 2.20     0.89        0.1         0.3         3.16     -0.21 - 0.40     0.09       0.155        Healthy
5         Bub Carrington    ['G']        WAS         8.78        4.74        0.54      4.05 - 13.52     8.23        4.09        2.39        0.59      1.69 - 6.48     3.83        3.78        2.06        0.55      1.72 - 5.85     3.54       0.144        Healthy
6      Justin Champagnie    ['G']        WAS         8.11        7.53        0.93      0.57 - 15.64     7.59        4.89        3.44        0.7       1.46 - 8.33     4.58        1.04        1.2         1.16     -0.17 - 2.24     0.97       0.155        Healthy
7           Jordan Poole    ['G']        WAS        20.74        8.93        0.43     11.81 - 29.68    19.43        3.0         1.97        0.66      1.03 - 4.97     2.81        4.9         2.34        0.48      2.56 - 7.23     4.59       0.282        Healthy
8        Malcolm Brogdon    ['G']        WAS        13.83        7.44        0.54      6.40 - 21.27    12.96        4.06        2.94        0.72      1.12 - 7.00     3.8         3.94        2.26        0.57      1.68 - 6.21     3.69       0.243          Out
9           Anthony Gill    ['G']        WAS         1.94        2.21        1.14      -0.27 - 4.15     1.82        0.85        1.3         1.53     -0.45 - 2.15     0.79        0.21        0.48        2.28     -0.27 - 0.70     0.2        0.128        Healthy
10     Jonas Valančiūnas    ['G']        WAS        11.57        5.51        0.48      6.05 - 17.08    10.83        8.13        3.22        0.4      4.91 - 11.35     7.61        2.15        1.66        0.77      0.49 - 3.81     2.02       0.238        Healthy
11        Kyshawn George    ['G']        WAS         7.46        5.59        0.75      1.87 - 13.05     6.99        3.61        1.67        0.46      1.94 - 5.28     3.38        2.24        1.53        0.68      0.71 - 3.77     2.1        0.152        Healthy
12            Alex Sarr     ['G']        WAS        11.46        4.82        0.42      6.64 - 16.29    10.74        6.63        2.84        0.43      3.79 - 9.48     6.21        2.2         1.52        0.69      0.67 - 3.72     2.06       0.207          Out
13        Richaun Holmes    ['G']        WAS         3.89        3.52        0.9        0.37 - 7.40     3.64        3.33        3.35        1.01     -0.02 - 6.69     3.12        0.44        1.01        2.28     -0.57 - 1.46     0.42        0.16        Healthy
14         Corey Kispert    ['G']        WAS        11.15        6.04        0.54      5.11 - 17.19    10.44        2.93        1.63        0.56      1.29 - 4.56     2.74        1.59        1.16        0.73      0.42 - 2.75     1.48       0.171        Healthy
15            Kyle Kuzma    ['G']        WAS        14.48        7.85        0.54      6.63 - 22.33    13.56        5.86        2.7         0.46      3.17 - 8.56     5.49        2.55        1.7         0.67      0.85 - 4.25     2.39        0.26        Healthy
16     Marvin Bagley III    ['G']        WAS         4.89        5.46        1.11     -0.56 - 10.35     4.58        2.95        2.68        0.91      0.27 - 5.62     2.76        0.37        0.6         1.62     -0.23 - 0.97     0.35       0.222          Out
17   Jalen Hood-Schifino    ['G']        LAL         2.0         2.83        1.41      -0.83 - 4.83     1.88        0.5         0.71        1.41     -0.21 - 1.21     0.47        0.5         0.71        1.41     -0.21 - 1.21     0.47       0.089          Out
18     Jarred Vanderbilt    ['G']        LAL         3.0         1.41        0.47       1.59 - 4.41     2.81        3.0         1.41        0.47      1.59 - 4.41     2.81        1.5         0.71        0.47      0.79 - 2.21     1.41       0.125        Healthy
19         Anthony Davis    ['G']        LAL        25.74       10.36        0.4      15.38 - 36.10    24.13       11.88        4.14        0.35     7.74 - 16.02    11.14        3.36        2.06        0.61      1.30 - 5.42     3.15       0.305          Out
20         Dalton Knecht    ['G']        LAL         9.47        7.99        0.84      1.48 - 17.45     8.88        3.16        2.34        0.74      0.82 - 5.49     2.96        0.91        0.9         0.99      0.01 - 1.81     0.85       0.179        Healthy
21           Cam Reddish    ['G']        LAL         3.32        3.72        1.12      -0.40 - 7.04     3.12        2.0         2.11        1.06     -0.11 - 4.11     1.88        0.71        0.97        1.37     -0.26 - 1.68     0.67       0.087        Healthy
22          Gabe Vincent    ['G']        LAL         4.87        3.87        0.8        1.00 - 8.75     4.57        1.26        1.14        0.91      0.12 - 2.40     1.18        1.26        1.41        1.12     -0.15 - 2.67     1.18       0.121       Day-To-Day
23          Bronny James    ['G']        LAL         0.31        0.75        2.44      -0.44 - 1.06     0.29        0.38        0.87        2.26     -0.49 - 1.25     0.36        0.31        0.63        2.05     -0.32 - 0.94     0.29       0.206        Healthy
24      Christian Koloko    ['G']        LAL         2.04        2.13        1.04      -0.09 - 4.17     1.91        2.24        2.39        1.06     -0.15 - 4.63     2.1         0.44        1.0         2.28     -0.56 - 1.44     0.41       0.092        Healthy
25          Jaxson Hayes    ['G']        LAL         5.17        3.02        0.58       2.15 - 8.18     4.84        3.83        2.62        0.68      1.22 - 6.45     3.59        0.75        0.94        1.26     -0.19 - 1.69     0.7        0.117        Healthy
26          Max Christie    ['G']        LAL         8.23        5.52        0.67      2.71 - 13.75     7.71        2.64        1.94        0.74      0.69 - 4.58     2.47        1.39        1.17        0.84      0.22 - 2.55     1.3         0.14        Healthy
27         Austin Reaves    ['G']        LAL        18.23        6.47        0.36     11.75 - 24.70    17.09        4.2         2.58        0.62      1.62 - 6.78     3.94        6.12        3.2         0.52      2.93 - 9.32     5.74       0.225        Healthy
28   Dorian Finney-Smith    ['G']        LAL         8.81        5.38        0.61      3.43 - 14.19     8.26        4.0         1.78        0.44      2.22 - 5.78     3.75        1.25        1.3         1.04     -0.05 - 2.55     1.17       0.134       Day-To-Day
29          Shake Milton    ['G']        LAL         5.94        6.13        1.03     -0.18 - 12.07     5.57        1.75        1.57        0.9       0.18 - 3.32     1.64        2.03        2.58        1.27     -0.55 - 4.61     1.9        0.166        Healthy
30          LeBron James    ['G']        LAL        23.81        7.33        0.31     16.48 - 31.14    22.32        7.6         3.3         0.43     4.30 - 10.89     7.12        8.95        2.9         0.32     6.05 - 11.86     8.39       0.298       Day-To-Day
31         Rui Hachimura    ['G']        LAL        12.18        5.06        0.42      7.12 - 17.25    11.42        5.18        2.5         0.48      2.68 - 7.69     4.86        1.5         1.01        0.67      0.49 - 2.51     1.41       0.156       Day-To-Day
32      Trey Jemison III    ['G']        LAL         2.17        2.41        1.11      -0.24 - 4.57     2.03        2.78        1.96        0.7       0.82 - 4.73     2.6         0.56        0.7         1.27     -0.15 - 1.26     0.52       0.125        Healthy
33          Armel Traoré    ['G']        LAL         1.5         1.77        1.18      -0.27 - 3.27     1.41        1.75        1.67        0.95      0.08 - 3.42     1.64        0.12        0.35        2.83     -0.23 - 0.48     0.12       0.166        Healthy
68            Max Strus     ['G']        CLE         7.89        4.67        0.59      3.23 - 12.56     8.61        4.16        2.36        0.57      1.79 - 6.52     4.53        3.05        1.78        0.58      1.27 - 4.83     3.33       0.141        Healthy
69            Ty Jerome     ['G']        CLE        11.14        7.18        0.64      3.96 - 18.32    12.14        2.34        1.58        0.68      0.76 - 3.92     2.55        3.34        2.08        0.62      1.26 - 5.42     3.64       0.225        Healthy
70          Caris LeVert    ['G']        CLE         10.8        5.44        0.5       5.36 - 16.24    11.77        2.91        1.7         0.58      1.21 - 4.62     3.18        3.77        1.88        0.5       1.89 - 5.65     4.11       0.183          Out
71           Evan Mobley    ['G']        CLE        18.22        7.3         0.4      10.92 - 25.52    19.86        9.07        3.3         0.36     5.77 - 12.38     9.89        2.83        1.94        0.68      0.89 - 4.76     3.08        0.23        Healthy
72           Sam Merrill    ['G']        CLE         6.62        4.55        0.69      2.07 - 11.16     7.21        1.9         1.55        0.82      0.34 - 3.45     2.07        1.62        1.44        0.89      0.17 - 3.06     1.76       0.153       Day-To-Day
73      Craig Porter Jr.    ['G']        CLE         2.57        3.53        1.37      -0.96 - 6.10     2.8         0.89        1.13        1.27     -0.24 - 2.03     0.97        1.04        1.53        1.47     -0.49 - 2.56     1.13       0.134        Healthy
74        Darius Garland    ['G']        CLE        21.71        7.72        0.36     13.99 - 29.44    23.67        2.53        1.52        0.6       1.02 - 4.05     2.76        6.8         2.33        0.34      4.47 - 9.13     7.41       0.274       Day-To-Day
75      Tristan Thompson    ['G']        CLE         1.87        2.2         1.18      -0.33 - 4.07     2.04        2.74        2.86        1.05     -0.12 - 5.60     2.99        0.61        1.03        1.7      -0.42 - 1.64     0.66       0.145        Healthy
76             JT Thor      ['G']        CLE         3.5         3.85        1.1       -0.35 - 7.35     3.82        0.75        0.89        1.18     -0.14 - 1.64     0.82        0.12        0.35        2.83     -0.23 - 0.48     0.14       0.257        Healthy
77         Georges Niang    ['G']        CLE         8.7         4.84        0.56      3.86 - 13.54     9.49        3.77        2.3         0.61      1.47 - 6.06     4.11        1.38        1.09        0.79      0.29 - 2.48     1.51        0.17        Healthy
78           Emoni Bates    ['G']        CLE         0.0         0.0         0.0        0.00 - 0.00     0.0         0.0         0.0         0.0       0.00 - 0.00     0.0         0.33        0.58        1.73     -0.24 - 0.91     0.36       0.168        Healthy
79          Jaylon Tyson    ['G']        CLE         2.38        3.73        1.57      -1.35 - 6.11     2.59        1.93        2.37        1.23     -0.44 - 4.31     2.11        0.83        1.49        1.8      -0.66 - 2.32     0.9         0.14        Healthy
80         Jarrett Allen    ['G']        CLE        13.83        5.86        0.42      7.97 - 19.69    15.08        9.96        3.44        0.35     6.51 - 13.40    10.86        1.94        1.57        0.81      0.37 - 3.50     2.11       0.157        Healthy
81            Dean Wade     ['G']        CLE         6.03        4.17        0.69      1.86 - 10.20     6.57        5.09        2.37        0.47      2.72 - 7.45     5.54        1.57        1.2         0.76      0.38 - 2.77     1.71       0.107          Out
82          Luke Travers    ['G']        CLE         1.33        2.07        1.55      -0.73 - 3.40     1.45        1.0         0.89        0.89      0.11 - 1.89     1.09        0.83        1.33        1.59     -0.50 - 2.16     0.91       0.111          Out
83           Isaac Okoro    ['G']        CLE         5.75        4.36        0.76      1.39 - 10.11     6.27        2.07        2.04        0.98      0.04 - 4.11     2.26        1.64        1.13        0.69      0.51 - 2.77     1.79        0.12          Out
84      Donovan Mitchell    ['G']        CLE        23.93        8.26        0.35     15.67 - 32.19    26.09        4.33        2.71        0.62      1.63 - 7.04     4.72        4.64        2.01        0.43      2.63 - 6.66     5.06       0.306        Healthy
85         Jalen Johnson    ['G']        ATL        18.89        6.2         0.33     12.68 - 25.09    19.57        9.97        3.68        0.37     6.30 - 13.65    10.33        5.03        2.35        0.47      2.68 - 7.38     5.21        0.22          Out
86        Keaton Wallace    ['G']        ATL         6.42        6.45        1.0      -0.03 - 12.87     6.65        1.68        1.57        0.93      0.12 - 3.25     1.75        2.26        2.42        1.07     -0.16 - 4.69     2.35       0.164        Healthy
87           Kobe Bufkin    ['G']        ATL         5.3         3.09        0.58       2.21 - 8.39     5.49        2.1         1.29        0.61      0.81 - 3.39     2.18        1.7         1.49        0.88      0.21 - 3.19     1.76       0.209          Out
88         Dyson Daniels    ['G']        ATL         13.5        5.32        0.39      8.18 - 18.82    13.99        5.29        2.38        0.45      2.90 - 7.67     5.48        3.67        1.65        0.45      2.02 - 5.31     3.8        0.178        Healthy
89           David Roddy    ['G']        ATL         4.69        4.71        1.0       -0.02 - 9.41     4.86        2.69        2.48        0.92      0.21 - 5.17     2.79        1.15        1.19        1.03     -0.04 - 2.34     1.2        0.151        Healthy
90    Zaccharie Risacher    ['G']        ATL        10.52        5.85        0.56      4.68 - 16.37    10.91        3.55        2.26        0.64      1.29 - 5.81     3.68        1.2         1.07        0.89      0.13 - 2.27     1.24       0.205        Healthy
91            Trae Young    ['G']        ATL        22.72        8.81        0.39     13.92 - 31.53    23.55        3.35        2.03        0.61      1.31 - 5.38     3.47       11.42        4.24        0.37     7.17 - 15.66    11.83       0.279       Day-To-Day
92       De'Andre Hunter    ['G']        ATL        19.12        6.81        0.36     12.31 - 25.93    19.81        3.7         1.88        0.51      1.82 - 5.58     3.83        1.45        1.06        0.73      0.39 - 2.52     1.51       0.247        Healthy
93     Bogdan Bogdanović    ['G']        ATL         10.0        5.96        0.6       4.04 - 15.96    10.36        2.75        1.96        0.71      0.79 - 4.71     2.85        2.04        1.37        0.67      0.68 - 3.41     2.12       0.185        Healthy
94          Clint Capela    ['G']        ATL         9.42        4.9         0.52      4.52 - 14.32     9.76        9.0         3.42        0.38     5.58 - 12.42     9.33        1.2         0.87        0.72      0.33 - 2.07     1.24       0.164          Out
95        Onyeka Okongwu    ['G']        ATL        11.62        5.57        0.48      6.06 - 17.19    12.05        7.72        3.69        0.48     4.03 - 11.42     8.01        1.9         1.72        0.91      0.18 - 3.62     1.97       0.172        Healthy
96        Mouhamed Gueye    ['G']        ATL         4.25        4.79        1.13      -0.54 - 9.04     4.4         3.25        2.99        0.92      0.26 - 6.24     3.37        0.25        0.5         2.0      -0.25 - 0.75     0.26       0.214        Healthy
97       Larry Nance Jr.    ['G']        ATL         9.0         6.6         0.73      2.40 - 15.60     9.33        4.12        3.62        0.88      0.50 - 7.74     4.27        1.53        1.28        0.84      0.25 - 2.81     1.58       0.159        Healthy
98      Garrison Mathews    ['G']        ATL         7.87        6.24        0.79      1.62 - 14.11     8.15        1.74        1.75        1.01     -0.01 - 3.49     1.8         1.45        1.43        0.99      0.02 - 2.87     1.5         0.16        Healthy
99       Dominick Barlow    ['G']        ATL         1.8         3.39        1.88      -1.59 - 5.19     1.87        0.9         0.88        0.97      0.02 - 1.78     0.93        0.3         0.48        1.61     -0.18 - 0.78     0.31       0.133        Healthy
100           Vít Krejčí    ['G']        ATL         6.5         5.41        0.83      1.09 - 11.91     6.74        2.44        1.9         0.78      0.54 - 4.34     2.53        2.72        2.07        0.76      0.65 - 4.79     2.82       0.139        Healthy
101      Daeqwon Plowden    ['G']        ATL         12.0        9.9         0.82      2.10 - 21.90    12.44        2.5         2.12        0.85      0.38 - 4.62     2.59        0.0         0.0         0.0       0.00 - 0.00     0.0         0.15        Healthy
125       Keyonte George    ['G']        UTA        16.09        6.72        0.42      9.37 - 22.80    16.22        3.54        1.6         0.45      1.95 - 5.14     3.57        5.8         2.19        0.38      3.61 - 7.99     5.85       0.242        Healthy
126        Cody Williams    ['G']        UTA         3.88        3.6         0.93       0.28 - 7.49     3.92        2.19        1.6         0.73      0.59 - 3.79     2.21        1.35        1.06        0.78      0.29 - 2.40     1.36       0.118          Out
127          Patty Mills    ['G']        UTA         4.35        4.29        0.98       0.07 - 8.64     4.39        1.24        0.9         0.73      0.33 - 2.14     1.25        1.24        1.25        1.01     -0.02 - 2.49     1.25        0.15        Healthy
128         Drew Eubanks    ['G']        UTA         5.81        4.03        0.69       1.78 - 9.83     5.85        4.67        2.9         0.62      1.77 - 7.56     4.7         1.19        0.92        0.77      0.27 - 2.11     1.2         0.15        Healthy
129       Jonathan Isaac    ['G']        ORL         6.38        4.39        0.69      1.99 - 10.77     5.7         4.9         2.77        0.56      2.14 - 7.67     4.38        0.48        0.59        1.25     -0.12 - 1.07     0.43       0.172        Healthy
130        Caleb Houstan    ['G']        ORL         2.88        3.86        1.34      -0.98 - 6.74     2.57        1.0         1.56        1.56     -0.56 - 2.56     0.89        0.45        0.67        1.46     -0.21 - 1.12     0.41       0.113        Healthy
131          Jalen Suggs    ['G']        ORL         16.2        8.09        0.5       8.11 - 24.29    14.46        4.03        2.05        0.51      1.98 - 6.08     3.6         3.69        2.01        0.55      1.67 - 5.70     3.29       0.274       Day-To-Day

In [3]:
# Install required package
!pip install nba_api

import json
import time
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.endpoints import teamestimatedmetrics, playerestimatedmetrics
from nba_api.stats.endpoints import leaguedashteamstats, commonteamroster
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, playergamelogs
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display

# Map of team names to abbreviations
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL", "Boston Celtics": "BOS", "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA", "Chicago Bulls": "CHI", "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL", "Denver Nuggets": "DEN", "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW", "Houston Rockets": "HOU", "Indiana Pacers": "IND",
    "LA Clippers": "LAC", "Los Angeles Lakers": "LAL", "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA", "Milwaukee Bucks": "MIL", "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP", "New York Knicks": "NYK", "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL", "Philadelphia 76ers": "PHI", "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR", "Sacramento Kings": "SAC", "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR", "Utah Jazz": "UTA", "Washington Wizards": "WAS"
}

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        stats = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        ).get_data_frames()[0]

        metrics = stats[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        team_metrics = {TEAM_NAME_TO_ABBREVIATION.get(k, k): v for k, v in metrics_dict.items()}
        return team_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Initialize DvP data
def initialize_dvp_data():
    try:
        stats = leaguedashteamstats.LeagueDashTeamStats(
            measure_type_detailed_defense='Opponent',
            per_mode_detailed='PerGame',
            season="2024-25",
            season_type_all_star="Regular Season"
        ).get_data_frames()[0]

        stats['TEAM_ABBREVIATION'] = stats['TEAM_NAME'].map(TEAM_NAME_TO_ABBREVIATION)

        dvp_data = {}
        for pos in ['C', 'F', 'G']:
            column = f'OPP_PTS_{pos.upper()}'
            if column in stats.columns:
                dvp_data[pos] = stats.groupby('TEAM_ABBREVIATION')[column].mean().to_dict()

        return dvp_data
    except Exception as e:
        print(f"Error fetching DvP stats: {e}")
        return {}

# Normalize player positions
def normalize_player_position(position):
    if not position or not isinstance(position, str):
        return []

    positions = position.split("-")
    valid_positions = {'C', 'F', 'G'}
    return [pos.strip() for pos in positions if pos.strip() in {"C", "F", "G"}]
    print(f"Player: {player_name}, Original Position: {player_position}, Normalized: {player_normalized_positions}")

# Initialize globally for consistent usage across functions
normalized_positions = []  # Collect all normalized positions globally

# Process team rosters
def process_team_roster(team_name):
    global normalized_positions  # Ensure this modifies the global list
    try:
        team_id = teams.find_team_by_abbreviation(team_name)['id']
        roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

        for _, player in roster.iterrows():
            player_name = player['PLAYER']
            player_position = player['POSITION']
            player_normalized_positions = normalize_player_position(player_position)
            normalized_positions.extend(player_normalized_positions)  # Collect positions
            print(f"Processed {player_name} with positions {player_normalized_positions}")
    except Exception as e:
        print(f"Error processing roster for team {team_name}: {e}")

# Adjust main analysis function
def analyze_teams_for_today():
    global normalized_positions  # To accumulate across games
    normalized_positions.clear()  # Reset at the start of the day's analysis

    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            process_team_roster(team_name)

    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        return playergamelog.PlayerGameLog(player_id=player_id, season="2024-25").get_data_frames()[0]
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

def fetch_injury_data():
    url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        injury_status_dict = {}  # Store injuries in {player_name: status} format

        for team in data.get('injuries', []):
            for injury in team.get('injuries', []):
                player_name = injury.get('athlete', {}).get('displayName', 'Unknown Player')
                status = injury.get('status', 'Healthy')  # Default to 'Healthy'
                injury_status_dict[player_name] = status

        return injury_status_dict
    except Exception as e:
        print(f"Error fetching injury data: {e}")
        return {}

# Calculate stats
def calculate_stats(stat_series):
    mean = stat_series.mean()
    std_dev = stat_series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust predictions for DvP and other factors
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data):
    try:
        positions = player_position.split("-")
        dvp_factors = [dvp_data[pos].get(opposing_metrics['TEAM_ABBREVIATION'], 1) for pos in positions if pos in dvp_data]

        dvp_factor = sum(dvp_factors) / len(dvp_factors) if dvp_factors else 1
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        return stat_mean * pace_factor * offensive_factor / defensive_factor * dvp_factor
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Main analysis for today's games
def analyze_teams_for_today():
    dvp_data = initialize_dvp_data()
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_status_dict = fetch_injury_data()  # Assuming this function fetches injury data
    injury_data = injury_status_dict  # Store all injury statuses

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []
    normalized_positions = []  # Initialize here to store all normalized positions

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            try:
                team_id = teams.find_team_by_abbreviation(team_name)['id']
                roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in roster.iterrows():
                    player_position = player['POSITION']
                    player_normalized_positions = normalize_player_position(player_position)
                    normalized_positions.extend(player_normalized_positions)  # Collect positions

                    # Process player as needed, e.g., fetching game logs
            except Exception as e:
                print(f"Error processing team roster for {team_name}: {e}")

    # Adjust for multi-position players in DvP adjustment
    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})
                dvp_factor = dvp_data.get(pos, {}).get(opposing_metrics.get('TEAM_ABBREVIATION', ''), 1)
                print(f"DvP adjustment for position {pos} against {opposing_team}: {dvp_factor}")

                # Continue processing
                if home_team not in team_metrics or away_team not in team_metrics:
                        print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
                        continue

                for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
                        try:
                            # Fetch team roster here
                            team_id = teams.find_team_by_abbreviation(team_name)['id']
                            roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                            # Fetch injury data once to use throughout the script
                            injury_data = fetch_injury_data()

                            for _, player in roster.iterrows():
                                player_id = player['PLAYER_ID']
                                player_name = player['PLAYER']
                                player_position = player['POSITION']
                                usg_pct = player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A')
                                injury_status = injury_data.get(player_name, 'Healthy')

                                game_logs = fetch_player_game_logs(player_id)
                                if game_logs.empty:
                                    continue

                                mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                                mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                                mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                                adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)
                                adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position, dvp_data)

                                # Add new difference columns
                                low = mean_ppg - std_dev_ppg
                                high = mean_ppg + std_dev_ppg
                                ppg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_rpg - std_dev_rpg
                                high = mean_rpg + std_dev_rpg
                                rpg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_apg - std_dev_apg
                                high = mean_apg + std_dev_apg
                                apg_diff = f"{low:.2f} - {high:.2f}"

                                all_players_data.append({
                                    'Player': player_name,
                                    'Position': player_normalized_positions,
                                    'Team': team_name,
                                    'PPG': round(mean_ppg, 2),
                                    'PPG SD': round(std_dev_ppg, 2),
                                    'PPG CV': round(cv_ppg, 2),
                                    'PPG Diff': ppg_diff,
                                    'Adj PPG': round(adjusted_ppg, 2),
                                    'RPG': round(mean_rpg, 2),
                                    'RPG SD': round(std_dev_rpg, 2),
                                    'RPG CV': round(cv_rpg, 2),
                                    'RPG Diff': rpg_diff,
                                    'Adj RPG': round(adjusted_rpg, 2),
                                    'APG': round(mean_apg, 2),
                                    'APG SD': round(std_dev_apg, 2),
                                    'APG CV': round(cv_apg, 2),
                                    'APG Diff': apg_diff,
                                    'Adj APG': round(adjusted_apg, 2),
                                    'USG%': usg_pct,
                                    'Injury Status': injury_status
                                })

# Debug: Print player data added to all_players_data
                                print(f"Added data for player: {player_name}, Team: {team_name}")

                                time.sleep(1)  # To avoid rate-limiting
                        except Exception as e:
                            print(f"Error analyzing team {team_name}: {e}")
                            continue

        df = pd.DataFrame(all_players_data)
        df = df.drop_duplicates(subset=['Player', 'Team'])
        df.columns = [col.center(10) for col in df.columns]
        df = df.apply(lambda row: row.map(lambda x: str(x).center(10)), axis=1)
        display(df)
        return df  # This is now correctly placed within the function

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.disable_dataframe_formatter()

Requirement already satisfied: nba_api in /usr/local/lib/python3.12/dist-packages (1.11.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.10.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
No games scheduled for 2025-11-12.
No games scheduled for today.

In [2]:
# Install required package
!pip install nba_api

import json
import time
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.endpoints import teamestimatedmetrics, playerestimatedmetrics
from nba_api.stats.endpoints import leaguedashteamstats, commonteamroster
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog, playergamelogs
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display

# Map of team names to abbreviations
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL", "Boston Celtics": "BOS", "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA", "Chicago Bulls": "CHI", "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL", "Denver Nuggets": "DEN", "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW", "Houston Rockets": "HOU", "Indiana Pacers": "IND",
    "LA Clippers": "LAC", "Los Angeles Lakers": "LAL", "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA", "Milwaukee Bucks": "MIL", "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP", "New York Knicks": "NYK", "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL", "Philadelphia 76ers": "PHI", "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR", "Sacramento Kings": "SAC", "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR", "Utah Jazz": "UTA", "Washington Wizards": "WAS"
}

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Fetch team metrics
def fetch_team_metrics():
    try:
        stats = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        ).get_data_frames()[0]

        metrics = stats[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        team_metrics = {TEAM_NAME_TO_ABBREVIATION.get(k, k): v for k, v in metrics_dict.items()}
        return team_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Process team rosters
def process_team_roster(team_name):
    global normalized_positions  # Ensure this modifies the global list
    try:
        team_id = teams.find_team_by_abbreviation(team_name)['id']
        roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

        for _, player in roster.iterrows():
            player_name = player['PLAYER']
            player_position = player['POSITION']
            player_normalized_positions = normalize_player_position(player_position)
            normalized_positions.extend(player_normalized_positions)  # Collect positions
            print(f"Processed {player_name} with positions {player_normalized_positions}")
    except Exception as e:
        print(f"Error processing roster for team {team_name}: {e}")

# Adjust main analysis function
def analyze_teams_for_today():
    global normalized_positions  # To accumulate across games
    normalized_positions.clear()  # Reset at the start of the day's analysis
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data()

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            process_team_roster(team_name)

    for pos in set(normalized_positions):  # Use unique positions only
        for game in games_today:
            home_team = game['home_team']
            away_team = game['away_team']
            for opposing_team in [home_team, away_team]:
                opposing_metrics = team_metrics.get(opposing_team, {})

# Fetch player game logs
def fetch_player_game_logs(player_id):
    try:
        return playergamelog.PlayerGameLog(player_id=player_id, season="2024-25").get_data_frames()[0]
    except Exception as e:
        print(f"Error fetching game logs for player {player_id}: {e}")
        return pd.DataFrame()

def fetch_injury_data():
    url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        injury_status_dict = {}  # Store injuries in {player_name: status} format

        for team in data.get('injuries', []):
            for injury in team.get('injuries', []):
                player_name = injury.get('athlete', {}).get('displayName', 'Unknown Player')
                status = injury.get('status', 'Healthy')  # Default to 'Healthy'
                injury_status_dict[player_name] = status

        return injury_status_dict
    except Exception as e:
        print(f"Error fetching injury data: {e}")
        return {}

# Calculate stats
def calculate_stats(stat_series):
    mean = stat_series.mean()
    std_dev = stat_series.std()
    cv = std_dev / mean if mean != 0 else 0
    return mean, std_dev, cv

# Adjust predictions for ORTG, DRTG, and PACE
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position):
    try:
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        return stat_mean * pace_factor * offensive_factor / defensive_factor
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Main analysis for today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_status_dict = fetch_injury_data()  # Assuming this function fetches injury data
    injury_data = injury_status_dict  # Store all injury statuses

    if not games_today:
        print("No games scheduled for today.")
        return

    all_players_data = []
    normalized_positions = []  # Initialize here to store all normalized positions

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        for team_name in [home_team, away_team]:
            try:
                team_id = teams.find_team_by_abbreviation(team_name)['id']
                roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                for _, player in roster.iterrows():
                    player_position = player['POSITION']
                    player_positions = player_position(player_position)
                    player_positions.extend(player_positions)  # Collect positions

                    # Process player as needed, e.g., fetching game logs
            except Exception as e:
                print(f"Error processing team roster for {team_name}: {e}")

                # Continue processing
                if home_team not in team_metrics or away_team not in team_metrics:
                        print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
                        continue

                for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
                        try:
                            # Fetch team roster here
                            team_id = teams.find_team_by_abbreviation(team_name)['id']
                            roster = commonteamroster.CommonTeamRoster(team_id=team_id).get_data_frames()[0]

                            # Fetch injury data once to use throughout the script
                            injury_data = fetch_injury_data()

                            for _, player in roster.iterrows():
                                player_id = player['PLAYER_ID']
                                player_name = player['PLAYER']
                                player_position = player['POSITION']
                                usg_pct = player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A')
                                injury_status = injury_data.get(player_name, 'Healthy')

                                game_logs = fetch_player_game_logs(player_id)
                                if game_logs.empty:
                                    continue

                                mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                                mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                                mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                                adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position)
                                adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position)
                                adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating, player_position)

                                # Add new difference columns
                                low = mean_ppg - std_dev_ppg
                                high = mean_ppg + std_dev_ppg
                                ppg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_rpg - std_dev_rpg
                                high = mean_rpg + std_dev_rpg
                                rpg_diff = f"{low:.2f} - {high:.2f}"
                                low = mean_apg - std_dev_apg
                                high = mean_apg + std_dev_apg
                                apg_diff = f"{low:.2f} - {high:.2f}"

                                all_players_data.append({
                                    'Player': player_name,
                                    'Position': player_position,
                                    'Team': team_name,
                                    'PPG': round(mean_ppg, 2),
                                    'PPG SD': round(std_dev_ppg, 2),
                                    'PPG CV': round(cv_ppg, 2),
                                    'PPG Diff': ppg_diff,
                                    'Adj PPG': round(adjusted_ppg, 2),
                                    'RPG': round(mean_rpg, 2),
                                    'RPG SD': round(std_dev_rpg, 2),
                                    'RPG CV': round(cv_rpg, 2),
                                    'RPG Diff': rpg_diff,
                                    'Adj RPG': round(adjusted_rpg, 2),
                                    'APG': round(mean_apg, 2),
                                    'APG SD': round(std_dev_apg, 2),
                                    'APG CV': round(cv_apg, 2),
                                    'APG Diff': apg_diff,
                                    'Adj APG': round(adjusted_apg, 2),
                                    'USG%': usg_pct,
                                    'Injury Status': injury_status
                                })

# Debug: Print player data added to all_players_data
                                print(f"Added data for player: {player_name}, Team: {team_name}")

                                time.sleep(1)  # To avoid rate-limiting
                        except Exception as e:
                            print(f"Error analyzing team {team_name}: {e}")
                            continue

        df = pd.DataFrame(all_players_data)
        df = df.drop_duplicates(subset=['Player', 'Team'])
        df.columns = [col.center(10) for col in df.columns]
        df = df.apply(lambda row: row.map(lambda x: str(x).center(10)), axis=1)
        display(df)
        return df  # This is now correctly placed within the function

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.disable_dataframe_formatter()

Requirement already satisfied: nba_api in /usr/local/lib/python3.12/dist-packages (1.11.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.10.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
No games scheduled for 2025-11-12.
No games scheduled for today.

In [1]:
# Install required package
!pip install nba_api

import json
from nba_api.stats.endpoints import teamestimatedmetrics
from nba_api.stats.endpoints import TeamVsPlayer
from nba_api.stats.endpoints import PlayerGameLogs
from nba_api.stats.endpoints import playergamelog
import pandas as pd
import requests
from datetime import datetime
import pytz
from nba_api.stats.static import teams
from nba_api.stats.endpoints import commonteamroster
from nba_api.stats.library.parameters import SeasonAll
from IPython.display import display
import time  # Ensure time is imported

# Set display options for Google Colab
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

# Fetch today's schedule from NBA Stats API
def fetch_schedule():
    try:
        url = "https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule.json"
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        # Set timezone to EST
        est = pytz.timezone('US/Eastern')
        today = datetime.now(est).strftime('%Y-%m-%d')
        games_today = []

        for month_data in data['lscd']:
            for game in month_data['mscd']['g']:
                if game['gdte'] == today:
                    games_today.append({
                        'home_team': game['h']['ta'],
                        'away_team': game['v']['ta'],
                        'home_team_id': game['h']['tid'],
                        'away_team_id': game['v']['tid']
                    })

        if not games_today:
            print(f"No games scheduled for {today}.")
        return games_today
    except Exception as e:
        print(f"Error fetching schedule: {e}")
        return []

# Function to fetch DvP stats
def fetch_dvp_stats(team_id, season_type="Regular Season"):
    try:
        stats = TeamVsPlayer(team_id=team_id, season_type=season_type)
        return stats.get_data_frames()[0]  # return the first dataframe
    except Exception as e:
        print(f"Error fetching DvP stats for team {team_id}: {e}")
        return None

# Function to process player data
def process_players(team):
    team_players = team['players']
    player_stats = []
    for player in team_players:
        player_data = {
            'Player': player['full_name'],
            'Position': player.get('position', 'Unknown')  # Handle missing 'POS' field
        }
        player_stats.append(player_data)
    return player_stats

# Fetch team metrics
def fetch_team_metrics():
    try:
        team_metrics = teamestimatedmetrics.TeamEstimatedMetrics(
            season="2024-25", season_type="Regular Season", league_id="00"
        )
        data = team_metrics.get_data_frames()[0]
        metrics = data[['TEAM_NAME', 'E_OFF_RATING', 'E_DEF_RATING', 'E_PACE']]
        metrics_dict = metrics.set_index('TEAM_NAME').to_dict(orient='index')

        # Calculate league averages
        avg_pace = metrics['E_PACE'].mean()
        avg_off_rating = metrics['E_OFF_RATING'].mean()
        avg_def_rating = metrics['E_DEF_RATING'].mean()

        # Map abbreviations to full names
        team_name_mapping = {
            "ATL": "Atlanta Hawks", "BOS": "Boston Celtics", "BKN": "Brooklyn Nets", "CHA": "Charlotte Hornets",
            "CHI": "Chicago Bulls", "CLE": "Cleveland Cavaliers", "DAL": "Dallas Mavericks", "DEN": "Denver Nuggets",
            "DET": "Detroit Pistons", "GSW": "Golden State Warriors", "HOU": "Houston Rockets", "IND": "Indiana Pacers",
            "LAC": "LA Clippers", "LAL": "Los Angeles Lakers", "MEM": "Memphis Grizzlies", "MIA": "Miami Heat",
            "MIL": "Milwaukee Bucks", "MIN": "Minnesota Timberwolves", "NOP": "New Orleans Pelicans", "NYK": "New York Knicks",
            "OKC": "Oklahoma City Thunder", "ORL": "Orlando Magic", "PHI": "Philadelphia 76ers", "PHX": "Phoenix Suns",
            "POR": "Portland Trail Blazers", "SAC": "Sacramento Kings", "SAS": "San Antonio Spurs", "TOR": "Toronto Raptors",
            "UTA": "Utah Jazz", "WAS": "Washington Wizards"
        }

        # Adjusted metrics dictionary
        adjusted_metrics = {}
        for abbr, full_name in team_name_mapping.items():
            if full_name in metrics_dict:
                adjusted_metrics[abbr] = metrics_dict[full_name]
            else:
                print(f"Warning: Metrics not found for {abbr} ({full_name}).")

        return adjusted_metrics, avg_pace, avg_off_rating, avg_def_rating
    except Exception as e:
        print(f"Error fetching team metrics: {e}")
        return {}, 0, 0, 0

# Fetch player estimated metrics for USG%
def fetch_player_usg():
    try:
        stats = playerestimatedmetrics.PlayerEstimatedMetrics(
            season="2024-25", season_type="Regular Season"
        ).get_data_frames()[0]

        usg_data = stats[['PLAYER_ID', 'PLAYER_NAME', 'E_USG_PCT']]
        return usg_data.set_index('PLAYER_ID').to_dict(orient='index')
    except Exception as e:
        print(f"Error fetching player usage metrics: {e}")
        return {}

# Fetch injury data
def fetch_injury_data():
    url = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/injuries"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()

        injury_status_dict = {}  # Store injuries in {player_name: status} format

        for team in data.get('injuries', []):
            for injury in team.get('injuries', []):
                player_name = injury.get('athlete', {}).get('displayName', 'Unknown Player')
                status = injury.get('status', 'Healthy')  # Default to 'Healthy'
                injury_status_dict[player_name] = status

        return injury_status_dict
    except Exception as e:
        print(f"Error fetching injury data: {e}")
        return {}

# Define the adjust_prediction function
def adjust_prediction(stat_mean, team_metrics, opposing_metrics, avg_pace, avg_off_rating, avg_def_rating):
    try:
        # Calculate pace adjustment factor
        pace_factor = team_metrics.get('E_PACE', avg_pace) / avg_pace if avg_pace != 0 else 1

        # Offensive adjustment factor
        offensive_factor = team_metrics.get('E_OFF_RATING', avg_off_rating) / avg_off_rating if avg_off_rating != 0 else 1

        # Defensive adjustment factor (using opponent's defensive rating)
        defensive_factor = opposing_metrics.get('E_DEF_RATING', avg_def_rating) / avg_def_rating if avg_def_rating != 0 else 1

        # Apply adjustments to the stat mean
        adjusted_stat = stat_mean * pace_factor * offensive_factor / defensive_factor
        return adjusted_stat
    except Exception as e:
        print(f"Error adjusting prediction: {e}")
        return stat_mean

# Analyze teams and players for today's games
def analyze_teams_for_today():
    games_today = fetch_schedule()
    team_metrics, avg_pace, avg_off_rating, avg_def_rating = fetch_team_metrics()
    player_usg_data = fetch_player_usg()
    injury_data = fetch_injury_data() # Assuming this function fetches injury
    if not games_today:
        print("No games scheduled for today.")
        return pd.DataFrame()

    all_players_data = []

    for game in games_today:
        home_team = game['home_team']
        away_team = game['away_team']

        if home_team not in team_metrics or away_team not in team_metrics:
            print(f"Metrics not available for one or both teams: {home_team}, {away_team}. Skipping game.")
            continue

        for team_name, opposing_metrics in [(home_team, team_metrics[away_team]), (away_team, team_metrics[home_team])]:
            try:
                team_roster = commonteamroster.CommonTeamRoster(
                    team_id=teams.find_team_by_abbreviation(team_name)['id']
                ).get_data_frames()[0]

                for _, player in team_roster.iterrows():
                    player_id = player['PLAYER_ID']
                    player_name = player['PLAYER']
                    print(f"Fetching data for {player_name} ({team_name})")

                    game_logs = fetch_player_game_logs(player_id)
                    if game_logs.empty:
                        continue

                    mean_ppg, std_dev_ppg, cv_ppg = calculate_stats(game_logs['PTS'])
                    mean_rpg, std_dev_rpg, cv_rpg = calculate_stats(game_logs['REB'])
                    mean_apg, std_dev_apg, cv_apg = calculate_stats(game_logs['AST'])

                    adjusted_ppg = adjust_prediction(mean_ppg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_rpg = adjust_prediction(mean_rpg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)
                    adjusted_apg = adjust_prediction(mean_apg, team_metrics[team_name], opposing_metrics, avg_pace, avg_off_rating, avg_def_rating)

                    all_players_data.append({
                        'Player': player_name,
                        'Position': player['POSITION'],
                        'Team': team_name,
                        'PPG': round(mean_ppg,2),
                        'Adj PPG': round(adjusted_ppg, 2),
                        'PPG SD': round(std_dev_ppg, 2),
                        'PPG CV': round(cv_ppg, 2),
                        'RPG': round(mean_rpg, 2),
                        'Adj RPG': round(adjusted_rpg, 2),
                        'RPG SD': round(std_dev_rpg, 2),
                        'RPG CV': round(cv_rpg, 2),
                        'APG': round(mean_apg, 2),
                        'Adj APG': round(adjusted_apg, 2),
                        'APG SD': round(std_dev_apg, 2),
                        'APG CV': round(cv_apg, 2),
                        'USG%': player_usg_data.get(player_id, {}).get('E_USG_PCT', 'N/A'),
                        'Inj Status': injury_data.get(player_name, 'Healthy')  # Use the fetched injury status
                    })
                    # Add a sleep delay to respect API request limits
                    time.sleep(1)  # Sleep for 1 second between requests
            except Exception as e:
                print(f"Error analyzing team {team_name} or player {player_name}: {e}")
                continue

    # Display the players data
    if all_players_data:
        df = pd.DataFrame(all_players_data)
        display(df)
        return df
    else:
        return pd.DataFrame()

# Start the analysis
analyze_teams_for_today()

from google.colab import data_table
data_table.enable_dataframe_formatter()

Collecting nba_api
  Downloading nba_api-1.11.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from nba_api) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2025.10.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
Downloading nba_api-1.11.1-py3-none-any.whl (316 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.0/316.0 kB 5.6 MB/s eta 0:00:00
Installing collected packages: nba_api
Successfully installed nba_api-1.11.1
No games scheduled for 2025-11-12.
Error fetching player usage metrics: name 'playerestimatedmetrics' is not defined
No games scheduled for today.